### DISCUSSION TITLE
How to load assets from dbt project?

### DISCUSSION THREAD

**Discussion by hypr-platform** [dagster-io/dagster#12893] [Q&A] [answered]
I'm trying to load assets from my dbt project called "dbtz", but i'm receiving the error

```
hyprster:dagster_dbt.errors.DagsterDbtCliFatalRuntimeError: Fatal error in the dbt CLI (return code 2): Encountered an error while reading the project:  ERROR: Runtime Error
  Could not find profile named dbtz Encountered an error:
Runtime Error
  Could not run dbt
```

the dbt run works fine on the command line, but i just can't use it on dagster

code & error:

![image](https://user-images.githubusercontent.com/119820316/224391430-6634487a-0693-4ed0-a6fd-f118e0dc9583.png)

my profiles.yml is:

```
dbtz:
  target: dev
  outputs:
    dev:
      dataset: dev
      job_execution_timeout_seconds: 600
      job_retries: 0
      keyfile: ../service_account.json
      location: US
      method: service-account
      priority: interactive
      project: site-hypr
      threads: 1
      type: bigquery
    prod:
      dataset: prod
      job_execution_timeout_seconds: 600
      job_retries: 0
      keyfile: ../service_account.json
      location: US
      method: service-account
      priority: interactive
      project: site-hypr
      threads: 1
      type: bigquery
```
