### DISCUSSION TITLE
How do I set variables for jobs as for user deployment?

### DISCUSSION THREAD

**Discussion by anutator** [dagster-io/dagster#12986] [Q&A] [answered]
I've set secret variables for concrete user deployment. I can see this variables in pod, but they are not passed to job.
I don't want to set the same variables for all jobs in dagster helm chart. I'd like to have variabes for job equal to variables for user deployment.
I don't understand the meaning of includeConfigInLaunchedRuns (true in my values) and DAGSTER_CLI_API_GRPC_CONTAINER_CONTEXT.

```yml
            {{- $includeConfigInLaunchedRuns := $deployment.includeConfigInLaunchedRuns | default (dict "enabled" true) }}
            {{- if $includeConfigInLaunchedRuns.enabled }}
            # uses the auto_envvar_prefix of the dagster cli to set the --container-context arg on 'dagster api grpc'
            - name: DAGSTER_CLI_API_GRPC_CONTAINER_CONTEXT
              value: {{ include "dagsterUserDeployments.k8sContainerContext" (list $ $deployment) | fromYaml | toJson | quote }}
            {{- end }}
```

Does the job take variables from configmap ....-user-env?

**Comment by anutator** [comment, marked as answer]
Now I can get standart variables for deployment pod and jobs from env and secret variables from secret "myapp":

```yml
deployments:
  - name: myapp
    ...
    env:
       TEST1: testanna1
       TEST2: testanna2
...
    envSecrets:
      - name: myapp
```

I've created file `secret.yml` in helm chart. I had to use index 0 for name because in one Gitlab repo I have one project which creates one user deployment in Gitlab CI/CD pipeline.

```yml
apiVersion: v1
kind: Secret
metadata:
  name: {{ (index .Values.deployments 0).name }}
  labels: {{- include "dagster.labels" $ | nindent 4 }}
type: Opaque
data:
{{- include "GetSecretEnvs" . | indent 2 }}
```
I keep all my secrets encripted with Mozilla SOPS+age in Gitlab. In deploy job they are automatically decrypted using helm (with plugin "secrets") .
