### DISCUSSION TITLE
How to deploy a Dagster project with a dbt project

### DISCUSSION THREAD

**Discussion by slopp** [dagster-io/dagster#13767] [Q&A] [answered]
This GH discussion https://github.com/dagster-io/dagster/discussions/12248 suggests placing a dbt project inside of a Dagster project. However often your dbt project is located in a different folder or even a different Git repo. How do I deploy to Dagster in these scenarios?

**Comment by slopp** [comment, marked as answer]
# For different repos

If you have a dagster repo and a dbt repo, one approach is to setup the dagster repo's CICD to clone the dbt repo into a subdirectory prior to building. Then setup a dispatch action on dbt repo to ensure changes to dbt trigger a deploy of dagster.

Example: 
- https://github.com/slopp/dagsterproj
- https://github.com/slopp/dbtproj

**Reply by tacastillo** [reply]
Another option for keeping Dagster up-to-date with dbt and not using a monorepo is:

If you're pulling the dbt project (either manifest or code) at definition-time is to have your dbt project trigger a GraphQL mutation that reloads the Dagster project on dbt's CD.

Here's a sample GraphQL snippet + Python wrapper code that you can add to your dbt project's CD pipeline:


```python
# install with pip install "gql[aiohttp]"

from gql import Client, gql
from gql.transport.aiohttp import AIOHTTPTransport

ENDPOINT = "http://localhost:3000/graphql"

client = Client(
    transport=AIOHTTPTransport(url=ENDPOINT),
    fetch_schema_from_transport=True,
)

query = gql("""
    mutation refreshDefinitions(
        $locationName: String!
    ) {
    reloadRepositoryLocation(
        repositoryLocationName: $locationName
    ) {
        ... on WorkspaceLocationEntry {
        loadStatus
        }
        ... on Error {
            message
            __typename
        }
    }
    }
"""
)

client.execute(query)
```

**Comment by slopp** [comment]
# For a mono-repo

If you have a single repo where the dbt project is in a top-level directory, and the dagster project is separate, you can setup CICD to copy the dbt project into the dagster project during deployment.

For example: 

```
pkg-etl/
  pkg_etl/
  pyproject.toml
  setup.cfg
  ...
transform/
```

You could use a GitHub action structure like: 

```
   - name: Checkout
        if: env.ENABLE_FAST_DEPLOYS == 'true'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          path: project-repo

      - run: pip install --upgrade pip && pip install --upgrade dbt-snowflake pyOpenSSL
      - run: dbt deps --project-dir $GITHUB_WORKSPACE/project-repo/transform

      - run: cp -r $GITHUB_WORKSPACE/project-repo/transform $GITHUB_WORKSPACE/project-repo/pkg-etl/dbt_project
 ```

along with a dagster_cloud.yaml file with: 

```
locations:
  - location_name: pkg-etl
    code_source:
      package_name: pkg_etl
    build:
      directory: ./pkg-etl
```

**Comment by slopp** [comment]
Also keep in mind the steps for dbt deps installs: https://github.com/dagster-io/dagster/discussions/12180

**Comment by mjkanji** [comment]
@slopp Would it be possible to update the sample CI/CD workflow files for different Dagster and DBT repos to more closely align with the most recent changes to the quickstart repos? The example files here are about a year old now, while the recommended quickstart CI/CD files have changed quite significantly since.

For example, the [workflow file in the dagster-cloud-serverless-quickstart repo](https://github.com/dagster-io/dagster-cloud-serverless-quickstart/blob/main/.github/workflows/deploy.yml) does not checkout the action-repo manually. 

There are now also two types of deployments (Docker-based and PEX-based), which further complicates things. It would also be great if you could add comments to the workflow files in your examples to more clearly delineate the specifics changes, compared to the default template, that are required for DBT.

**Reply by mjkanji** [reply]
I was able to get around this issue and have the DBT repo show up by making it a submodule of the Dagster repo and making the following change to the workflow file:

Before:

```yaml
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Checkout DBT repo
        uses: actions/checkout@v3
        with:
          repository: org/dbt-repo
          ref: main
          path: dbt
          token: ${{ secrets.DBT_REPO_PAT }}
```

After:

```yaml
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.DBT_REPO_PAT }}
          submodules: recursive
```

That seems to fix the issue, though I'm not sure why submodules work but simply checking the repo out as a separate step doesn't (I'd prefer to not use submodules, if possible).
