### DISCUSSION TITLE
Reload workspace without restarting pods and interrupting running jobs

### DISCUSSION THREAD

**Discussion by anutator** [dagster-io/dagster#14124] [Q&A]
I deploy dagster to kubernetes using Gitlab CI. Workspace:

```yml
dagit:
  workspace:
    servers:
      - host: dagster-metrika-logs
        port: 4001
      - host: dagster-oprosso-api
        port: 4003
      - host: dagster-synch-clickhouse
        port: 4005
....
```

When we change workspace and deploy new values 3 dagster infra pods are terminated and the new one are started (daemon, dagit, dagit-read-only).

We'd like to use 'Reload all' button on the Reload page. I tried to delete  checksum test for configmap for dagit in annotations, dagit pods are not restarted, but I can  manually reload workspace only on standard Deployment web page (not read-only web-interface). Besides there is a checksum control in daemon template. Does daemon restart interrupt jobs running?

Besides there is an `externalConfigmap` but I don't know how to use it. I didn't find an example.

Please tell me how to reload workspace without restarting 3 pods or how to use `externalConfigmap`.
