### DISCUSSION TITLE
How do I terminate all runs that are currently queued?

### DISCUSSION THREAD

**Discussion by gibsondan** [dagster-io/dagster#14203] [Q&A] [answered]
Is there a way to clear the entire run queue in Dagster?

**Comment by gibsondan** [comment, marked as answer]
We're actively working on enabling bulk termination in the Dagster UI. In the meantime, running a script like this will clear out the queue:

```
from dagster import DagsterInstance, RunsFilter, DagsterRunStatus

instance = DagsterInstance.get() # needs your DAGSTER_HOME to be set

while True:
    queued_runs = instance.get_runs(limit=100, filters=RunsFilter(statuses=[DagsterRunStatus.QUEUED]))
    if not queued_runs:
        break
    for run in queued_runs:
        instance.report_run_canceled(run)
```

If you're running Dagster in Kubernetes, Running `kubectl exec` into the Dagit pod and running this script will also work.

**Comment by gibsondan** [comment]
A way to do the above with Dagster Cloud:

a) Create a dagster.yaml file locally with the following contents, adding an agent token in the `agent_token` field (and changing the deployment name if it's something other than 'prod'):


```
instance_class:
  module: dagster_cloud.instance
  class: DagsterCloudAgentInstance

dagster_cloud_api:
  agent_token: <YOUR_AGENT_TOKEN>
  deployment: prod

user_code_launcher:
  module: dagster_cloud.workspace.user_code_launcher
  class: ProcessUserCodeLauncher
```

b) Run the following command in the same folder as the `dagster.yaml` file you created, in an environment with the `dagster-cloud` Python package installed:
```
DAGSTER_HOME=$PWD python script.py
```
(where script.py is a file containing the script in the answer above that iterates through the runs)
