### DISCUSSION TITLE
How to set the repository name ?

### DISCUSSION THREAD

**Discussion by dmarteau** [dagster-io/dagster#14590] [Q&A]
Hi

I have a grpc repository location that load a single package (`-m <my_package>`].    

When requesting repositories with graphQL, the repository name is `__repository__`.

How to change the repository name to something more convenient ?  I'm using `Definitions` in the  `my_package/__init__.py` and I cannot figure out how to set the repository_name as with the   `@repository` declaration which has a `name` argument.

Thanks

**Comment by clairelin135** [comment]
Hi @dmarteau. Are you using a workspace.yaml? You can [set a location name on the workspace.yaml](https://docs.dagster.io/concepts/code-locations/workspace-files#initializing-the-server):

```
# workspace.yaml

load_from:
  - grpc_server:
      host: localhost
      port: 4266
      location_name: "my_grpc_server"
```
