### DISCUSSION TITLE
How to switch to in-process execution behavior

### DISCUSSION THREAD

**Discussion by dpeng817** [dagster-io/dagster#15248] [Q&A] [answered]
Assuming you are using the default `multi_or_in_process` executor, you can specify this using the following config block:

```yaml
execution:
  config:
    in_process:
```
