### DISCUSSION TITLE
[S3ComputeLogManager] How to upload compute logs automatically

### DISCUSSION THREAD

**Discussion by clairelin135** [dagster-io/dagster#16407] [Q&A] [answered]
I'm not seeing logs in my s3 bucket, how can I make them visible?

**Comment by clairelin135** [comment, marked as answer]
By default `S3ComputeLogManager` will only upload logs on termination, there might have been something preventing it being marked as failed/successful and trigger the log file upload.

You can configure an upload interval if you'd like, via your dagster.yaml:
```
compute_logs:
  module: dagster_aws.s3.compute_log_manager
  class: S3ComputeLogManager
  config:
    upload_interval: 30
```
