### DISCUSSION TITLE
How to load dbt source description and metadata into Dagster

### DISCUSSION THREAD

**Discussion by csaba-pusztai** [dagster-io/dagster#16470] [Q&A] [answered]
I have successfully integrated a dbt model into Dagster. Description and metadata are correctly pulled in by Dagster for my tables and visible both in the graph (the description) and the corresponding asset detail pages . However, `source` details do not seem to be populated when I click on the asset details. The model runs nicely via Dagster and sources appear in the graph. 

My dummy dbt `schema.yml` is as follows:
```
version: 2

models:
  - name: test_model_1
    description: "This model contains user-level revenue data aggregated at the monthly level."
    columns:
      - name: n_of_rows
    config:
      meta:
        dagster:
          group: revenue

sources:
  - name: external
    description: "This is an external source"
    database: ext
    schema: ext
    tables:
    - name: payments
      description: "User payment data"
      meta:
        dagster:
          group: revenue
```

More specifically:
- I do get to see "This model contains user-level revenue data aggregated at the monthly level." for my `test_model_1` in the graph node and  on the asset profile.
- But I do not see "User payment data" either in the graph node or the asset profile.
