### DISCUSSION TITLE
Default max concurrent run of assets

### DISCUSSION THREAD

**Discussion by Aluriak** [dagster-io/dagster#16791] [Q&A] [answered]
Hi !
I am maintaining a dagster self-hosted instance, and trying to achieve the following: 

* by default, any asset should run with maximum 1 process
* it is possible to allow for a specific asset to get a higher limit (i plan to  [use tags](https://docs.dagster.io/guides/limiting-concurrency-in-data-pipelines#limiting-opasset-concurrency-across-runs) for that)

Currently, i have that configuration:

```yaml
run_coordinator:
  module: dagster._core.run_coordinator
  class: QueuedRunCoordinator
  config:
    max_concurrent_runs: 1
    tag_concurrency_limits:
    - key: threadlimit
      limit: 20
      value: nolimit
    - key: threadlimit
      limit: 5
      value: robust
```

I understand that, because of the global limit set by `max_concurrent_runs`, only one process can work, whatever the per-asset threadlimit is.

However, as i'm working with very fragile data sources, having multiple processes of the same asset may have unwanted consequences.
I can't therefore set `max_concurrent_runs` to 20, because, if i make a typo in (or just forget) the tag of an asset, i may end up being responsible for data loss.

My question is then : how can i ensure that only one process of each asset can run, unless, for specific assets, where having exactly the good tags allow for more ?

Thank you in advance for your help !
Best regards,
