### DISCUSSION TITLE
Unexpected behavior when running many concurrent jobs

### DISCUSSION THREAD

**Discussion by dagsir** [dagster-io/dagster#17731] [Q&A] [answered]
I've got a partial conflict in how to performatively run many jobs with Dagster. I've got a RunQueue with a max of 25 concurrent jobs, and I'm calling the InProcessExecutor to run jobs with as little initialisation time between each op.

But I'm barely seeing more than 3 jobs concurrently unless a job starts failing. Each job takes around ~1.5s, and when I tested the MP Executor I was seeing 25s per job or more in just overhead for running the 5 ops involved, so I'm hesitant to use that.

Is the best option here to use something like the CeleryExecutor, or am I missing something?

---

*The question was originally asked in [Dagster Slack](https://dagster.slack.com/archives/C01U954MEER/p1699268419407239?thread_ts=1699268419.407239&cid=C01U954MEER).*

**Comment by jamiedemaria** [comment, marked as answer]
You can modify how many runs are pulled from the run queue by modifying some settings 

```
run_coordinator:
  module: dagster.core.run_coordinator
  class: QueuedRunCoordinator
  config:
    dequeue_use_threads: true
    dequeue_num_workers: 8
```

https://docs.dagster.io/deployment/dagster-instance#queuedruncoordinator
