### DISCUSSION TITLE
Max concurrent runs for partitioned asset

### DISCUSSION THREAD

**Discussion by dagsir** [dagster-io/dagster#17741] [Q&A] [answered]
hello everyone, im trying to find documentation about max concurrent runs in a partitioned asset, can someone help me? basically i have a partitioned asset that i need to configure to 1 max partitioned run per time

i tried to add `backfill_policy=BackfillPolicy.single_run()` on the asset definition, but it not worked

and i already tried to add the following on the define_asset_job, but it not worked and affected other assets executions

```config = {
        'execution': {
            'config': {
                'multiprocess' : {
                    'max_concurrent': 1,
                }
            }
        }
    }```


---

*The question was originally asked in [Dagster Slack](https://dagster.slack.com/archives/C01U954MEER/p1699305023189279?thread_ts=1699305023.189279&cid=C01U954MEER).*

**Comment by hypr-platform** [comment, marked as answer]
i fixed adding this to the dagster.yaml

```
run_queue:
  max_concurrent_runs: 10
  tag_concurrency_limits:
    - key: "backfill"
      limit: 3
    - key: "destination"
      value: "bigquery"
      limit: 3
```
      
and setting the op tags on my assets and ops
