### DISCUSSION TITLE
How do I configure the DuckDB IO manager to load from a custom schema?

### DISCUSSION THREAD

**Discussion by malow106** [dagster-io/dagster#17850] [Q&A] [answered]
Hi all,

I implement DBT+DuckDB pipeline. 
I try to load data from `duckDB/DBT asset` into `dagster asset`. 

My **dbt_project.yml** :
```
models:
  DBT_proj:
    DATAMART:
      +schema: datamart
      +materialized: table
      +meta:
        dagster:
          group: "DBT_PUBLISHING"
          auto_materialize_policy:
            type: 'lazy'
```
My **profiles.yml** :
```
duck_profile:
  target: default
  outputs:
    default:
      type: duckdb
      path: my_db.duckdb
      schema: dev
```
 The duckdb/dbt generated schema is the concatenation of both **profiles.yml** and **dbt_project.yml** schemas
-> for my table :  **dev_datamart.stocks** 
![git_discussion](https://github.com/dagster-io/dagster/assets/26186200/20c215f5-5300-4383-aa6d-9c8df6746d60)

Here my dagster asset to get this table : 
```
@asset(
    ins={
        "stocks": AssetIn(
            key=get_asset_key_for_model([my_dbt_assets], "stocks"),
        )
    }
)
def export_stocks(stocks):
   ...
```

The error : 
```
dagster._core.errors.DagsterExecutionLoadInputError: Error occurred while loading input "stocks" of step "export_stocks"::

duckdb.duckdb.CatalogException: Catalog Error: Table with name stocks does not exist!
Did you mean "dev_datamart.stocks"?
LINE 1: SELECT * FROM datamart.stocks
                      ^
```
Dagster seems not considering **profiles.yml** schema, is it intentional ? 
As a workaround tried to customize `get_asset_key_for_model` asset key but this is out of my skills..

Thanks !
