### DISCUSSION TITLE
Github actions pex-based pipeline completion time

### DISCUSSION THREAD

**Discussion by ivan-tsarev-bioage** [dagster-io/dagster#18148] [Q&A]
Hi everyone!
I'm working on our Dagster Cloud deployment workflow and trying with switch from old Docker-based builds to pex-based.

Before that we have old docker-based pipeline with 3 code locations. All locations have same dependencies and were built in about 10 minutes each. So in total the whole deployment took like 11 minutes or so since locations were build in parallel in different jobs.

However after switch to pex fast deploy, the pipeline takes like ~30 min to run.

It looks like it always rebuild all code locations independent on what code changes were made, were dependencies changed and so on. And it also basically builds the exact same set of dependencies for all three code location taking x3 time for it.
Is there any kind of magic I missed to make it works actually fast and not rebuild everything from scratch every time?

Just a wild guess, that I have to merge it into master and take a look how further deployments will perform on top of it, but I'm not sure will it actually work and don't want to merge huge (possible worsening) changes without confirmation :)

**Comment by shalabhc** [comment]
Can you share how your dependencies are specified - are they in a `setup.py` or `requirements.txt` and is that file hand written or generated?

Also can you share where the pex deploys are running - are you using the github action or if you have your own commands, can you share what you are running?

When running your own command you want to specify `--deps-cache-from=tag` and `--deps-cache-to=tag` to the `deploy-python-executable` command. This will cache the dependencies and reuse them. The `tag` can be any string you specify - it should just match for both flags.

**Reply by mudravrik** [reply]
> Can you share how your dependencies are specified - are they in a setup.py or requirements.txt and is that file hand written or generated?

I believe I tried both ways - starting with requirements.in + pip-tools generated requirements.txt, then switched to just hand-written setup.py after some errors from local setuptools, so right now it's something like:
```
setup(
    name="data-platform-dagster",
    packages=find_packages(exclude=["data_platform_dagster_tests", "scripts"]),
    install_requires=[
        "dagit~=1.5",
        "dagster~=1.5",
        "dagster-cloud~=1.5",
        "dagster-dbt",
        "dagster_slack",
        "google-cloud-bigquery[pandas]~=3.11.4",
        "google-cloud-storage~=2.7.0",
        "google-cloud-dataproc~=5.4.1",
        "pandas~=1.5",
        "python-dateutil~=2.8.2",
        "python-dotenv~=0.21.0",
        "codaio~=0.6.10",
        "requests~=2.31",
        "numpy~=1.24.2",
        "pytz~=2022.7.1",
        "neo4j~=5.6.0",
        "aiohttp~=3.8.4",
        "great_expectations~=0.17",
    ],
    extras_require={"dev": ["dagster-webserver", "pytest"]},
)
```

> Also can you share where the pex deploys are running - are you using the github action or if you have your own commands, can you share what you are running?

Using the workflow delivered by fresh dagster cloud setup - have to actually create new project to get this file because resolving of what is an actual version just from your github appeared to be quite a challenge :)
So .github/workflows/branch_deployments.yaml looks like this:
```
name: Serverless Branch Deployments
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

concurrency:
  group: ${{ github.ref }}/branch_deployments
  cancel-in-progress: true

env:
  DAGSTER_CLOUD_URL: "http://*****.dagster.cloud"
  DAGSTER_CLOUD_API_TOKEN: ${{ secrets.DAGSTER_CLOUD_API_TOKEN }}
  ENABLE_FAST_DEPLOYS: "true"
  PYTHON_VERSION: "3.11"
  DAGSTER_CLOUD_FILE: "dagster_cloud.yaml"

jobs:
  dagster_cloud_default_deploy:
    name: Dagster Serverless Deploy
    runs-on: ubuntu-20.04
    outputs:
      build_info: ${{ steps.parse-workspace.outputs.build_info }}

    steps:
      - name: Prerun Checks
        id: prerun
        uses: dagster-io/dagster-cloud-action/actions/utils/prerun@v0.1

      - name: Launch Docker Deploy
        if: steps.prerun.outputs.result == 'docker-deploy'
        id: parse-workspace
        uses: dagster-io/dagster-cloud-action/actions/utils/parse_workspace@v0.1
        with:
          dagster_cloud_file: $DAGSTER_CLOUD_FILE

      - name: Checkout for Python Executable Deploy
        if: steps.prerun.outputs.result == 'pex-deploy'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          path: project-repo

      - name: Python Executable Deploy
        if: steps.prerun.outputs.result == 'pex-deploy'
        uses: dagster-io/dagster-cloud-action/actions/build_deploy_python_executable@v0.1
        with:
          dagster_cloud_file: "$GITHUB_WORKSPACE/project-repo/$DAGSTER_CLOUD_FILE"
          build_output_dir: "$GITHUB_WORKSPACE/build"
          python_version: "${{ env.PYTHON_VERSION }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  dagster_cloud_docker_deploy:
    name: Docker Deploy
    runs-on: ubuntu-20.04
    if: needs.dagster_cloud_default_deploy.outputs.build_info
    needs: dagster_cloud_default_deploy
    strategy:
      fail-fast: false
      matrix:
        location: ${{ fromJSON(needs.dagster_cloud_default_deploy.outputs.build_info) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Build and deploy to Dagster Cloud serverless
        uses: dagster-io/dagster-cloud-action/actions/serverless_branch_deploy@v0.1
        with:
          dagster_cloud_api_token: ${{ secrets.DAGSTER_CLOUD_API_TOKEN }}
          location: ${{ toJson(matrix.location) }}
          base_image: "python:${{ env.PYTHON_VERSION }}-slim"
          # Uncomment to pass through Github Action secrets as a JSON string of key-value pairs
          # env_vars: ${{ toJson(secrets) }}
          organization_id: ${{ secrets.ORGANIZATION_ID }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
