### DISCUSSION TITLE
Make dbt auto-materialize policy configurable on a project or schema level

### DISCUSSION THREAD

**Discussion by jonathanneo** [dagster-io/dagster#18197] [Q&A] [answered]
Dbt's auto-materialize policy is only available on a dbt node level when configuring using the "meta config" approach detailed here: https://docs.dagster.io/integrations/dbt/reference#customizing-auto-materialize-policies 

It would be great this can also apply to either a project, or schema level. 

Project level: 

```yaml
models:
    config:
      meta:
        dagster:
          auto_materialize_policy:
            type: eager
```

Schema level: 

```yaml
models:
  person:
    raw:
      +schema: raw
      config:
        meta:
          dagster:
            auto_materialize_policy:
              type: eager
```

**Comment by jonathanneo** [comment]
@rexledesma

**Comment by OwenKephart** [comment]
@jonathanneo one other option along these lines would be to use the `DagsterDbtTranslator` class ([here](https://docs.dagster.io/integrations/dbt/reference#customizing-auto-materialize-policies)). This gives you the freedom to apply policies based on whatever dbt metadata you wish

**Reply by jonathanneo** [reply]
Yes, I am using that at the moment. But I think the option to do it via the dbt configuration files facilitates a better user experience.

That way, Analytics Engineers who only know dbt can easily configure the policies themselves without having to learn how to do it in dagster.

**Reply by jonathanneo** [reply]
This also applies to `FreshnessPolicy`, which is something that Analytics Engineers would like to configure themselves as well.

**Reply by OwenKephart** [reply, marked as answer]
@jonathanneo gotcha -- I think I misunderstood the original question, and what you're looking for is already possible. The trick is that in your examples you're specifying "meta" underneath the "config" key, whereas you need to just specify it directly under the meta key:

```
models:
   +meta:
      dagster:
        auto_materialize_policy:
          type: eager
```
