### DISCUSSION TITLE
'Env var required but not provided' error in 'dbt parse' during CI/CD, even though I've added the env var to Dagster Cloud

### DISCUSSION THREAD

**Discussion by dagsir** [dagster-io/dagster#18280] [Q&A] [answered]
I've added a profiles.yaml inside my DBT repo itself (which seems to be the recommended way for Dagster). The config values are defined by environment variables. I then added a dbt parse command to dagster_cloud_post_install.sh. Unfortunately, however, I'm getting an error saying Env var required but not provided: 'DBT_LOCAL_SCHEMA', even though I have added this env variable to Dagster Cloud already.

My profiles.yaml:

```
config:
  send_anonymous_usage_stats: false

pinwheel_analytics:
  target: local
  outputs:
    local:
      type: redshift
      schema: "{{ env_var('DBT_LOCAL_SCHEMA') }}"
      threads: 4

      dbname: "dev"
      host: "{{ env_var('DBT_ENV_SECRET_REDSHIFT_HOST') }}"
      port: 5439
      user: "{{ env_var('DBT_ENV_SECRET_REDSHIFT_USERNAME') }}"
      password: "{{ env_var('DBT_ENV_SECRET_REDSHIFT_PASSWORD') }}"

    branch:
      type: redshift
      schema: test_dbt
      threads: 4

      dbname: "dev"
      host: "{{ env_var('DBT_ENV_SECRET_REDSHIFT_HOST') }}"
      port: 5439
      user: "{{ env_var('DBT_ENV_SECRET_REDSHIFT_USERNAME') }}"
      password: "{{ env_var('DBT_ENV_SECRET_REDSHIFT_PASSWORD') }}"

    prod:
      type: redshift
      schema: dbt
      threads: 4

      dbname: "dev"
      host: "{{ env_var('DBT_ENV_SECRET_REDSHIFT_HOST') }}"
      port: 5439
      user: "{{ env_var('DBT_ENV_SECRET_REDSHIFT_USERNAME') }}"
      password: "{{ env_var('DBT_ENV_SECRET_REDSHIFT_PASSWORD') }}"
```

My dagster_cloud_post_install.sh:

```
dbt deps --project-dir ./dbt
dbt parse --project-dir ./dbt --target-path ./dbt/target/ --profiles-dir ./dbt/config/
```

---

*The question was originally asked in [Dagster Slack](https://dagster.slack.com/archives/C02LJ7G0LAZ/p1700697054141889?thread_ts=1700697054.141889&cid=C02LJ7G0LAZ).*

**Comment by gibsondan** [comment, marked as answer]
Adding an environment variable in Dagster Cloud will cause that environment variable to be read in when your Dagster definitions are loaded in Dagster Cloud, but will not have any affect on commands that are run during CI/CD in your Github Action. If you need environment variables to be available during your Github action, you should add them as secrets to the Github repository following the instructions here: https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#creating-secrets-for-a-repository

**Reply by mjkanji** [reply]
Adding a note that alongside setting the relevant variables as secrets to the GH repo, you also need to explicitly pass the secrets to the Docker container in the Build and Deploy to Dagster Cloud step as follows:

```yaml
      - name: Build and deploy to Dagster Cloud serverless
        uses: dagster-io/dagster-cloud-action/actions/serverless_prod_deploy@v0.1
        with:
          dagster_cloud_api_token: ${{ secrets.DAGSTER_CLOUD_API_TOKEN }}
          location: ${{ toJson(matrix.location) }}
          base_image: "python:${{ env.PYTHON_VERSION }}-slim"
          # Uncomment to pass through Github Action secrets as a JSON string of key-value pairs
          env_vars: ${{ toJson(secrets) }}
          organization_id: ${{ secrets.ORGANIZATION_ID }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

The `env_vars: ${{ toJson(secrets) }}` is commented out by default in Dagster examples, but without it, the relevant secrets won't be forwarded to the Docker container, resulting in the same error.
