### DISCUSSION TITLE
how to map a code location from Dagster Cloud hybrid onto the Dagster open source helm chart

### DISCUSSION THREAD

**Discussion by dagsir** [dagster-io/dagster#18354] [Q&A] [answered]
I'm trying to deploy dagster with helm.

I used to have it working in dagster cloud in a hybrid mode.

I had one code location like this

```
image: europe-west1-docker.pkg.dev/$accountname/main/dagster:$sha
package_name: dbt_data_stack
```

I assume in Helm I need to configure this as a `dagster-user-deployments` , right?

Should something like this work? Or did I misuderstood what `dagster-user-deployments`is?
```
dagster-user-deployments:
  enabled: true
  deployments:
    - name: "k8s-example-user-code-1"
      image:
        repository: "<http://docker.io/dagster/user-code-example|docker.io/dagster/user-code-example>"
        tag: latest
        pullPolicy: Always
      dagsterApiGrpcArgs:
        - "--python-file"
        - "/example_project/example_repo/repo.py"
      port: 3030
    - name: "dbt_data_stack"
      image:
        repository: "europe-west1-docker.pkg.dev/$account_name/main/dagster"
        tag: $sha
        pullPolicy: Always
```
---

*The question was originally asked in [Dagster Slack](https://dagster.slack.com/archives/C014N0PK37E/p1701215022684309?thread_ts=1701215022.684309&cid=C014N0PK37E).*
