### DISCUSSION TITLE
Recommended way to clean up docker containers?

### DISCUSSION THREAD

**Discussion by poweribo** [dagster-io/dagster#18536] [Q&A]
How do you make sure the generated docker containers for every run gets cleaned up after? I've noticed Dagster uses up a lot of space after a few weeks of run. we have more than a dozen jobs running from 15mins, daily to weekly. We manually run docker prune right now but is this what others do? Does Dagster actively cleanup unused docker containers?

**Comment by clyons42** [comment]
@poweribo   I ran into this same issue and the solution is pretty straightforward, although not obvious given the dagster documentation.  The dagster_run_launcher.py file leverages the docker module to create and run the containers.  The containers are created using the create method of the container class: 

[Python Docker Container Class](https://docker-py.readthedocs.io/en/stable/containers.html#)
  
```
container = client.containers.create(
                image=docker_image,
                command=command,
                detach=True,
                environment=docker_env,
                network=container_context.networks[0] if len(container_context.networks) else None,
                **container_context.container_kwargs,
            )

```

In your dagster.yml file you can specify the contents of container_kwargs you see above which will be passed into the create method.   One of the arguments the create method takes is "auto_remove: bool".  So you can simply set the "auto_remove: True" key/value in your dagster.yml file. 


```
run_launcher:
  module: dagster_docker
  class: DockerRunLauncher
  config:
    env_vars:
      - DAGSTER_POSTGRES_USER
      - DAGSTER_POSTGRES_PASSWORD
      - DAGSTER_POSTGRES_DB
      - DAGSTER_POSTGRES_HOST
      - DAGSTER_LOCAL_ARTIFACT_STORAGE_DIR
    image: "<docker image to use>"
    network: "<docker network>"
    container_kwargs:
      auto_remove: True
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /tmp/io_manager_storage:/tmp/io_manager_storage
        - /development/local_repos/dagster-primary-code-location/src/dagster-primary-code-location:/opt/dagster/dagster-primary-code-location/src/dagster-primary-code-location
        - /development/dagster_storage:/opt/dagster/dagster_home/storage
```

If you already figured this out, excellent!  Perhaps someone else can benefit....
