### DISCUSSION TITLE
how to use "secrets_tag" in ECS deployment

### DISCUSSION THREAD

**Discussion by will-regal-voice** [dagster-io/dagster#18761] [Q&A] [answered]
The dagster docs [docs](https://docs.dagster.io/deployment/guides/aws#secrets-management-in-ecs) say the following
```
run_launcher:
  module: "dagster_aws.ecs"
  class: "EcsRunLauncher"
  config:
    secrets_tag: "my-tag-name"
```

> In this example, any secret tagged with my-tag-name will be included as an environment variable with the name and value as that secret.

I'm trying to determine how exactly this works.  What does "tagged with my-tag-name" mean?  AWS tags are key-value pairs, so does this mean regardless of the key, any secret with that _value_ gets included?
