### DISCUSSION TITLE
dagster dbt disable specific dbt tests based on tags (or select long-running tests to operate on a different cadence)

### DISCUSSION THREAD

**Discussion by geoHeil** [dagster-io/dagster#18957] [Q&A] [answered]
Recently, new features have been added to dagster to allow filtering DBT asset checks based on tags https://github.com/dagster-io/dagster/issues/17372

@johannkm `build_dbt_asset_selection` looks great. 
However: `@dbt_assets(manifest=dbt_manifest_path, exclude="tag:long_running_test",)` does NOT exclude the tests I want to exclude or execute on a different cadence.

How is the exclude supposed to work for `@dbt_assets` API?

FYI: https://github.com/dagster-io/dagster/issues/17628 is hopefully not relevant

As it is a (not yet dagster supported relationship tests) I want to not (yet) load it to dagster.

The test looks like this (for a whole object/table):

```
tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - primary_key_id_col
            - timestamp_col
```
