### DISCUSSION TITLE
Prevent certain jobs running when a particular job is running

### DISCUSSION THREAD

**Discussion by the4thamigo-uk** [dagster-io/dagster#19011] [Q&A] [answered]
Hi, I have a concurrency issue, I would be interested if anyone has a similar use case and maybe ideas of how to solve it:

I have about 30 assets that load raw data into a database on different schedules with different partition structures (mainly hourly and daily). I also have a dbt asset to transform this data (daily partitions). I would like to prevent the raw data assets from loading raw data into the database while the dbt model is running. 

This is not dbt-specific of course: In general, if I have a job J (e.g. dbt), and several other jobs j1,j2,j3 I want to somehow enforce these concurrency constraints : 

* If J1 IS running,  then  j1,j2,j3  SHOULD NOT be running
* If one or more of j1,j2,j3 ARE running, then  J1 SHOULD NOT be running

I have thought about giving each of the j1,j2,j3 its own tag with concurrency set to `1`, and assigning all of these the tags also to J, so that neither j1 & J can run concurrently (or j2 & J or J3 & J). This would be fine except for the fact that this unnecessarily limits the concurrency of j1 (or j2 or j3) to `1` when J is not running. 

How can I achieve this?

**Comment by rexledesma** [comment, marked as answer]
I'm going to edit your notation a bit, since using `J` and `j` is a bit confusing.

Assuming that you have jobs `A`, `X`, `Y`, `Z`:

- If `A` is running, `X`, `Y`, `Z` should not be running.
- If one of `X`, `Y`, `Z` are running, then `A` should not be running.

One way to do this using our concurrency tags is to:

- Tag job `X` with `X`.
- Tag job `Y` with `Y`.
- Tag job `Z` with `Z`.
- Tag job `A` with `X`, `Y`, `Z`.
- Enforce concurrency limits on each of `X`, `Y`, `Z` to 1.

However, one problem with this is that job `A` will only be scheduled if there's a period of time where job `X`, `Y`, and `Z` are not running.

**Reply by the4thamigo-uk** [reply]
Well yes, this is the suggestion I made above, but that means that when A is not running, you cant have more than one of X running. If X is partitioned this is an unnecessary throttle.

**Reply by rexledesma** [reply]
Apologies, I didn't initially understand what you had proposed. Yeah, looks like we have the same solutions.

I don't think our current concurrency tag scheme will support your use-case. Feel free to submit a feature request.

**Comment by the4thamigo-uk** [comment]
@rexledesma What do you think of this proposal?

```
tag_concurrency_limits:
    - key: "my_tag"
      value: A
      exclude:
            - key: my_tag
              value: X
            - key: my_tag
              value: Y
            - key: my_tag
              value: Z
    - key: "my_tag"
      value: X
      exclude:
            - key: my_tag
              value: A
    - key: "my_tag"
      value: Y
      exclude:
            - key: my_tag
              value: A
    - key: "my_tag"
      value: Z
      exclude:
            - key: my_tag
              value: A
```
