### DISCUSSION TITLE
Setting environment variables from k8s secrets using `env.valueFrom.secretKeyRef`?

### DISCUSSION THREAD

**Discussion by cbini** [dagster-io/dagster#19204] [Q&A] [answered]
Is it possible to define environment variables in `dagster_cloud.yaml` using the method detailed here? https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#define-a-container-environment-variable-with-data-from-a-single-secret

I've been using `container_context.k8s.env_secrets` which loads the key/values within the secret directly as env vars, but I'd like to explicitly set the variable name and map it to a specific secret value. 

I'm trying to take advantage of 1Password's k8s secret automation, but that creates a secret per item with the field names as the keys, which would create conflicts.

**Comment by gibsondan** [comment, marked as answer]
You can use the `server_k8s_config` and `run_k8s_config` fields to apply any raw k8s configuration you want to servers or runs or both. The example from that doc could look like this:

```
container_context:
  k8s:
    server_k8s_config:
      container_config:
        env:
          - name: SECRET_USERNAME
            valueFrom:
              secretKeyRef:
                name: backend-user
                key: backend-username
    run_k8s_config:
      container_config:
        env:
          - name: SECRET_USERNAME
            valueFrom:
              secretKeyRef:
                name: backend-user
                key: backend-username
```
