### DISCUSSION TITLE
limit concurrent k8s_pipes_client pods

### DISCUSSION THREAD

**Discussion by ahoneycutt** [dagster-io/dagster#19235] [Q&A] [answered]
Is there a configuration option when using `k8s_pipes_client` to limit the number of pods launched by a dynamic fan-out?

Currently I am chunking some heavy compute into groups of 100 for testing. I can imagine in the production environment, chunks of 100 will overwhelm the cluster (could yield 1000 pods for the compute). Is there a built-in method to limit the scaling of pod launching when using `k8s_pipes_client`?

**Comment by alangenfeld** [comment]
https://docs.dagster.io/guides/limiting-concurrency-in-data-pipelines#limiting-concurrency-in-data-pipelines

edit: the tagged based concurrency is the more fine grained tool, but `max_concurrent` may be sufficient if thats all thats happening in the job

**Comment by ahoneycutt** [comment]
Hey @alangenfeld thanks for the reply. I only need to limit scaling on the one op, so I followed the documentation and found a feature called `tag_concurrency_limits`. I may have set it up incorrectly, I'm not certain. I added in my `dagster.yaml`

```yaml
    run_coordinator:
      module: dagster.core.run_coordinator
      class: QueuedRunCoordinator
      config:
        ...
        tag_concurrency_limits:
          - key: "parallel"
            value: "my_parallel_op"
            limit: 1
```
I limited to `1` for local testing in minikube.

Then, I added to the op in question:
```python
@op(tags={"parallel": "my_parallel_op"})
def my_k8s_pipe_op(...):
  ...
```

After adding the above, my parallel op still executes as many pods as the cluster allows. Any advice on what I'm doing wrong here?

Thanks much
