### DISCUSSION TITLE
Using run_retries in Hybrid Cloud deployment

### DISCUSSION THREAD

**Discussion by DennisSchwartz** [dagster-io/dagster#19303] [Q&A] [answered]
Hi all!

I have a Hybrid Cloud deployment set up using a K8s agent to run our workloads. Because we use an autoscaling cluster (GKE Autopilot) sometimes runs get killed for resource reasons while more nodes are spun up.

There is probably some tweaking of configurations I can do to solve it properly, but in the meantime I was hoping to just use the [run_retries](https://docs.dagster.io/deployment/run-retries) setting to just retry at least once.

I have added this to my `dagster_cloud.yaml` file but it is causing `Invalid dagster_cloud.yaml` errors during deployment, both when adding it to the top level and within a location definition.

I don't have a `dagster.yaml` file.

Any tips on how to get this running? Any help is appreciated.

I will post my full `dagster_could.yaml` file below.

```yaml
locations:
  - location_name: Main
    code_source:
      module_name: data.assets
    working_directory: ./src/
    build:
      directory: ./
      registry: <registry_link>
    container_context:
      k8s:
        run_k8s_config: # Raw kubernetes config for runs launched by the agent
          container_config:
            resources:
              requests:
                cpu: 500m
                memory: 4G
                ephemeral-storage: 10G
              limits:
                cpu: 1
                memory: 8G
```
