### DISCUSSION TITLE
What's the recommended path for modifying the dagster core database schema?

### DISCUSSION THREAD

**Discussion by kirkhansen** [dagster-io/dagster#19493] [Q&A] [answered]
As an example, if we use dagster's [EventRecordsFilter](https://docs.dagster.io/_apidocs/internals#dagster.EventRecordsFilter) to pull events between two timestamps, we'll end up with heavy IO load due to a lacking index on the timestamp column.

See #19390 for the use case driving the Q&A.

**Comment by kirkhansen** [comment, marked as answer]
We're currently running a `create index if not exists` against the database directly.  See below for a minimal example applying the index to a postgres backed dagster via a k8s job.

```yaml
apiVersion: batch/v1
kind: Job
spec:
  template:
    metadata:
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: check-db-ready
          envFrom:
            - configMapRef:
                name: dagster-daemon-env
          image: public.ecr.aws/docker/library/postgres:9.6.21
          imagePullPolicy: "IfNotPresent"
          command: ['sh', '-c', 'until pg_isready -h ${DAGSTER_K8S_POSTGRES_HOSTNAME} -p 5432 -U ${DAGSTER_K8S_POSTGRES_USERNAME}; do echo waiting for database; sleep 2; done;']
      containers:
        - name: create-events-by-timestamp-index
          envFrom:
            - configMapRef:
                name: dagster-daemon-env
          image: public.ecr.aws/docker/library/postgres:9.6.21
          imagePullPolicy: "IfNotPresent"
          command: ['sh', '-c', 'psql -h ${DAGSTER_K8S_POSTGRES_HOSTNAME} -p 5432 -U ${DAGSTER_K8S_POSTGRES_USERNAME} -c "CREATE INDEX IF NOT EXISTS idx_events_by_timestamp ON public.event_logs USING btree (dagster_event_type, timestamp, id)"']
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: <a secret somewhere>
                  key: <key of the secret>
```
