### DISCUSSION TITLE
is there a complete example of an off-cluster kubernetes configuration for K8sRunLauncher?

### DISCUSSION THREAD

**Discussion by mr-f00** [dagster-io/dagster#19584] [Q&A]
Can someone point me to a working example of `dagster.yaml` and at least one asset or job definition which invokes the `K8sRunLauncher` from an off cluster dagster instance using a kube config file? 

In my scenario, I'm running dagster but not using Helm. My local environment has full access to a k8 cluster with a working kube config file. However, I'm struggling to have a basic "hello world" example of materializing assets or running a basic job in K8. 

The [config schema](https://docs.dagster.io/_apidocs/libraries/dagster-k8s#kubernetes-dagster-k8s) for `dagster-k8s` hints that a kube config file is possible.

**Comment by mr-f00** [comment]
After some trial and error, the following `dagster.yaml` will result in pods being created for a job on the K8 cluster however they are still failing w/ an obscure error. First the `dagster.yaml`:
```
run_launcher:
  module: dagster_k8s.launcher
  class: K8sRunLauncher
  config:
    load_incluster_config: false
    kubeconfig_file: /users/user/.kube/config
    job_image: dagster/user-code-example:latest
    instance_config_map: dagster-instance
    service_account_name: default
telemetry:
  enabled: false
sensors:
  use_threads: true
  num_workers: 4
schedules:
  use_threads: true
  num_workers: 4
```

I'm attempting to run a toy example of asset materialization with an asset such as:
```
@dagster.asset
def random_ints() -> list[int]:
    scale_factor = 100
    n_values = 10
    return [int(scale_factor * random.random()) for _ in range(n_values)]
```

The pod is scheduled but fails almost immediately with the following log (obtained by `kubectl logs <podname>`):
```
...
dagster._check.CheckError: Expected non-None value: Run with id 'bc394948-f3b3-4ed0-b994-61c721bd95db' not found for run execution.
```

What's worse, the run in dagster is simply in the "Starting" state and shows no kind of error and no logs from the failed pod. It is as though the pod lifecycle is completely divorce from the run in dagster. I don't understand how a pod can fail to run and the originating run stays stuck in "Starting".
