### DISCUSSION TITLE
How to identify asset keys for dbt source names

### DISCUSSION THREAD

**Discussion by ya7010** [dagster-io/dagster#19732] [Q&A] [answered]
I am trying to create a source asset that will add records to the snowflake external table, but I still don't know how to handle updates to the snowflake external table in dagster.

```python
from dagster import AssetExecutionContext, asset
from dagster_dbt import DbtCliResource, dbt_assets, get_asset_key_for_source

from my_dagster.constants import DBT_MANIFEST_PATH


@dbt_assets(manifest=DBT_MANIFEST_PATH)
def my_dbt_assets(context: AssetExecutionContext, dbt: DbtCliResource):
    yield from dbt.cli(["build"], context=context).stream()


@asset(
    key=get_asset_key_for_source(
        [my_dbt_assets], "MY_SNOWFLAKE_EXTERNAL_TABLE"
        # <-- KeyError: 'Could not find a dbt source with name: MY_SNOWFLAKE_EXTERNAL_TABLE'
    )
)
def my_snowflake_external_table(context: AssetExecutionContext):
    # upload_to_gcs(data)
    ...
```

Is there a way to identify the asset key for a specific dbt source?

`get_asset_key_for_soruce` searches for `sources[...].name` in `manifest.json`.
However, from what I have found, `source_name` contains the name of the schema or database, so it does not identify a specific source.

On the other hand, `get_asset_key_for_model` searches for `nodes[...] .name` in `manifest.json`, which can be identified by the model name.

Since source, unlike model, does not have a unique name in dbt, it seems that we need to use the concatenation of schema and table names as asset names.

If I want to handle the update flow of an external table on dagster, what is the best way to proceed?

**Comment by ya7010** [comment]
Regarding the handling of external tables, I found that I can write as follows

```python
@asset(compute_kind="python")
def my_snowflake_external_table(context: AssetExecutionContext):
    ...
```

And dbt schema.yml

```yaml
sources:
  - name: DATALAKE
    tables:
      - name: my_snowflake_external_table
        meta:
          dagster:
            asset_key: ['my_snowflake_external_table']
```

However, there is still a question.

`get_asset_key_for_source` is not getting a unique asset key because it goes to get the `source_name` in `manifest.json`.

The `source_name` is assigned the name of the schema ( or the database), not the table name, so it is giving an error retrieving multiple asset keys.

**Comment by rexledesma** [comment, marked as answer]
The instructions for defining an upstream dependency to your dbt models are here: https://docs.dagster.io/integrations/dbt/reference#upstream-dependencies.

You should be passing the dbt source name to [`get_asset_key_for_source`](https://docs.dagster.io/_apidocs/libraries/dagster-dbt#dagster_dbt.get_asset_key_for_source). Let's examine the `schema.yml` that you provided:

```yaml
sources:
  - name: DATALAKE
    tables:
      - name: my_snowflake_external_table
        meta:
          dagster:
            asset_key: ['my_snowflake_external_table']
```

The source name is `DATALAKE` and the source table name is `my_snowflake_external_table`.

When you use `get_asset_key_for_source`, you should use `DATALAKE`. 

```diff
get_asset_key_for_source(
    [my_dbt_assets],
-   "MY_SNOWFLAKE_EXTERNAL_TABLE"
+   "DATALAKE" 
)
```

If your source has multiple tables associated with it, then you should use [`get_asset_keys_by_output_name_for_source`](https://docs.dagster.io/_apidocs/libraries/dagster-dbt#dagster_dbt.get_asset_keys_by_output_name_for_source) instead.
