### DISCUSSION TITLE
Job Concurrency - When running, block all others. How?

### DISCUSSION THREAD

**Discussion by dinis-rodrigues** [dagster-io/dagster#20061] [Q&A] [answered]
All my jobs have a unique tag `{“single_run_per_job”: <job_name>}` which prevents the same job from running more than once concurrently. In my `dagster.yaml`

```yaml
tag_concurrency_limits:
      - key: single_run_per_job
        value:
          applyLimitPerUniqueValue: True
        limit: 1
```

What I would like to achieve is having a job that if it is running, no other job can be running as well.
Is this possible to achieve?

For example, I would like to have a job that performs optimize and vacuum to my tables, and I don't any other job running at the same time.
