### DISCUSSION TITLE
Make dbt auto-materialize policy rules configurable

### DISCUSSION THREAD

**Discussion by darijavz** [dagster-io/dagster#20231] [Q&A] [answered]
Hi, is there a way to add an auto-materialize rules for dbt models in meta config? I would like something like that:
```
models:
  my_models:
    marts:
      +meta:
          dagster:
            auto_materialize_policy:
              type: eager
              skip_on_all_parents_not_updated:
                require_update_for_all_parent_partitions: False
```
However, as I understand currently it is only possible to configure `skip_on_all_parents_not_updated` rules using `DagsterDbtTranslator` for all assets, which is not desired in my case. Any help is appreciated.
