### DISCUSSION TITLE
How to supply environment variables for mapping the docker container host directory to the Docker Run Launcher

### DISCUSSION THREAD

**Discussion by pbower** [dagster-io/dagster#20571] [Q&A]
Hey everybody,

I'm wondering if anyone knows how to supply environment variables to the Docker container run launcher?

The following doesn't work:
********************************************
DAGSTER.YAML - Cannot supply env variables for launched container jobsrun_launcher:

```yaml
  module: dagster_docker
  class: DockerRunLauncher
  config:
    env_vars:
      - REPO_BASE_DIR
      - MY_ENV2
    network: dagster-network
    container_kwargs:
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /tmp/io_manager_storage:/tmp/io_manager_storage
        - ${REPO_BASE_DIR}/python/:/opt/dagster/app/
        - ${REPO_BASE_DIR}/python/:/opt/dagster/dagster_home
```

********************************************
So then I've built a python module to do this type of thing:
********************************************
CUSTOM RUN LAUNCHER.py:

```python
import os
from dagster_docker import DockerRunLauncherREPO_BASE_DIR = os.getenv('REPO_BASE_DIR')if not REPO_BASE_DIR:
    raise EnvironmentError("REPO_BASE_DIR environment variable is not set.")volumes = [
    '/var/run/docker.sock:/var/run/docker.sock',
    '/tmp/io_manager_storage:/tmp/io_manager_storage',
    f'{REPO_BASE_DIR}/python/:/opt/dagster/app/',
    f'{REPO_BASE_DIR}/python/:/opt/dagster/dagster_home',
]docker_run_launcher = DockerRunLauncher(
    env_vars=[
      'REPO_BASE_DIR',
      'ENV_VAR_2,
    ],
    network='dagster-network',
    container_kwargs={
        'volumes': volumes,
    }
)
```

********************************************

How does one then apply that configuration (if this is the easiest way to do it?) to ensure ops and assets launch containers with the correct mapping?

I looked in the "Definitions' object (and documentation) and couldn't see anything for this.

Thanks heaps for your help
