### DISCUSSION TITLE
Dagster run pod image pull backoff

### DISCUSSION THREAD

**Discussion by darwyncook** [dagster-io/dagster#20927] [Q&A]
We are running dagster 1.6.13 instance managed via a helm umbrella chart, with user deployments managed via different umbrella charts in different repositories. All of these are managed using ArgoCD.

We are working on our first dagster project in this environment. The project deploys fine and shows up as loaded in the dagster UI. When we try to materialize the first asset it fails, looking at the namespace there is a dagster-run pod that is experiencing an ImagePullBackoff.

Using kubectl describe pod, it looks like the correct image pull secret (which works fine for the initial deployment of the project) is being sent as an Arg to the dagster-run pod. 

Additional info: 
For the dagster deployment, here is the part of our values file for the user deployments. The top level dagster: is for the umbrella chart.
```
dagster:
  generateCeleryConfigSecret: true
  # Need to get sealed secrets working, until then:
  generatePostgresqlPasswordSecret: true
  dagster-user-deployments:
    enabled: true
    enableSubchart: false
  global:
    postgresqlSecretName: "dagster-prod-postgresql"
    celeryConfigSecretName: "dagster-celery-config-secret-prod"
  dagsterWebserver:
    deploymentLabels:
      environment: prod
    labels:
      environment: prod
    workspace:
      enabled: true
      servers:
      - host: "k8s-example-user-code-1"
        port: 3030
      - host: "gitlab-repo-introspection-tool" # should be the same as the deployments name
        port: 3050
  ```
  And the values file for the user deployment gitlab-repo-introspection-tool
  ```
 dagster-user-deployments:
  # Specify secrets to run containers based on images in private registries. See:
  # https://kubernetes.io/docs/concepts/containers/images/#referring-to-an-imagepullsecrets-on-a-pod

  global:
    postgresqlSecretName: "dagster-prod-postgresql"
    celeryConfigSecretName: "dagster-celery-config-secret-prod"
    #  dagsterHome: ""
    #  serviceAccountName: ""
  ####################################################################################################
  # User Code Deployments: Configuration for user code containers to be loaded via GRPC server. For
  # each item in the "deployments" list, a K8s Deployment and K8s Service will be created to run the
  # GRPC server that Dagster communicates with to get repository information and the current
  # image information. These deployments can be updated independently of the webserver, and Dagster
  # will pull the current image for all execution. When using a distributed executor (such as
  # Celery-K8s) for pipeline run, the current image will be queried once and used for all
  # solid executions for that pipeline run. In order to guarantee that all solid executions within a
  # pipeline execution use the same image, we recommend using a unique tag (ie not "latest").
  #
  # All user code will be invoked within the images.
  ####################################################################################################
  deployments:
    - name: "gitlab-repo-introspection-tool"
      image:         
        repository: "gitlab.toolchain.corning.com:5050/scicomp/scke/deployed-projects/corning-models-infrastructure/repo-introspection-tool"
        tag: latest
        pullPolicy: Always
      # Arguments to `dagster api grpc`.
      # Ex: "dagster api grpc -m dagster_test.test_project.test_jobs.repo -a define_demo_execution_repo"
      # would translate to:
      # dagsterApiGrpcArgs:
      #   - "-m"
      #   - "dagster_test.test_project.test_jobs.repo"
      #   - "-a"
      #   - "define_demo_execution_repo"
      # The `dagsterApiGrpcArgs` key can also be replaced with `codeServerArgs` to use a new
      # experimental `dagster code-server start` command instead of `dagster api grpc`, which takes
      # identical arguments but can reload its definitions from within the Dagster UI without
      # needing to restart the user code deployment pod.
      dagsterApiGrpcArgs:
        - "--python-file"
        - "/opt/repo_introspection/gitlab_data/__init__.py" # This is where the definitions are
      port: 3050
  
      # Whether or not to include configuration specified for this user code deployment in the pods
      # launched for runs from that deployment
      includeConfigInLaunchedRuns:
        enabled: true
  
      # Readiness probe detects when the pod is ready to serve requests.
      # https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes
      readinessProbe:
        # Readiness probes are enabled by default.
        enabled: true
        # If `readinessProbe` has no `exec` field, then the following default will be used:
        # exec:
        #   command: ["dagster", "api", "grpc-health-check", "-p", "{{ $deployment.port }}"]
        periodSeconds: 20
        timeoutSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      env: 
        # This token is for the assets, which read repos from gitlab. Not a deploy token
        - name: GITLAB_REPO_TOKEN
          valueFrom:
            secretKeyRef:
              name: toolchain-gitlab-token
              key: GITLAB_REPO_TOKEN   
  imagePullSecrets: 
    - name: gitlab-pull-secret-repo-introspection
  ```
