### DISCUSSION TITLE
Dagster daemon and webserver stuck in init state

### DISCUSSION THREAD

**Discussion by wilson-zhang-sndk** [dagster-io/dagster#21243] [Q&A]
Hello,
I have configured a dagster daemon, webserver, and 7 user deployments using the provided values.yaml. Once i helm install the dagster chart, I do see all 7 user deployments pods start and are running correctly. 
However, the daemon and webserver pods both start but they are stuck at status: Init: 1/8. The reason why they're stuck there is because the init container is not able to find the service for the user deployment so its repeatedly checking for the service.

Kubernetes logs for the init container show:
```

** server can't find user-deployment.cluster.local: NXDOMAIN

** server can't find user-deployment.svc.cluster.local: NXDOMAIN

** server can't find user-deployment.cluster.local: NXDOMAIN

** server can't find user-deployment.cluster.local: NXDOMAIN

waiting for user service

```

Below is a values.yaml snippet for one of the user deployments. I have replaced the repository location in dagster-user-deployments.deployments.image with *** :
```
dagster-user-deployments:
  # Creates a workspace file with the gRPC servers hosting your user code.
  enabled: true

  # If you plan on deploying user code in a separate Helm release, set this to false.
  enableSubchart: true

  # Specify secrets to run user code server containers based on images in private registries. See:
  # https://kubernetes.io/docs/concepts/containers/images/#referring-to-an-imagepullsecrets-on-a-pod
  imagePullSecrets: []

  # List of unique deployments
  deployments:
    - name: "user-deployment"
      image:
        # When a tag is not supplied, it will default as the Helm chart version.
        repository: ***
        tag: latest

        # Change with caution! If you're using a fixed tag for pipeline run images, changing the
        # image pull policy to anything other than "Always" will use a cached/stale image, which is
        # almost certainly not what you want.
        pullPolicy: Always

      # Arguments to `dagster api grpc`.
      # Ex: "dagster api grpc -m dagster_test.test_project.test_jobs.repo -a define_demo_execution_repo"
      # would translate to:
      # dagsterApiGrpcArgs:
      #   - "-m"
      #   - "dagster_test.test_project.test_jobs.repo"
      #   - "-a"
      #   - "define_demo_execution_repo"
      #
      # The `dagsterApiGrpcArgs` key can also be replaced with `codeServerArgs` to use a new
      # experimental `dagster code-server start` command instead of `dagster api grpc`, which takes
      # identical arguments but can reload its definitions from within the Dagster UI without
      # needing to restart the user code deployment pod.
      dagsterApiGrpcArgs:
        - "--python-file"
        - "/app/repo.py"
      port: 3030

      # Whether or not to include configuration specified for this user code deployment in the pods
      # launched for runs from that deployment
      includeConfigInLaunchedRuns:
        enabled: true

      # Additional environment variables to set.
      # These will be directly applied to the daemon container. See
      # https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/
      #
      # Example:
      #
      # env:
      # - name: ENV_ONE
      #   value: "one"
      # - name: ENV_TWO
      #   value: "two"
      env: 
        - name: config
          value: /app/config.ini

      # Readiness probe detects when the pod is ready to serve requests.
      # https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes
      readinessProbe:
        # Readiness probes are enabled by default.
        enabled: false
        # If `readinessProbe` has no `exec` field, then the following default will be used:
        # exec:
        #   command: ["dagster", "api", "grpc-health-check", "-p", "{{ $deployment.port }}"]
        periodSeconds: 20
        timeoutSeconds: 10
        successThreshold: 1
        # Allow roughly 300 seconds to start up by default
        failureThreshold: 1

      resources:
        limits:
          cpu: 200m
          memory: 512Mi
        requests:
          cpu: 200m
          memory: 512Mi 
```
How can I start the services for the 7 user deployments?

Thanks alot
