### DISCUSSION TITLE
Request for input: Config-based pipelines

### DISCUSSION THREAD

**Discussion by sryza** [dagster-io/dagster#21498] [Ideas]
## Motivation

YAML. A very polarizing topic in the data community. Many hate it. Many more use it.

Many data organizations define parts of their data pipelines in configuration languages like YAML. Configuration languages like YAML are particularly useful for:

- Users who aren’t familiar with Python, e.g. analysts or frontend engineers who sometimes need to contribute to data pipelines but don’t have it as a primary responsibility.
- Tasks that can & should be heavily standardized within an organization, e.g. moving a file of a certain type from one storage system to another, or refreshing a Databricks notebook.

We've observed that many organizations build layers on top of Dagster that consume YAML. We’re trying to determine whether – and how – to make these uses more first class in Dagster, and to help users avoid reinventing the wheel every time they want to implement them.

## What this could look like

What might this look like on top of Dagster? Some basic requirements:

- Customizable - data platform engineers need to be able to determine what fields their stakeholders can set and what level of abstraction to expose them to.
- Escapable - a YAML layer can’t be as expressive as a Turing-complete language, so users need to be able to punch through to Python when they have advanced needs.
- Approachable - to be useful, needs to provide an out of the box experience that allows a user with basic needs to get the job done without complex Python scaffolding.

A high-level sketch:

- A new `dagster-yaml` library includes a `load_defs_from_yaml` function, which reads a directory of YAML files and uses their contents to generate a Dagster `Definitions` object.
- `load_defs_from_yaml` accepts a list of plugins, which specify YAML interfaces for building Dagster definitions.
- Some Dagster integration libraries, like `dagster-dbt` and `dagster-shell`, expose built-in plugins. Users can also define their own plugins.

### Example

definitions.py

```python
from dagster_yaml import load_defs_from_yaml
from dagster_dbt import dbt_yaml_plugin
from dagster_shell import shell_yaml_plugin

defs = load_defs_from_yaml(base_dir=".", plugins=[dbt_yaml_plugin, shell_yaml_plugin])
```

definitions.py (alternative with both YAML defs and Python defs)
```python
from dagster import Definitions
from dagster_yaml import load_defs_from_yaml
from dagster_dbt import dbt_yaml_plugin
from dagster_shell import shell_yaml_plugin

defs_from_yaml = load_defs_from_yaml(base_dir=".", plugins=[dbt_yaml_plugin, shell_yaml_plugin])
defs_from_python = Definitions(...)
defs = defs_from_yaml + defs_from_python
```

my_analytics_defs.yaml:

```yaml
defs:
  - type: dbt
    name: cloud_analytics_dbt_assets
    dbt_project_dir: "analytics_dbt/"
    exclude: "+tag:insights,config.materialized:incremental"
```

my_recommender_model_defs.yaml:

```yaml
assets:
  - type: shell
    key: recommender_model
    shell_command: "./train_recommender_model.sh"
  - type: python
    key: recommender_model_eval
    module_path: my_org.evaluate_recommender_model
```

## Let us know what you think

As usual, we would love your feedback. Do you write your own definition factories using YAML? What kinds of tasks do you use it for? What kinds of difficulties do you face? What functionality would you find useful?
