### DISCUSSION TITLE
Default grouping for dbt sources

### DISCUSSION THREAD

**Discussion by fredonia88** [dagster-io/dagster#21626] [Q&A] [answered]
I upgraded to dagster==1.7.3 and dagster-dbt==0.23.3 and am now seeing my dbt sources grouped under the default asset group in the UI. The version I was on previously, dagster==1.5.13 and dagster-dbt==0.21.13, did not show my sources in the asset group section. I've tried adding necessary meta tags to the nodes themselves in the sources.yml file and to the dbt_project.yml file to group them, but its not working. How do I group my dbt sources so they aren't grouped under default? I'm using dbt-core==1.7.13. The dagster meta key does group my models correctly, but not my sources.

Here's a snippet of my dbt_project.yml file: 
```
sources:
  some_dbt_project:
    +meta:
      dagster:
        group: sources
```

Here's a snippet a sources.yml file:
```
sources:
  - name: some_source
    description: Some source data.
    database: some_db
    schema: some_schema
    tables:
      - name: some_table_name
        config:
          meta:
            dagster:
              group: sources
```

After the above changes, sources still group under default: 
<img width="327" alt="Screenshot 2024-05-03 at 8 58 56 AM" src="https://github.com/dagster-io/dagster/assets/14169734/9f53373a-9fc5-4eaa-9f22-a45bfe324a8d">
