### DISCUSSION TITLE
Dagster suddenly cannot communicate with Docker to launch run containers

### DISCUSSION THREAD

**Discussion by clayheaton** [dagster-io/dagster#21987] [Community]
I've been running self-hosted Dagster with Docker Compose and 5 code locations for over a year without any problems, updating regularly. This is on Ubuntu 22.04.

Today, out of the blue, Dagster no longer can communicate with Docker to launch containers. This is the error:

`docker.errors.DockerException: Error while fetching server API version: Not supported URL scheme http+docker`

![Screenshot 2024-05-20 at 5 46 17 PM](https://github.com/dagster-io/dagster/assets/205364/8efc33d6-fdb4-49a3-bce4-3b20849a44b0)
![Screenshot 2024-05-20 at 5 46 28 PM](https://github.com/dagster-io/dagster/assets/205364/b8872b5d-3124-46e9-bc45-2cd9722d8ebe)

This is how I have my run launcher configured. I have not touched this in over a year:

```yaml
run_launcher:
  module: dagster_docker
  class: DockerRunLauncher
  config:
    network: dagster_docker_network
    container_kwargs:
      volumes: # Make docker client accessible to any launched containers as well
        - /var/run/docker.sock:/var/run/docker.sock
```

If I just ssh to the VM where Dagster is running, I can do this in a python repl:

```python
import docker
client = docker.from_env()
```

However, if I `docker exec -it dagster_daemon bash` into the `dagster_daemon` container, trying the same code leads to the error shown above. The dagster_daemon is defined like this in my docker compose file:

```yaml
  dagster_daemon:
    env_file:
      - ${PWD}/.env
    build:
      context: .
      dockerfile: ./Dockerfile_dagster
    entrypoint:
      - dagster-daemon
      - run
    container_name: dagster_daemon
    profiles: ["nondata", "all"]
    restart: on-failure
    environment:
      DAGSTER_POSTGRES_URL: ${DAGSTER_POSTGRES_CONN_STRING}
    volumes: # Make docker client accessible so we can launch containers using host docker
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
    networks:
      - dagster_docker_network
    depends_on:
      - code_loc1
      - code_loc2
```

Any ideas? I have no idea why this suddenly stopped working. I've rebooted the VM, upgraded docker, etc... but none of it is enabling the dagster run launcher to communicate with docker...
