### DISCUSSION TITLE
How to handle and materialize dbt sources

### DISCUSSION THREAD

**Discussion by thmswt** [dagster-io/dagster#22499] [Q&A] [answered]
### Overview

Dagster currently handles dbt sources as external assets, but there are scenarios where treating them as materializable assets can provide advantages. Specifically, dbt sources can be materialized using the [dbt-external-tables](https://github.com/dbt-labs/dbt-external-tables) package to create external tables (e.g., in BigQuery). This discussion should help finding potential advantages and disadvantages of the proposed solution.

### Key Points

1. **Materializable Assets for dbt Sources**
    - dbt sources should have the option to be handled as materializable assets, not just external assets.
    - The `dbt-external-tables` package allows the creation of dbt sources as external tables, such as in BigQuery:  `dbt run-operation stage_external_sources`
    
    This could resolve the following discussion:
    
    - https://github.com/dagster-io/dagster/discussions/21457
2. **Loading Descriptions and Metadata for dbt Source Assets**
    - dbt sources, when loaded as “normal” assets, should be able to load descriptions and metadata similar to assets based on dbt models.
    - This will ensure consistency and completeness of metadata across all dbt assets in Dagster.
    
    This could resolve the following discussion:
    
    - https://github.com/dagster-io/dagster/discussions/16470
3. **Mapping Upstream Dependencies for dbt Source Assets**
    - A new dbt [asset definition attribute](https://docs.dagster.io/integrations/dbt/reference#understanding-asset-definition-attributes) can be implemented to map upstream dependencies to the asset that stores the raw files in an object storage (e.g., Parquet files in Google Cloud Storage).
    - **Example Attribute:** Using the dbt [meta config](https://docs.getdbt.com/reference/resource-configs/meta) to add a dagster key, e.g. `deps`.
    
    This could resolve the following discussion:
    
    - https://github.com/dagster-io/dagster/discussions/21077

### Example Configuration

Here's an example YAML configuration for a dbt source handled as a materializable asset with upstream dependency mapping:

```yaml
---

version: 2

sources:
  - name: example_bq_dataset
    tables:
      - name: src__table
        description: "External Delta Lake table stored as Parquet files in Google Cloud Storage"
        external:
          location: gs://bucket/delta-lake-table
          options:
            format: DELTA_LAKE
        meta:
          dagster:
            asset_key: ["gcp-project","example_bq_dataset","src__table"]
            group: "dbt_source"
            deps: ["gcp-project","bucket","delta-lake-table"]  # references the upstream asset that creates the delta lake table

```

Here’s an example Dagster implementation for a dbt source executing the `dbt.cli` method with `run-operation stage_external_sources` as input.

```yaml
@dbt_assets(
    manifest=manifest,
    select=DBT_SELECT_SOURCE,
    dagster_dbt_translator=CustomDbtTranslator(),
)
def dbt_source_assets(context: OpExecutionContext):
    yield from DBT.cli(["run-operation", "stage_external_sources"], manifest=manifest, context=context).stream()
```

### Conclusion

Is this approach viable and aligns with the core concepts of Dagster and dbt integration?

I appreciate any feedback on this matter.

P.S. if a contribution is welcomed, I can help there as well.
