### DISCUSSION TITLE
Change `Code location` name

### DISCUSSION THREAD

**Discussion by kennycontreras** [dagster-io/dagster#24494] [Q&A] [answered]
Hello Dagster community 👋 

I'd like to ask, I hope, a simple question.

I have a setup loading two `code locations`, and I'd like to know if there's a way to modify the `code location` name for something simpler than what I have by default (see screenshot attached).

Currently, the only option that helps me identify each code location is the attribute key in my workspace.yaml
I'd like to avoid having the `definitions.py:batch` and instead only `batch` , so, getting rid of the file name.

Thanks. 

![Screenshot 2024-09-15 at 05 42 17](https://github.com/user-attachments/assets/3f546619-77c9-4d13-989d-d1fd28621aef)

**Comment by garethbrickman** [comment]
Hey Kenny, could you please share your current `workspace.yaml` file?

**Reply by kennycontreras** [reply]
My `workspace.yaml` is the following:

```
load_from:
  - python_file:
      relative_path: "definitions.py"
      attribute: "batch"
  - python_file:
      relative_path: "definitions.py"
      attribute: "streaming"
```

**Comment by nixent** [comment, marked as answer]
Just set `location_name` parameter:
```yaml
load_from:
  - python_file:
      relative_path: "definitions.py"
      attribute: "batch"
      location_name: batch
  - python_file:
      relative_path: "definitions.py"
      attribute: "streaming"
      location_name: streaming
```
