### DISCUSSION TITLE
Help with AWS ECS Deployment

### DISCUSSION THREAD

**Discussion by Nirosh-cartrabbit** [dagster-io/dagster#25706] [Q&A]
Hii I'm trying to deploy my Dagster project to ECS but when i trying to deploy them in the cluster as service my tasks is not running it just draining every time. My task definition consists of the three container like told in docs, when i create my service and add my task to it my Dagster dosen't seems to get up and running.

my dagster yaml file is 
```
storage:
  postgres:
    postgres_url:
      env: DAGSTER_POSTGRES_DB

telemetry:
  enabled: false

run_monitoring:
  enabled: true
  start_timeout_seconds: 180
  cancel_timeout_seconds: 180
  poll_interval_seconds: 120
  free_slots_after_run_end_seconds: 2

run_retries:
  enabled: true
  max_retries: 5
  retry_on_asset_or_op_failure: true

compute_logs:
  module: dagster_aws.s3.compute_log_manager
  class: S3ComputeLogManager
  config:
    bucket: beta-tasks-dev
    region: us-east-2
```
    
Do i need to have launcher type as ecs ah. how does that work can any one explain and help me with this ?

**Comment by garethbrickman** [comment]
Could you link to the doc you are using for reference?

**Reply by Nirosh-cartrabbit** [reply]
This is the docs im referring to https://docs.dagster.io/deployment/guides/aws

my doubt is mainly do i really need to change my run launcher to ECS ah
```

run_launcher:
  module: "dagster_aws.ecs"
  class: "EcsRunLauncher"
  config:
    task_definition: "arn:aws:ecs:us-east-2:2323:task-definition/tasksdev:19"
    container_name: "betatask-grpc"
  run_resources:
    cpu: "256"
    memory: "512" # In MiB
    ephemeral_storage: 20 # In GiB
```
    
    
or can i use deafult run launcher ah ?
