### DISCUSSION TITLE
Are credentials sent with Python HTTPHandler handler?

### DISCUSSION THREAD

**Discussion by ChrisChinchilla** [dagster-io/dagster#25978] [Q&A]
I am trying to send Dagster logs to an external logging sevrice via HTTP, so I use the Python HTTPHandler logging Handler, which I think Dagster supports. And if I remove any authentication, then I receive an unauthorized error.

This is my Dagster YAML config, everything is running in Kubernetes:

```
pythonLogs:
  pythonLogLevel: DEBUG
  dagsterHandlerConfig:
    handlers:
      parseable:
        class: logging.handlers.HTTPHandler
        host: parseable.parseable.svc.cluster.local:8000
        url: api/v1/logstream/dagster
        method: POST
        credentials: admin,admin
        secure: False
```

I have tried enabling and disabling `secure`, and I have tried every possible formatting of `credentials` I can think of… CSV, CSV with quotes, CSV in brackets, YAML object, YAML array, and on the ones that don't give a YAML error, I get the following error on a Dgaster run:

```
File "/usr/local/lib/python3.10/logging/handlers.py", line 1266, in emit
s = ('%s:%s' % self.credentials).encode('utf-8')
TypeError: not enough arguments for format string
```

Any idea? Is there a formatting I've missed, or is Dagster not sending the credentials correctly?
