### DISCUSSION TITLE
Concurrency documentation

### DISCUSSION THREAD

**Discussion by medihack** [dagster-io/dagster#27440] [Q&A] [answered]
Hello!

The documentation is quite unclear about the difference between
```
run_queue:
  max_concurrent_runs: 15
```
and this one
```
run_coordinator:
  module: dagster.core.run_coordinator
  class: QueuedRunCoordinator
  config:
    max_concurrent_runs: 15
```
Does it do the same thing? Do I have to specify both?

The [concurrency documentation](https://docs.dagster.io/guides/operate/managing-concurrency) also does not state whether the `QueuedRunCoordinator` is still necessary for concurrency when only using the `max_concurrent_runs` of `run_queue` (I guess so, as the `DefaultRunCoordinator` is not capable of running assets in parallel).
