### DISCUSSION TITLE
How to add private Python packages to a Dagster cloud deployment?

### DISCUSSION THREAD

**Discussion by C-Roensholt** [dagster-io/dagster#28753] [Q&A]
I know this is a possible duplicate of #12340, but that discussion seems to be inactive why I am raising this in a separate discussion in the hope to get some help.

I would like to add private Github packages to my dagster+ cloud deployment. I am using fast deploys and have added the build steps mentioned in the discussion above.
The packages are build correctly and are seen when I debug using `pip list`. However, the github action fails in the **Deploy to Dagster+ Serverless** step with the error:
```
3.385 ERROR: Could not find a version that satisfies the requirement private_package (from dagster-pipeline) (from versions: none)
3.385 ERROR: No matching distribution found for private_package
```

The Dagster project lives in a subfolder in a Github repository, e.g. my-github-repo/dagster-pipeline.
This is the Github Action I am trying to for deployment:

```yaml
name: Deploy to Dagster Cloud

on:
  workflow_dispatch:

env:
  DAGSTER_CLOUD_ORGANIZATION: "my-org"
  DAGSTER_CLOUD_API_TOKEN: ${{ secrets.DAGSTER_CLOUD_API_TOKEN }}
  DAGSTER_PROJECT_DIR: "./dagster-pipeline"
  DAGSTER_CLOUD_YAML_PATH: "./dagster-pipeline/dagster_cloud.yaml"
  ENABLE_FAST_DEPLOYS: 'true'

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    # Checkout repos
    # main code
    - name: Checkout main code
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0
        submodules: true  # required for dependencies in private submodules
    
    # Private packages
    # private-package1
    - name: Checkout private-package1 repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PAT }}
        repository: my-github-org/private-package1
        path: deps/private-package1

    # private-package2
    - name: Checkout private-package2 repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PAT }}
        repository: my-github-org/private-package2
        path: deps/private-package2

    # private-package3
    - name: Checkout private-package3 repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PAT }}
        repository: my-github-org/private-package3
        path: deps/private-package3

    # Main setup
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install pip, wheel and build
      run: pip install --upgrade pip wheel build

    # Install private packages
    # private-package1
    - name: Build a wheel for private-package1
      run: >
        cd deps/private-package1 &&
        python setup.py bdist_wheel &&
        mkdir -p $GITHUB_WORKSPACE/deps &&
        cp dist/*whl $GITHUB_WORKSPACE/deps
    
    # private-package2 (build from pyproject.yml)
    - name: Build a wheel for private-package2
      run: >
        cd deps/private-package-sub-folder/private-package2 &&
        python -m build --wheel --outdir $GITHUB_WORKSPACE/deps

    # private-package3 (build from pyproject.yml)
    - name: Build a wheel for private-package3
      run: >
        cd deps/private-package3 &&
        python -m build --wheel --outdir $GITHUB_WORKSPACE/deps

    # Configure private packages build above
    - name: Configure pip to use local wheels
      run: |
        echo "[global]" > $GITHUB_WORKSPACE/deps/pip.conf
        echo "find-links = file://$GITHUB_WORKSPACE/deps/" >> $GITHUB_WORKSPACE/deps/pip.conf
        echo "PIP_CONFIG_FILE=$GITHUB_WORKSPACE/deps/pip.conf" >> $GITHUB_ENV

    - name: Install dependencies
      run: pip install -r $DAGSTER_PROJECT_DIR/requirements.txt

    - name: Debug Pip Installation
      run: pip list

    - name: Deploy to Dagster+ Serverless
      env:
        DAGSTER_CLOUD_API_TOKEN: ${{ secrets.DAGSTER_CLOUD_API_TOKEN }}
        DAGSTER_CLOUD_ORGANIZATION: "my-org"
        DAGSTER_CLOUD_DEPLOYMENT: "prod"

      run: |
        cd dagster-pipeline
        dagster-cloud serverless deploy --location-name dagster-pipeline
```
