### DISCUSSION TITLE
cross-dependencies between two different dbt project on dagster

### DISCUSSION THREAD

**Discussion by NunoTrigo1986** [dagster-io/dagster#29672] [Q&A]
Hi!

I have a Dagster project with dbt assets that depend on source tables from another SQL Server. Since dbt cannot connect to two different servers at the same time, I decided to create two separate dbt projects: one for the source tables (since I don't want to replicate/materialize data on the target server) called "source_dbt_project" and one for the target called "target_dbt_project".

In my source_dbt_project, I have the following source.yaml:

```
ource.yaml from source_dbt_project
version: 2

sources:
  - name: raw_trafikk_app
    database: ff_backoffice
    schema: dbo
    tables:
      - name: table1 
      - name: table2
```

I want to use source table1 and source table2 from source_dbt_project as source tables in my target_dbt_project. Both dbt projects are defined as assets, and all tables appear in the Dagster UI. I read that in Dagster, I could do something like this:

```
asset_keys = get_asset_keys_by_output_name_for_source([source_dbt_project], "raw_trafikk_app")
bilde_key = asset_keys["stg_table1"]
```

Then, I could reference these in the source.yaml of my target_dbt_project like this:

```
sources:
  - name: raw_trafikk_app
    tables:
      - name: stg_table1
```
      
However, this approach is not working for me. Could someone please help me figure out how to properly reference the source tables from one dbt project in another using Dagster? Thank you in advance! If there is a better way to perform this task, please let me know!
