### DISCUSSION TITLE
How can I set pool size in dagster+?

### DISCUSSION THREAD

**Discussion by jarichb** [dagster-io/dagster#30051] [Q&A]
I keep on getting this:
`{"time": "16/May/2025:14:23:42 +0000", "log": "connectionpool - Connection pool is full, discarding connection: serverless-agents-storage.s3.us-west-2.amazonaws.com. Connection pool size: 10", "status": "WARNING", "logger": "urllib3.connectionpool"}`
But my settings on Dagster+ don’t mention anything regarding 10 pool size:
```
run_queue:
  max_concurrent_runs: 50
  tag_concurrency_limits: []
run_monitoring:
  start_timeout_seconds: 1200
  cancel_timeout_seconds: 1200
  free_slots_after_run_end_seconds: 300
run_retries:
  max_retries: 0
  retry_on_asset_or_op_failure: true
sso_default_role: VIEWER
non_isolated_runs:
  max_concurrent_non_isolated_runs: 1
auto_materialize:
  run_tags: {}
  respect_materialization_data_versions: true
  use_sensors: true
concurrency:
  pools:
    default_limit: 1
    granularity: run
  runs:
    max_concurrent_runs: 100
```
Any idea how I might change this? Because I’m reading a lot of json files from ADLS to Snowflake and it consumes only 5% memory and 0% CPU and takes for ever…

I'm using dlthub for this by the way.
