### DISCUSSION TITLE
How to increase the number of concurrent runs?

### DISCUSSION THREAD

**Discussion by nyte-owl** [dagster-io/dagster#30767] [Q&A]
I am attempting to backfill hundreds of partitions across a couple different assets.  Despite hundreds of runs being queued, I am only seeing 3 to 5 runs in progress.  I'd like to increase the number of runs that can execute concurrently.

I am running dagster 1.10.19 locally with `dagster dev -m <module_name_with_defs>`

I've attempted to set the following in my dagster.yaml, to little effect:

```yaml
concurrency:
  runs:
    max_concurrent_runs: 32
    tag_concurrency_limits:
      - key: "dagster/backfill"
        limit: 32
    default_op_concurrency_limit: 32
```

I will note that setting `max_concurrent_runs` to `1` does limit the runs in progress to 1 properly.  But I still don't see more than 3 to 5 in progress when that same config is set to `32`.  This leads me to believe there is some other limit affecting the number of concurrent runs here that I'm running up against.
