### DISCUSSION TITLE
Dagit can't display the runs from python api.

### DISCUSSION THREAD

**Discussion by wangm23456** [dagster-io/dagster#3556] [Q&A] [answered]
Dagit can't display the runs from python api.
f.e. I run a python script to iterates through the pngs of a directory and then start a dagit to do this too (with same dagster.yaml), But history of runs that from script don't display in dagit,  and runs' status from dagit was Queued.
So How should I do to display other runs and event that from python api?

**Comment by gibsondan** [comment, marked as answer]
Hi, would it be possible to post your `dagster.yaml` file? It sounds like you may have queuing enabled on your instance but the queued runs aren't getting started for some reason. If you're using queuing, have you started the `dagster-daemon` process that's used to launch the queued runs?

See https://docs.dagster.io/overview/pipeline-runs/limiting-run-concurrency#setup for how to set up run queueing in your Dagster deployment. (and if it is the daemon that needs to be set up, https://docs.dagster.io/deploying should have more information on how exactly to do that with your setup).

Let us know here or in Slack if that doesn't help.

**Reply by wangm23456** [reply]
```
run_storage:
    module: dagster_postgres.run_storage
    class: PostgresRunStorage
    config:
        postgres_db:
            username:
                env: POSTGRES_USER
            password:
                env: POSTGRES_PASSWORD
            hostname:
                env: POSTGRES_HOST
            db_name:
                env: POSTGRES_DB
            port: 15432

event_log_storage:
    module: dagster_postgres.event_log
    class: PostgresEventLogStorage
    config:
        postgres_db:
            username:
                env: POSTGRES_USER
            password:
                env: POSTGRES_PASSWORD
            hostname:
                env: POSTGRES_HOST
            db_name:
                env: POSTGRES_DB
            port: 15432

scheduler:
    module: dagster.core.scheduler
    class: DagsterDaemonScheduler

schedule_storage:
    module: dagster_postgres.schedule_storage
    class: PostgresScheduleStorage
    config:
        postgres_db:
            username:
                env: POSTGRES_USER
            password:
                env: POSTGRES_PASSWORD
            hostname:
                env: POSTGRES_HOST
            db_name:
                env: POSTGRES_DB
            port: 15432

run_launcher:
    module: dagster.core.launcher
    class: DefaultRunLauncher

run_coordinator:
    module: dagster.core.run_coordinator
    class: QueuedRunCoordinator

compute_logs:
    module: dagster.core.storage.local_compute_log_manager
    class: LocalComputeLogManager

local_artifact_storage:
    module: dagster.core.storage.root
    class: LocalArtifactStorage
    config:
        base_dir: DAGSTER_HOME

telemetry:
    enabled: true
```
