### DISCUSSION TITLE
Increase quantity in progress

### DISCUSSION THREAD

**Discussion by Saamuel** [dagster-io/dagster#4044] [Q&A]
Hello all!

I have more than 20,000 tasks in the queue, and in the in progress status only 3-5 tasks are launched.
How to increase the number of progress of tasks?

![image](https://user-images.githubusercontent.com/19970895/114676702-3b03a980-9d12-11eb-9f11-992fee896b08.png)

my config

```yaml
run_coordinator:
  module: dagster.core.run_coordinator
  class: QueuedRunCoordinator
  config:
    max_concurrent_runs: 25
    tag_concurrency_limits:
      - key: 'magento_img'
        value: 'magento_img'
        limit: 25
```
