### DISCUSSION TITLE
Set PodDisruptionBudget for run-coordinator pods

### DISCUSSION THREAD

**Discussion by amarrella** [dagster-io/dagster#4295] [Q&A]
dagster-run coordinator pods don't like to be rescheduled, and sometimes in Kubernetes clusters, cluster-autoscaler reclaims nodes killing the pods running in them. To avoid this issue it's enough to add a `PodDisruptionBudget` to the dagster helm chart:

```yaml
extraManifests:
  - apiVersion: policy/v1beta1
    kind: PodDisruptionBudget
    metadata:
      name: run-pdb
    spec:
      maxUnavailable: 0
      selector:
        matchLabels:
          app.kubernetes.io/component: run_coordinator
          app.kubernetes.io/part-of: dagster
```

It would be nice if the run coordinators were resilient to these kind of events, but this at least solves the cluster-autoscaler problem, so I thought I would share it here.
