### DISCUSSION TITLE
access to context in scheduler

### DISCUSSION THREAD

**Discussion by beebeed** [dagster-io/dagster#5804] [Q&A]
Hi,

I am very new to dagster and I am trying to figure out how you access the context file when running scheduled jobs. 

What I would like to do is schedule a job every fixed time period and then query a db using the the execution time of the scheduler as one of the input. I had expected the scheduler to write to `context.op_config` the execution time, which would be used by the db function. However the scheduler does not appear to have access to all the parameters in the `context` so the job fails.

Here is a bare bones example which is similar to the example given in github at [scheduler example](https://github.com/dagster-io/dagster/blob/master/examples/docs_snippets/docs_snippets/intro_tutorial/advanced/scheduling/scheduler.py)

```
class DBWarehouse
   def __init__(...)
      configure from context file

   def do_db_stuff():

@resourse
def local_warehouse_resource(context):
   returns DBWarehouse(context.resource_config.parma]

@op(required_resource_key="warehouse")
def do_stuff(context)
   config_parmas = context.op_config["params"]
   context.resources.warehouse.do_db_stuff[config_params]

@job(resource_def={"warehouse":local_warehouse_resource})
def main_job()
   do_suff()

@schedule(
   cron_schedule="* * * * *",
   job=main_job
)
def minute_schedule(context):
   datetime = str(context.scheduled_execution_time)
   return {"ops":{"do_stuff":{"config":{"datetime":datetime}}}}

@repository
def do_stuff_repo():
   return [main_job, minute_schedule]
```

and the corresponding yaml
```
ops:
  do_stuff:
    config: 
        params: "data stuff"
        datatime: "datetime"
resources:
  warehouse:
    config:
       parmas: "resource stuff"
```

this function workswhen I running it as a single job `do_stuff_repo`
however when I run it in dagit in scheduler, it fails since it does have full access the the context... only to the execution datetime 
```
ops:
  do_stuff:
    config: 
        datatime: "datetime"
```

I would really appreciate any help on this.

Thanks

David
