### DISCUSSION TITLE
Make dynamic outputs run in parallel

### DISCUSSION THREAD

**Discussion by dagsir** [dagster-io/dagster#8486] [Q&A]
Quick question - How do I make my Dynamic Outputs run in parallel? I fanned out one of the solids/ops but its only running sequentially.

---

*The question was originally asked in [Dagster Slack](https://dagster.slack.com/archives/C01U954MEER/p1635274840154300?thread_ts=1635274840.154300&cid=C01U954MEER).*

**Comment by yuhan** [comment]
Each job defaults to multiprocess execution, which means if you are using the job/graph/op APIs (as opposed to legacy pipeline/solid APIs), it should be running in parallel by default. To control job execution, you can
1. Toggle between in process and multiprocess via config:
```yaml
execution:
  config:
    in_process:
```
 
2. Manage max concurrent steps in a job via config (https://docs.dagster.io/_apidocs/execution#dagster.multiprocess_executor):
```yaml
execution:
  multiprocess:
    config:
      max_concurrent: 3 
```

See more details in [Controlling Job Execution](https://docs.dagster.io/concepts/ops-jobs-graphs/job-execution#controlling-job-execution).
