### DISCUSSION TITLE
Pass environment variables to dagster.yaml

### DISCUSSION THREAD

**Discussion by dagsir** [dagster-io/dagster#8514] [Q&A]
Hey All.
How would I go about passing environmental variables to the dagster.yaml file?
```
run_launcher:
  module: "dagster_aws.ecs"
  class: "EcsRunLauncher"
  config:
    task_definition: "arn:aws:ecs:us-east-1:1234567890:task-definition/my-task-definition:1"
    container_name: "my_container_name"
```
I need to pass it the aws account number of the env that I am deploying to.

```
run_launcher:
  module: "dagster_aws.ecs"
  class: "EcsRunLauncher"
  config:
    task_definition: "arn:aws:ecs:us-east-1:{AWS_ACC}:task-definition/my-task-definition:{TASK_VERSION}"
    container_name: "my_container_name"
```

---

*The question was originally asked in [Dagster Slack](https://dagster.slack.com/archives/C014UDS8LAV/p1645449054827019?thread_ts=1645449054.827019&cid=C014UDS8LAV).*

**Comment by yuhan** [comment]
You can put the whole task_definition string in its own environment variable and do something like:
```yaml
run_launcher:
  module: "dagster_aws.ecs"
  class: "EcsRunLauncher"
  config:
    task_definition:
      env: MY_TASK_DEFINITION_ENV_VAR
    container_name: "my_container_name"
```
