### DISCUSSION TITLE
use `Selector` in conjunction with other fields

### DISCUSSION THREAD

**Discussion by dagsir** [dagster-io/dagster#8546] [Q&A]
Is there a way to use `Selector` in conjunction with other fields? Like say I wanted to accept:
```
date: YYYY-MM-DD
jar: some_string
```
and
```
date: YYYY-MM-DD
jar_path: some dict
```
as both valid configs, but I only want `jar` or `jar_path` specified, not both. And I would want to require one of them

The example in the docs doesn’t use `Selector` with other fields

---

*The question was originally asked in [Dagster Slack](https://dagster.slack.com/archives/C01U954MEER/p1637279322408700?thread_ts=1637279322.408700&cid=C01U954MEER).*

**Comment by yuhan** [comment]
You may need to nest it a level.  E.g. allow either:
```yaml
date: YYYY-MM-DD
jar:
    path: some dict
```
or
```yaml
date: YYYY-MM-DD
jar:
    string: some_string
```
