### DISCUSSION TITLE
How can I use dagster-mysql ?

### DISCUSSION THREAD

**Discussion by szujung** [dagster-io/dagster#8899] [Q&A]
I tried to connect MySQL by adding `dagster_mysql.MySQLRunStorage` to dagster.yaml.
```
run_storage:
 module: dagster_mysql.run_storage
 class: MySQLRunStorage
 config:
  mysql_db:
   username: "xxxxxxx"
   password: "xxxxxx"
   hostname: "xxxxxx"
   db_name: "xxxxxxx"
   port: 3306
```
However, I got this error:  `sqlalchemy.exc.ProgrammingError: (mysql.connector.errors.ProgrammingError) 1045 (28000)`

I look it up on Google and there is a suggestion that I should edit ini file in MySQL. But I don't think I have the authority to do that.
 Is there any way to fix this problem? Thank you.
