### DISCUSSION TITLE
Support for Cloud SQL Auth proxy when deploying in GKE

### DISCUSSION THREAD

**Discussion by xmarcosx** [dagster-io/dagster#9086] [Ideas]
I have Dagster deployed on Google Kubernetes Engine using the Dagster provided Helm chart. In my deployment, I've disabled PostgreSQL in favor of using Google Cloud SQL. I felt that using a managed database service for my database would be wise given Google handles things like automated backups, point-in-time recovery, automated patching and updates, and the ability to easily adjust compute and memory.

Today I have my values.yaml configured to use the private IP of my Cloud SQL instance ([see here](https://github.com/xmarcosx/dagster-via-kubernetes/blob/master/values.yaml#L39)). This works and it keeps the traffic internal, but it does not use SSL. Not great.

Google recommends (see [here](https://cloud.google.com/sql/docs/postgres/connect-kubernetes-engine#:~:text=The%20Cloud%20SQL%20Auth%20proxy%20is%20the%20recommended%20way%20to%20connect%20to%20Cloud%20SQL%2C%20even%20when%20using%20private%20IP.%20This%20is%20because%20the%20Cloud%20SQL%20Auth%20proxy%20provides%20strong%20encryption%20and%20authentication%20using%20IAM%2C%20which%20can%20help%20keep%20your%20database%20secure.)) the use of Cloud SQL Auth proxy to connect to Cloud SQL. This allows for an encrypted connection between the GKE cluster and Cloud SQL. In this architecture, the Cloud SQL Auth proxy is added to the pods using the sidecar container pattern. Dagster's daemon and Dagit would then connect to the PostgreSQL instance via localhost.

Not a Dagster example, but you will [see here](https://github.com/xmarcosx/edfi-via-kubernetes/blob/master/kubernetes/deployment-pgbouncer.yaml#L62) an example of when I had to do this with a different application.

https://github.com/xmarcosx/dagster-via-kubernetes

It would be so fantastic if Dagster added support for this sidecar pattern to allow for an easy way to deploy Dagster in GKE while keeping the database in Cloud SQL.

**Comment by tdipadova3rd** [comment]
I've opened #24834 to support sidecars for Dagster pods. There are some workarounds required for Kubernetes versions before 1.29, but this PR should allow folks to deploy Dagster on GKE with Cloud SQL Auth Proxy for versions both before and after 1.29.

**K8s 1.29+**
For versions after 1.29, you can deploy Dagster with Cloud SQL Auth Proxy using [Native Sidecars](https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/). 

<details>
<summary>K8s 1.29+ Example Config</summary>

```
runLauncher:
  config:
    k8sRunLauncher:
      runK8sConfig:
        podSpecConfig:
          initContainers:
            - name: cloud-sql-proxy
              restartPolicy: Always
              image: "gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.1.0"
              args:
                - "--private-ip"
                - "--structured-logs"
                - "--port=5432"
                - "your-cloud-sql-instance"
dagsterWebserver:
  extraInitContainers:
    - name: cloud-sql-proxy
      restartPolicy: Always
      image: "gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.1.0"
      args:
        - "--private-ip"
        - "--structured-logs"
        - "--port=5432"
        - "your-cloud-sql-instance"
dagsterDaemon:
  extraInitContainers:
    - name: cloud-sql-proxy
      restartPolicy: Always
      image: "gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.1.0"
      args:
        - "--private-ip"
        - "--structured-logs"
        - "--port=5432"
        - "your-cloud-sql-instance"
migrate:
  extraInitContainers:
    - name: cloud-sql-proxy
      restartPolicy: Always
      image: "gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.1.0"
      args:
        - "--private-ip"
        - "--structured-logs"
        - "--port=5432"
        - "your-cloud-sql-instance"
```
</details>

**K8s before 1.29**
For versions before 1.29, you can deploy Dagster with Cloud SQL Auth Proxy using a few custom commands. For these versions, you cannot use the `K8sRunLauncher`, instead you need to configure deployments to use the `DefaultRunLauncher`, which runs Dagster jobs as new processes in the Code Location pod.

<details>
<summary>K8s 1.28 Example Config</summary>

```
runLauncher:
  type: CustomRunLauncher # Use the custom run launcher to launch on grpc server instead of K8s Job
  config:
    customRunLauncher:
      module: dagster._core.launcher
      class: DefaultRunLauncher
      config: {}
dagsterWebserver:
  extraContainers:
    - name: cloud-sql-proxy
      image: "gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.1.0"
      args:
        - "--private-ip"
        - "--structured-logs"
        - "--port=5432"
        - "your-cloud-sql-instance"
dagsterDaemon:
  extraContainers:
    - name: cloud-sql-proxy
      image: "gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.1.0"
      args:
        - "--private-ip"
        - "--structured-logs"
        - "--port=5432"
        - "your-cloud-sql-instance"
migrate:
  extraContainers:
    - name: cloud-sql-proxy
      image: "gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.1.0"
      args:
        - "--private-ip"
        - "--structured-logs"
        - "--quitquitquit" # Create endpoint to stop the proxy after the job is done
        - "--port=5432"
        - "your-cloud-sql-instance"
  # Override the default migrate command to call the quitquitquit endpoint on completion
  customMigrateCommand:
    - "/bin/sh"
    - "-c"
    - "set -x; sleep 10; trap 'python3 -c \"import requests; requests.post(\\\"http://127.0.0.1:9091/quitquitquit\\\")\"' EXIT; dagster instance migrate"
  postgresql:
    pgIsReadyCommandOverride: "sleep 20;" # Don't check if PG is ready in init-container, just wait because this will fail without a sidecar
```
</details>
