### DISCUSSION TITLE
How do you add an upstream asset to your dbt assets?

### DISCUSSION THREAD

**Discussion by OwenKephart** [dagster-io/dagster#9636] [Q&A] [answered]
Asked on Slack: https://dagster.slack.com/archives/C01U954MEER/p1662050893763849

**Comment by OwenKephart** [comment, marked as answer]
When you load your dbt assets, Dagster determines which asset keys are upstream of your dbt assets based off of the [sources](https://docs.getdbt.com/docs/building-a-dbt-project/using-sources) that are defined in your dbt project. For example, if you have a `sources.yml` file like this:

```yaml
version: 2

sources:
  - name: postgres_replica
    database: postgres_replica
    schema: public
    tables:
      - name: orders
        identifier: _airbyte_raw_orders
      - name: users
        identifier: _airbyte_raw_users
```

(taken from: https://github.com/dagster-io/dagster/blob/master/examples/assets_modern_data_stack/dbt_project/models/sources.yml)

Then Dagster will infer that there are two upstream asset keys for your dbt project, `postgres_replica/orders` and `postgres_replica/users`.

Now, if you create (or load) an asset which *produces* one of those asset keys, this asset will be upstream of whichever dbt assets consume these sources:

![Screen Shot 2022-09-08 at 9 24 44 AM](https://user-images.githubusercontent.com/22457492/189178957-335f1e72-3886-4c14-bd79-c13d5396e7bb.png)
