### DISCUSSION TITLE
Automatically remove Containers with DockerRunLauncher

### DISCUSSION THREAD

**Discussion by PascalStehling** [dagster-io/dagster#9739] [Q&A] [answered]
Hi,

I have the following problem. I have a Dagster Setup running with the DockerRunLauncher. Everything is working fine. The Problem is, that for each Job, a container is created, which is not deleted afterwards. As each container is multiple Gigabytes big (because of some Data Wrangling) the Hard-Drive is filled very fast, which leads to crashing the Database because there is not enough Hard-Drive space left.

The Question: Is there a way to setup the DockerRunLauncher in a way, that after the container ran and did its job, its automatically removed?

Thanks for your help in advance.

**Comment by johannkm** [comment, marked as answer]
Yes:

```yaml
# dagster.yaml
run_launcher:
  class: DockerRunLauncher
  module: dagster_docker
  config:
    container_kwargs:
      auto_remove: true
```

This will get passed to the the `auto_remove` param of the Docker api run method, documented here: https://docker-py.readthedocs.io/en/stable/containers.html#docker.models.containers.ContainerCollection.run
