### DISCUSSION TITLE
How to ensure that only one run of a particular job happens at a time

### DISCUSSION THREAD

**Discussion by sryza** [dagster-io/dagster#9921] [Q&A]
1. Configure the QueuedRunCoordinator

Instructions for this are [here](https://docs.dagster.io/deployment/dagster-instance#instance-configuration-yaml) if you have an OSS Dagster deployment and [here](https://docs.dagster.io/dagster-cloud/developing-testing/managing-deployments#configuring-deployment-settings) if you have a Dagster Cloud deployment.

2. Give your job a tag that's unique to that job:

```
@job(tags={"job": "myjob})
def myjob():
    ...
```

3. Set up a concurrency limit for the queued run coordinator for that tag:

```
run_coordinator:
  module: dagster.core.run_coordinator
  class: QueuedRunCoordinator
  config:
    tag_concurrency_limits:
      - key: "job"
        value: "myjob"
        limit: 1
```

**Comment by pang-wu** [comment]
Is it possible to make this a config on the job itself?

**Reply by sryza** [reply]
This isn't currently possible. That would be preferable to you over the approach outlined here? Any particular reason?

**Reply by pang-wu** [reply]
If the user change the job tag he/she need to make sure dagit configuration also changed (and get deployed) as well -- and job changes more frequent than dagster deployment. That's why the ask :)

**Reply by sryza** [reply]
Something that might help is the `applyLimitPerUniqueValue` option:

```yaml
run_coordinator:
  module: dagster.core.run_coordinator
  class: QueuedRunCoordinator
  config:
    tag_concurrency_limits:
      - key: "single_run_per_value"
        applyLimitPerUniqueValue: true
        limit: 1
```

Then you can opt a job into the limit without needing to update the run coordinator configuration.  In this case, each job will have its own limit, and they won't interfere with each other:

```python
@job(tags={"single_run_per_value": "job1"})
def job1():
    ...

@job(tags={"single_run_per_value": "job2"})
def job2():
    ...
```

**Reply by remigabillet** [reply]
I had the same thoughts as @pang-wu. `applyLimitPerUniqueValue` solves my need, thank you!

**Reply by DanilaBaklazhenkoWolt** [reply]
I believe the correct syntax as of today is the following:
```
run_coordinator:
  module: dagster.core.run_coordinator
  class: QueuedRunCoordinator
  config:
    tag_concurrency_limits:
      - key: "dagster/backfill"
        value:
          applyLimitPerUniqueValue: true
        limit: 1
```
