### ISSUE TITLE
Solid Registry and config-driven solid definition

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#102]
Right now we can "inject" solids into a sub_pipelne using `PipelineDefinition.create_single_solid_pipeline` and `PipelineDefinition.create_sub_pipeline`.

However we want to be able to do this with via config. In order to do this we will need to be able construct solids with only a string as a key. This will necessitate the ability to register solids and look them up by string and parameterize them. You can think of these as "higher order solids" in a way. The libraries need to declare a way to create solids, and then config can be set up to invoke those higher order solids to produce solids. This sounds complicate but when seen in practice it will be quite intuitive.

We want to be able specify something like

```yaml

injected_solids:
    solid_name:
        input_name:
           solid: load_pandas_df_from_csv
           args:
              delimiter: "|"
``` 

This config would dynamically create a solid which is injected into the pipeline.
