### ISSUE TITLE
Clean up pods via TTL Seconds After Finished by configuring HELM deployment instead of individual Jobs.

### ISSUE THREAD

**Issue by dangal95** [dagster-io/dagster#11041]
### What's the use case?

The Kubernetes Executor creates a new Pod everytime a job runs. The pod takes a while to get deleted when the job is finished, unless you specify a tag per job in the following way:
```
tags={
            "dagster-k8s/config": {
                "job_spec_config": {
                    "ttl_seconds_after_finished": TIME_IN_SECONDS
                } 
            }
        },
```
The feature I am requesting would be to create a configuration that is part of the Dagster deployment, and not specific jobs, so that all Job pods can be cleaned up quicker.

### Ideas of implementation

Add this functionality as a configuration in the values.yaml file used to deploy Dagster on Kubernetes.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by rexledesma** [comment]
You can set this outside of Dagster, by setting up a [mutating admission webhook](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#admission-webhooks) in your cluster to specify the TTL of created or finished Kubernetes jobs: https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/#ttl-after-finished-controller.

**Comment by stevenmurphy12** [comment]
+1. We are running Airbyte as part of our data stack which has a periodic process to clean up pods. Whereas with Dagster the pods linger until (presumably) the cluster decides to clean them up (in the region of 24 hours)

**Comment by milesbarnard** [comment]
Looks like you can do it here unless I've misunderstood this: https://github.com/dagster-io/dagster/blob/18ae855c5b12e7614da16ef0da53511fd5deff37/helm/dagster/values.yaml#L626

**Comment by PrabuDzak** [comment]
configuring `jobSpecConfig` works for me. I'm on chart version `1.10.1`

helm values
```yaml
runK8sConfig:
  jobSpecConfig:
    ttlSecondsAfterFinished: 1800
```

job describe
```yaml
Suspend:                     false
Backoff Limit:               0
TTL Seconds After Finished:  1800
Start Time:                  Fri, 04 Apr 2025 14:53:44 +0700
Completed At:                Fri, 04 Apr 2025 15:04:43 +0700
Duration:                    10m
```
