### ISSUE TITLE
event_log schema (asset_keys) not fully created when search_path set to non-default schema in Postgres

### ISSUE THREAD

**Issue by pdavidsonFIA** [dagster-io/dagster#11040]
### Dagster version

1.1.6

### What's the issue?

When a non-default schema is set for storage in dagster.yaml, some of the tables are created in `some_schema`, but asset_keys table is not generated

```
storage:
  postgres:
    postgres_db:
         ...
      params:
         options: -csearch_path=<some_schema>
```

It's related to this recent PR: https://github.com/dagster-io/dagster/pull/10935

### How to reproduce?

set the search path to a non-default schema in an empty postgres DB.

### Deployment type

Local

### Additional information

Operation name: AssetGraphLiveQuery

Message: asset_keys

Path: ["assetNodes",0,"assetMaterializations"]

Locations: [{"line":24,"column":3}]

### Message from the maintainers

Thanks @alangenfeld @prha @rexledesma
