### ISSUE TITLE
[dbt] Allow defining custom functions for dbt exposures

### ISSUE THREAD

**Issue by askvinni** [dagster-io/dagster#11716]
### What's the use case?

Currently, exposures aren't loaded into the asset graph. A team that wants to leverage the functionality but also model it as a data asset in the asset graph, maybe having it execute custom logic, would have to create an asset with the same dependency mapping and write the custom logic inside the asset. While easy enough to execute with a "dbt exposure to asset factory" pattern of sorts, it would be great to have first-class support.

Some of the possible uses:
- Calling an API to update dashboards when the upstream assets are updated
- Emailing stakeholders that new data is available

Added to that, I could see this as another important step towards full declarative scheduling. One could define freshness policies on the exposures directly in the dbt YML files.

### Ideas of implementation

I'm thinking of adding an argument to `load_assets_from_dbt_*` that takes in a `Mapping[str, Callable]`.

Example case:

```yaml
version: 2

exposures:
  - name: my_cool_exposure
    type: dashboard
    maturity: high
    url: https://bi.tool/dashboards/1
    description: A very cool exposure.
    meta:
        dagster_freshness_policy:
            maximum_lag_minutes: 30

    depends_on:
      - ref('fct_orders')
      - ref('dim_customers')
```

```python
def refresh_my_cool_dashboard():
    ...

dbt_assets = load_assets_from_dbt_manifest(
    dbt_exposure_to_func_mapping={"my_cool_exposure": refresh_my_cool_dashboard},
    **kwargs
)
```

This could under the hood wrap `refresh_my_cool_dashboard` in an `AssetsDefinition` with the proper dependencies and freshness policies:
```python
@asset(freshness_policy=FreshnessPolicy(maximum_lag_minutes=30))
def my_exposure_func(fct_orders, dim_customers):
    refresh_my_cool_dashboard()
    return None
```

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
