### ISSUE TITLE
Unexpected GraphQL Error for Schedules

### ISSUE THREAD

**Issue by jerome-laurent-pro** [dagster-io/dagster#11794]
## Dagster version
1.1.10

## What's the issue?

Unexpected GraphQL Error when opening the Schedule screen or any asset on Dagit.

```
Operation name: LatestRunTagQuery

Message: Invalid version: '5.7.38-log'

Path: ["pipelineRunsOrError","results"]

Locations: [{"line":4,"column":7}]
```

## What did you expect to happen?

Schedules and assets are displayed correctly.
The schedules work.

## Additional information

This involves the use of [MySQL storage](https://docs.dagster.io/deployment/dagster-instance#mysql-storage) to persist the metadata.
For the local dev, I added a MySQL container to my `docker-compose`, and everything was running smoothly.
```
  db:
    profiles: [ "local" ]
    image: mysql:5.7
    container_name: dagster_mysql
    hostname: ${MYSQL_HOSTNAME}
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
```

But for deployment, I used the MySQL instance of my company on AWS RDS.
It's working (the metadata is persisted in the MySQL database created for the occasion) BUT there is this specific error appearing on any asset page or on the schedule page. And the schedules don't work.

The MySQL version of the RDS is `5.7.38` so I don't know where the `log` (in `5.7.38-log`) is coming from.

## How to reproduce?

I tried to reproduce it locally but failed.
