### ISSUE TITLE
Error pop up when open raw compute logs using gcs compute log

### ISSUE THREAD

**Issue by Adiyansjah** [dagster-io/dagster#11855]
### Dagster version

1.1.13

### What's the issue?

I got the pop up error message when opening raw compute logs and use google cloud storage as compute logs.
![Screenshot 2023-01-25 at 10 14 29](https://user-images.githubusercontent.com/17077142/214472393-65fddebc-570a-4127-9c9f-8570be8854ad.png)

I assumed this is related to signing blob function or my credential is lack of permission.

### What did you expect to happen?

The error message/notification is not popping up

### How to reproduce?

I am using gcp application default credential with roles 
- roles/iam.serviceAccountTokenCreator
- roles/storage.legacyObjectOwner (granted for specific bucket)
- roles/storage.legacyBucketWriter (granted for specific bucket)

and set the compute log with this value

```yaml
computeLogManager:
  type: GCSComputeLogManager
  config:
    gcsComputeLogManager:
      bucket: dagster-staging
      prefix: dagster
```

try to materialize asset or run the job and open the raw computes logs.

### Deployment type

Dagster Helm chart

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
