### ISSUE TITLE
Materialized assets do not persist between server refreshes

### ISSUE THREAD

**Issue by kevinschaich** [dagster-io/dagster#12101]
### Dagster version

`dagster, version 1.1.15`

### What's the issue?

See GIF below, when restarting server none of my data persists:

![dagster_server_refresh_bug](https://user-images.githubusercontent.com/9244728/216727389-c3750839-b588-49de-b57d-94bc5495ec19.gif)

I have defined  `local_artifact_storage` in `dagster.yaml` as the following:

```yaml
local_artifact_storage:
  module: dagster.core.storage.root
  class: LocalArtifactStorage
  config:
    base_dir: "./storage"
```

### What did you expect to happen?

Assets & job metadata should 

### How to reproduce?

1. Start dagster server
2. Materialize asset
3. Kill server & restart
4. All jobs, runs, and assets are gone

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by kevinschaich** [comment]
I needed to set both `storage` and `local_artifact_storage` in `dagster.yml`. E.g. setting the following config:

```yaml
storage:
  sqlite:
    base_dir: "./.dagster"

local_artifact_storage:
  module: dagster.core.storage.root
  class: LocalArtifactStorage
  config:
    base_dir: "./.dagster"
```

will create a new directory in the same root folder as your `dagster.yaml`:

```
.dagster/
├── history
│   ├── runs
│   │   ├── d81102bc-5603-425e-9e00-2af3e829cba7.db
│   │   └── index.db
│   └── runs.db
├── schedules
│   └── schedules.db
└── storage
    └── my_json.json
```

Now run data & assets are persisting 🙂
