### ISSUE TITLE
Make strategy.rollingUpdate values configurable for Dagit deployment

### ISSUE THREAD

**Issue by caio-eiq** [dagster-io/dagster#12223]
### What's the use case?

When running only one Dagit instance a lot of times the UI won't be available because the strategy.rollingUpdate.maxUnavailable configuration is set to 25% (default values from k8s) which essentially will kill the existing pod when the next one is getting started. 

The dagit deployment is using the default values as shown below:

```
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
```

This behavior will disrupt users from accessing Dagit UI for a short period of time specially when doing multiple helm chart deployments through the day.

The idea of this feature request is make this configurable so we can tweak values as needed (essentially set to `maxUnavailable: 0` when running only with one dagit instance).

### Ideas of implementation

[In the helper Dagit Template](https://github.com/dagster-io/dagster/blob/master/helm/dagster/templates/helpers/_deployment-dagit.tpl) you could just specify the strategy.rollingUpdate and pass the values accordingly. 

Example:

_deployment-dagit.tpl:
```
spec:
  replicas: {{ .Values.dagit.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.dagit.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.dagit.rollingUpdate.maxUnavailable }}
```

values.yaml
```
####################################################################################################
# Dagit: Configuration for the Dagit webserver
####################################################################################################
dagit:
  replicaCount: 1
  # default values
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%
```

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
