### ISSUE TITLE
Document pattern for injecting secrets into config

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1246]
Current thought is that we might want users to write Selectors in config so that we can grab secrets from alternative sources -- e.g., instead of 

```
solids:
  some_solid:
    config:
      username: username
      password: password
```

We could have

```
solids:
  some_solid:
    config:
      credentials:
        value:
          username: username
          password: password
```

or

```
solids:
  some_solid:
    config:
      credentials:
        from_env:
          username: SERVICE_USERNAME
          password: SERVICE_PASSWORD
```

or

```
solids:
  some_solid:
    config:
      credentials:
        from_vault:
          username: service_username_key
          password: service_password_key
```

or

```
solids:
  some_solid:
    config:
      credentials:
        auto_config:
```
