### ISSUE TITLE
dbt runs outside virtual environments, ignoring code location config

### ISSUE THREAD

**Issue by liveandletbri** [dagster-io/dagster#12549]
### Dagster version

1.1.12

### What's the issue?

I have two code locations, each sharing the same Docker image, but using different virtual environments on that image. I did not run any `pip install` commands outside of the virtual environments; in other words the default Python interpreter has no libraries installed to it.

When I use the dbt resource in a job, it fails with this error `FileNotFoundError: [Errno 2] No such file or directory: 'dbt'`. Here is [an example job that failed](https://plunk.dagster.cloud/prod/runs/edada371-de8c-45b1-9139-41e08c58ef3a?logFileKey=autlbxhi). Here are some logs - notice they're coming from within `/base_env`, which is my virtual environment.
```
  File "/opt/dagster/app/dagster_repo/export_parcel_details.py", line 13, in dbt_parcel_details
    context.resources.dbt.run(models=['+parcel_details_export'], exclude='parcel_id_entity_resolution')
  File "/base_env/lib/python3.10/site-packages/dagster_dbt/cli/resources.py", line 145, in run
    return self.cli("run", models=models, exclude=exclude, select=select, **kwargs)
  File "/base_env/lib/python3.10/site-packages/dagster_dbt/cli/resources.py", line 90, in cli
    return execute_cli(
  File "/base_env/lib/python3.10/site-packages/dagster_dbt/cli/utils.py", line 101, in execute_cli
    process = subprocess.Popen(
  File "/usr/local/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
```

When I got these errors, my Dockerfile had this at the top:
```
COPY dagster/requirements.txt /requirements.txt
COPY dagster/requirements_databricks.txt /requirements_databricks.txt

# Different Python environments for different code locations
RUN python -m venv base_env
RUN /base_env/bin/pip install -r /requirements.txt

RUN python -m venv databricks_env
RUN /databricks_env/bin/pip install -r /requirements_databricks.txt
```

If I change it to this, which installs dbt to the default interpreter, outside any virtual environment, everything works:
```
COPY dagster/requirements.txt /requirements.txt
COPY dagster/requirements_databricks.txt /requirements_databricks.txt

# install dbt to default interpreter
RUN pip install dbt-core==1.2.0
RUN pip install dbt-snowflake==1.2.0

# Different Python environments for different code locations
RUN python -m venv base_env
RUN /base_env/bin/pip install -r /requirements.txt

RUN python -m venv databricks_env
RUN /databricks_env/bin/pip install -r /requirements_databricks.txt
```

I tried a version of the Dockerfile only installing `dbt-core`, and not `dbt-snowflake`. That gave me these errors:
![image](https://user-images.githubusercontent.com/29556484/221304174-b428b8c2-a318-497e-8b19-d255bba1f934.png)

Interestingly, you can see how the errors are coming from `/usr/local/lib/python3.10` - the default interpreter on my image, _not_ the one in my virtual environment. I believe this is because [dbt is being called with subprocess.Popen](https://github.com/dagster-io/dagster/blob/26e219cad5e45ad9673ef03d6cf2ca3e569c33d9/python_modules/libraries/dagster-dbt/dagster_dbt/cli/utils.py#L129-L134), but nothing is enforcing that dbt must be run inside the virtual environment.

### What did you expect to happen?

The Dagster job should have used the version of dbt I installed in my virtual environment, and not cared what is installed to the default interpreter.

### How to reproduce?

1. Create a Docker image for Dagster with dbt _only_ installed in a virtual environment
2. Set up a code location that uses this virtual environment with `executable_path`
3. Create a Dagster job that uses the dbt resource and calls it via context, e.g. `context.resources.dbt.run()`

### Deployment type

Dagster Hybrid

### Deployment details

Using Dagster Hybrid on Kubernetes, hosted in EKS. The images that the Dagster steps run in is built using Docker. The executor for my jobs is `k8s_job_executor`. I use the `dbt_cli_resource` to call dbt. My `dagster` and `dagster-cloud` versions are both 1.1.12.

Here is the config for my code locations:
```
locations:
  - location_name: chthonic_dagster_hybrid
    executable_path: /base_env/bin/python
    code_source:
      python_file: dagster_repo/repository.py
    build:
      directory: ./process/
      registry: <redacted>.amazonaws.com/dev/dagster-agent
    working_directory: dagster_repo/
    container_context:
      k8s:
        env_secrets:
          - dagster-snowflake-password
  - location_name: chthonic_dagster_databricks
    executable_path: /databricks_env/bin/python
    code_source:
      python_file: dagster_repo/repository_databricks.py
    build:
      directory: ./process/
      registry: <redacted>.amazonaws.com/dev/dagster-agent
    working_directory: dagster_repo/
    container_context:
      k8s:
        env_secrets:
          - dagster-snowflake-password
```

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
