### ISSUE TITLE
endpoint_url for s3_pickle_io_manager

### ISSUE THREAD

**Issue by AndreaGiardini** [dagster-io/dagster#12835]
### Dagster version

1.1.20

### What's the issue?

The S3 iomanager does not provide a way to configure the endpoint as code: https://docs.dagster.io/_apidocs/libraries/dagster-aws#dagster_aws.s3.s3_pickle_io_manager

I can configure the bucket or the prefix, but the endpoint needs to be specified on the resource instead. 

```
resources:
  s3:
    config:
      endpoint_url: "http://localhost"
      # Optional[str]: Specifies a custom endpoint for the S3 session. Default is None.
```

That's quite cumbersome since it's a configuration that won't often change so it would be nice to have it specified as code. Unfortunately boto does not support setting the endpoint via an environment variable either.

This would be particularly nice for people testing dagster locally on minio or using cloud providers like digitalocean.

### What did you expect to happen?

I would expect to be able to set the endpoint via `s3_pickle_io_manager` together with prefix and bucket.

### Deployment type

Dagster Helm chart

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
