### ISSUE TITLE
Configuration in `dagster.yml` not detect environment variables

### ISSUE THREAD

**Issue by chungquantin** [dagster-io/dagster#13000]
### Dagster version

1.2.1

## Issue
I am trying to use `dagster-postgres` for persistent storage and `dagster-aws` for S3 resource. Both has configuration does not work with environment variables declared in `dagster.yml`. For example, if I declare the configuration as a literal string, it does work.
```yaml
storage:
    postgres:
        postgres_db:
            username: "postgres"
            password: "password"
            hostname: "127.0.0.1"
            db_name: "postgres"
            port: 5433
```
But with this, it does not
```
run_storage:
  module: dagster_postgres.run_storage
  class: PostgresRunStorage
  config:
    postgres_db:
      hostname: postgresql
      username:
        env: DAGSTER_POSTGRES_USER
      password:
        env: DAGSTER_POSTGRES_PASSWORD
      db_name:
        env: DAGSTER_POSTGRES_DB
      port: 5432
```
Even though variables are set
```
DAGSTER_PG_HOST=127.0.0.1
DAGSTER_PG_PORT=5433
DAGSTER_PG_USERNAME=postgres
DAGSTER_PG_PASSWORD=password
DAGSTER_PG_DB=postgres
``` 

### What did you expect to happen?

I expect the dagster daemon is launched normally using the Postgres database for persistent storage.

### How to reproduce?

Not sure how to reproduce, I just follow this blog: https://docs.dagster.io/deployment/dagster-instance#postgres-storage

### Deployment type

Local

### Deployment details

<img width="507" alt="Screen Shot 2023-03-16 at 18 21 20" src="https://user-images.githubusercontent.com/56880684/225765551-0f850f34-839b-4611-ba66-86dcaeb87e78.png">

### Additional information

N/A

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
