### ISSUE TITLE
Helm chart does not deploy user-code deployment

### ISSUE THREAD

**Issue by MaxTeiger** [dagster-io/dagster#13356]
### Dagster version

dagster, version 1.2.4 (in the pod)

### What's the issue?

I deployed a dagster stack on my Kubernetes cluster following [this tutorial](https://docs.dagster.io/deployment/guides/kubernetes/deploying-with-helm#step-61-configure-the-deployment) using Helm Chart v1.2.4. 

Evrything went fine and I have all these resources healthy in my cluster : 
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/38110296/229808871-90e6c12e-6791-46de-90a9-4cb662bc14ae.png">

But when I try to add a new user-code deployment using the values.yaml file, nothing happens when I am deploying it, still only one user-code deployment (`dagster-user-deployments-k8s-example-user-code-1`). 

This is how I updated my `values.yaml` file : 
```yaml
dagit:
  [...]
  workspace:
    enabled: true

    # List of servers to include in the workflow file. When set,
    # `externalConfigmap` must be empty.
    servers:
      - host: "k8s-example-user-code-1"
        port: 3030
        name: "user-code-example"
  
+      - host: "k8s-example-user-code-2"
+        port: 3030
+        name: "user-code-example-2"

[...]
dagster-user-deployments:
  enabled: true

  enableSubchart: true

  imagePullSecrets: []

  # List of unique deployments
  deployments:
    - name: "k8s-example-user-code-1"
      image:
        # When a tag is not supplied, it will default as the Helm chart version.
        repository: "docker.io/dagster/user-code-example"
        tag: ~
        pullPolicy: Always

      dagsterApiGrpcArgs:
        - "--python-file"
        - "/example_project/example_repo/repo.py"
      port: 3030

+    - name: "k8s-example-user-code-2"
+      image:
+        # When a tag is not supplied, it will default as the Helm chart version.
+        repository: "docker.io/dagster/user-code-example"
+        tag: ~
+        pullPolicy: Always
+
+      dagsterApiGrpcArgs:
+        - "--python-file"
+        - "/example_project/example_repo/repo.py"
+      port: 3030
+
      # Whether or not to include configuration specified for this user code deployment in the pods
      # launched for runs from that deployment
      includeConfigInLaunchedRuns:
        enabled: true
[...]
```

In fact, when a run `helm template . > dagster-app.yaml` 

There is absolutely no trace of `k8s-example-user-code-2`. Even when I change the occurrences of `k8s-example-user-code-1` to let's say `k8s-example-user-code-1-test`, the resulting application after applying the `value.yaml` file is still `k8s-example-user-code-1`.

I think there is a problem regarding how this variable is handled in your chart

### What did you expect to happen?

I expect the helm chart to take my modifications on user-deployments in account when rendering a template from my `values.yaml` file.

### How to reproduce?

With helm chart version 1.2.4, try adding a new user user-deployment in the `values.yaml` file. 

### Deployment type

Dagster Helm chart

### Deployment details

```bash
> helm version
version.BuildInfo{Version:"v3.9.4", GitCommit:"dbc6d8e20fe1d58d50e6ed30f09a04a77e4c68db", GitTreeState:"clean", GoVersion:"go1.19"}
```

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
