### ISSUE TITLE
Change config-driven presets to code-driven

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1345]
instead of 

```
  kwargs:
    repo_config:
      pipelines:
        error_monster:
          presets:
            passing:
              environment_files:
                - environments/error.yml
```
```
presets=[PresetDefinition(name=‘passing’, files=[‘environments/error.yml’])]
```
on a PipelineDefinition
