### ISSUE TITLE
Add configuration to remove colors from logging

### ISSUE THREAD

**Issue by joshuataylor** [dagster-io/dagster#14012]
### What's the use case?

I pipe all logs from dagster/dagit into a file in systemd:

```conf
StandardOutput=append:/var/log/dagster/logs.log
StandardError=append:/var/log/dagster/logs.log
```

This is great, except that it has ANSI colors. You can see from using `cat` that it has colors:
<img width="1410" alt="SCR-20230501-srso" src="https://user-images.githubusercontent.com/225131/235459069-05f242af-3a3c-4467-918b-ed7c8a9bde00.png">

I've tried using `python_logs` in `dagster.yaml`, but it's handy to have additional information that something like systemd provides, as it shows things like failures, etc.

```yaml
python_logs:
  python_log_level: DEBUG
  dagster_handler_config:
    handlers:
      myHandler:
        class: logging.FileHandler
        level: DEBUG
        filename: "dagster_logs.log"
        mode: "a"
        formatter: timeFormatter
    formatters:
      timeFormatter:
        format: "%(asctime)s :: %(message)s"
```

### Ideas of implementation

Ability to disable ANSI Colors in logs.

Maybe `color_logs: false` or something?

I couldn't find a generic `log` group, something like this would be awesome?
```yaml
log:
  color: true
```

Default color to true, as it's handy in development etc.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
