### ISSUE TITLE
Creating multiple assets from the same configurable op using AssetsDefinition.from_op leads to confusing config scaffold

### ISSUE THREAD

**Issue by jcbiddle** [dagster-io/dagster#14198]
### What's the use case?

I've been working on creating a library of reusable ops that a number of different pipelines can draw from, and thought that the `AssetsDefinition.from_op` functionality would be very useful for this purpose. However, I noticed that if multiple assets are defined from the same op and the op requires config data, the config scaffold contains a number of entries of the form `op_name_1`, `op_name_2`, etc... 

Even if the output asset name is specified via the  `keys_by_output_name={"result": AssetKey("asset1")}` argument, the op config isn't nested under the config schema for `asset1`. The following code replicates this situation:

```
from dagster import op, Config, AssetsDefinition, AssetKey, Definitions, graph_asset


class MyConfig(Config):
    value: str


@op
def my_configurable_op(config: MyConfig):
    return config.value


asset1 = AssetsDefinition.from_op(my_configurable_op,
                                  keys_by_output_name={"result": AssetKey("asset1")})
asset2 = AssetsDefinition.from_op(my_configurable_op,
                                  keys_by_output_name={"result": AssetKey("asset2")})


@graph_asset()
def asset3():
    return my_configurable_op()


defs = Definitions(assets=[asset1, asset2, asset3])

```

Dagit scaffolds the following config structure:
```
ops:
  asset3:
    ops:
      my_configurable_op:
        config:
          value: ""
  my_configurable_op:
    config:
      value: ""
  my_configurable_op_2:
    config:
      value: ""
```
When reading the config, there is no relation between `asset1`, `asset2` and their corresponding invocations of `my_configurable_op`. This is confusing, and in my opinion limits the reusability of configurable ops via the `AssetsDefinition` pattern.

As shown in the above example, a workaround solution is to instead create a `graph_asset` that uses the op. This seems like it should behave the same as the `AssetsDefinition` pattern, but instead it provides a cleaner config with `my_configurable_op` nested under `asset3`. 

### Ideas of implementation

Ideally, it would be nice if there were a way to generate an asset from an op that behaved identically to if the asset was written explicitly, e.g.
```
@asset
def asset4(config: MyConfig):
    return config.value
```
which gives the config scaffold
```
ops:
  asset4:
    config:
      value: ""
```

This may not be possible due to the desire to track op usages throughout the pipeline. If this solution isn't possible, then I feel that the config schema should conform to the `graph_asset` behaviour as shown above. In this case, the above example would ideally have the following config schema
```
ops:
  asset1:
    ops:
      my_configurable_op:
        config:
          value: ""
  asset2:
    ops:
      my_configurable_op:
        config:
          value: ""
  asset3:
    ops:
      my_configurable_op:
        config:
          value: ""
```

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
