### ISSUE TITLE
Duplicate Image Pull Policies in Dagster Helms

### ISSUE THREAD

**Issue by airton-neto** [dagster-io/dagster#14429]
### Dagster version

1.3.5

### What's the issue?

Hi there,

I'm trying to deploy a local testing server using Kind and deploying via Helm with K8sRunLauncher/Celeryk8sRunLaucher configuration.

I found a particular issue trying to use a local image 'dagster-test-project' after 'kind load' it in my run nodes.

- In dagster/dagster-user-sployments, each deployment has a field 'image.pullPolicy', in which I choose to set to 'Never'

- On the other hand, runLauncher configs have a field 'imagePullPolicy' which is recommended to be set in 'Always', and surpass our first setting.

My cluster is always trying to pull a new image for 'dagster-test-project', which does not exist in the cloud and is already available in Kind nodes.

Some helpful commands:

```
helm repo add --force-update dagster https://dagster-io.github.io/helm
helm show values dagster/dagster > values_new.yml
helm show values dagster/dagster-user-sployments > dep_new.yml
```

### What did you expect to happen?

I expected for both **Runs** and **Code Servers** to reach out dagster-user-deployments 'pullPolicy', as they're expected to have tha same code.

### How to reproduce?

Unfortunately I had to set some things using Kind cluster and some Helm charts, that is nt this ready to reproduce.

### Deployment type

Dagster Helm chart

### Additional information

If you guys are interested, I could write a simple section to explain how to deploy dagster using Kind and Helm.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by gibsondan** [comment]
Hi @airton-neto - Have you tried running 'kubectl describe' on a run pod to verify what the image pull policy is? I would expect it to be using the value from dagster-user-deployments, like you expect it to (provided you have `includeConfigOnLaunchedRuns` set to true, which is the default behavior).

If that's different than what you're seeing, can you post the values.yaml that you're using in the dagster-user-deployments chart and the output of 'kubectl describe' for the run pod?

**Comment by airton-neto** [comment]
Hi there!

I've done some more testing, and I have to correct my first comment,
It works fine when `K8sRunLauncher`. Not when using `CeleryK8sRunLauncher` (maybe for the same reason described in https://github.com/dagster-io/dagster/issues/13728)

My deployment config:

```yaml
deployments:
  - name: 'testing'
    image:
      repository: 'dagster-test-project'
      tag: latest
      pullPolicy: Never
          labels:
      app: dagster-dagster-temp
          dagsterApiGrpcArgs:
      - '--module-name'
      - 'test_project'
    port: 3030
        includeConfigInLaunchedRuns:
      enabled: true
          env:
      DAGSTER_GRPC_TIMEOUT_SECONDS: '180'
    envConfigMaps: []
        envSecrets:
      - name: client33
          volumes: []
        volumeMounts: []
        annotations: {}
    nodeSelector: {}
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: nodepool
                  operator: In
                  values:
                    - dagster-codeservers
    tolerations:
      - effect: NoSchedule
        key: dagster-codeservers
        operator: Equal
        value: 'true'
      - effect: NoSchedule
        key: kubernetes.azure.com/scalesetpriority
        operator: Equal
        value: spot
    podSecurityContext: {}
    securityContext: {}
    resources: {}
        readinessProbe:
      periodSeconds: 20
      timeoutSeconds: 3
      successThreshold: 1
      failureThreshold: 3
          livenessProbe: {}
    startupProbe:
      enabled: false
          service:
      annotations: {}
      imagePullSecrets: []
      serviceAccount:
  create: true
    name: ''
    annotations: {}
    rbacEnabled: true
extraManifests: []

```

My runLauncher config

```yaml
runLauncher:
  type: K8sRunLauncher
    config:


    k8sRunLauncher:
      imagePullPolicy: 'Always'
      jobNamespace: dagster-runs
      loadInclusterConfig: true
      kubeconfigFile: ~
      envConfigMaps: []
      envSecrets: []
      envVars: []
      volumes: []
      volumeMounts: []
      labels: {}
      resources: {}
        failPodOnRunFailure: false
      securityContext: ~
      runK8sConfig:
        jobSpecConfig:
          ttlSecondsAfterFinished: 240
        containerConfig:
          resources:
            limits:
              cpu: 1000m
              memory: 2000Mi
            requests:
              cpu: 500m
              memory: 700Mi
          imagePullPolicy: IfNotPresent
        podSpecConfig:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: nodepool
                        operator: In
                        values:
                          - dagster-lightruns
          tolerations:
            - effect: NoSchedule
              key: dagster-lightruns
              operator: Equal
              value: 'true'
            - effect: NoSchedule
              key: kubernetes.azure.com/scalesetpriority
              operator: Equal
              value: spot


    celeryK8sRunLauncher:
      imagePullPolicy: 'Always'
            image:
        repository: 'docker.io/dagster/dagster-celery-k8s'
        tag: ~
        pullPolicy: Always
              jobNamespace: dagster-runs
            nameOverride: 'celery-workers'
            configSource: {}
      workerQueues:
        - name: 'dagster'
          replicaCount: 4
          labels: {}
          nodeSelector: {}
          configSource: {}
          additionalCeleryArgs: []
        - name: 'main'
          replicaCount: 4
          labels: {}
          nodeSelector: {}
          configSource: {}
          additionalCeleryArgs: []
      env: {}
      envConfigMaps: []
      envSecrets: []
            annotations: {}
      nodeSelector: {}
            affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodepool
                    operator: In
                    values:
                      - dagster-workers
      tolerations:
        - effect: NoSchedule
          key: dagster-workers
          operator: Equal
          value: 'true'
        - effect: NoSchedule
          key: kubernetes.azure.com/scalesetpriority
          operator: Equal
          value: spot
      podSecurityContext: {}
      securityContext: {}
      resources: {}
            livenessProbe:
        initialDelaySeconds: 15
        periodSeconds: 10
        timeoutSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      volumes: []
      volumeMounts: []
      labels: {}
      failPodOnRunFailure: false
```


OBS: 
  Does this behaviour have anything to do with my `k8sRunLauncher.runK8sConfig.containerConfig` configuration? 
  There is also a pullpolicy configured there.
