### ISSUE TITLE
[Helm] Ability to get postgresqlUsername from env or a secret 

### ISSUE THREAD

**Issue by MathieuLaksh** [dagster-io/dagster#15023]
### What's the use case?

For security, we'd like to have rotating username/password pairs for our database, Dagster included. 
But the current helm chart it is only possible do to so for the password.

### Ideas of implementation

I imagine the easiest way would be to have predetermined env variable names in the postgresql helper, with a boolean in the helm chart. Something like this for example:
Helm chart:
```
postgresql:
  # set postgresql.enabled to be false to disable deploy of a PostgreSQL database and use an
  # existing external PostgreSQL database
  enabled: true

  # Used by init container to check that db is running. (Even if enabled:false)
  image:
    repository: "library/postgres"
    tag: "14.6"
    pullPolicy: IfNotPresent

  postgresqlConfigFromEnv: false

  postgresqlUsername: test

  postgresqlPassword: test

  postgresqlDatabase: test

  postgresqlParams: {}

  postgresqlScheme: ""

  service:
    port: 5432
generatePostgresqlPasswordSecret: false
```

and in the helper something like:
```
{{- define "dagsterYaml.postgresql.config" }}
postgres_db:
  {{- if .Values.postgresql. postgresqlConfigFromEnv }}
  username:
    env: DAGSTER_PG_USERNAME
  hostname:
    env: DAGSTER_PG_HOSTNAME
  db_name:
    env: DAGSTER_PG_DB_NAME
  {{- else }}
  username: {{ .Values.postgresql.postgresqlUsername }}
  hostname: {{ include "dagster.postgresql.host" . }}
  db_name: {{ .Values.postgresql.postgresqlDatabase	}}
  {{- end }}
  password:
    env: DAGSTER_PG_PASSWORD
  port: {{ .Values.postgresql.service.port }}
  params: {{- .Values.postgresql.postgresqlParams | toYaml | nindent 4 }}
  {{- if .Values.postgresql.postgresqlScheme }}
  scheme: {{ .Values.postgresql.postgresqlScheme }}
  {{- end }}
{{- end }}
```

### Additional information

I hesitated with doing directly a PR as I felt like it was not a big change, but I'm not familiar enough with the inner workings of the dagster.yaml file and the potential side effects from the helm chart.

thanks in advance for your help!

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
