### ISSUE TITLE
DBT tests not run when materializing

### ISSUE THREAD

**Issue by PascalStehling** [dagster-io/dagster#15391]
### Dagster version

dagster, version 1.3.14

### What's the issue?

As stated in [this](https://github.com/dagster-io/dagster/discussions/15172#discussioncomment-6387959) discussion answer, the dbt tests should run when materializing the data and if they fail the dagster run will fail. But when defining tests, they will be detected by dagster, but not run.

### What did you expect to happen?

Exactly like described in the discussion, to fail the run if the tests fails.

### How to reproduce?

Th easiest way is to copy the [assets_dbt_python](https://github.com/dagster-io/dagster/tree/master/examples/assets_dbt_python) example and add replace the company column entry in dbt_project->models->cleaned->schema.yml with
```yml
      - name: "company"
        description: "The name of the company that this user belongs to."
        data_type: "str"
        tests:
          - unique
```

With this a test for uniqueness of that column is added, which should fail, as the column values are not unique.

Then just run on of the two jobs. The test should be detected (as shown in the screenshot), but it will not fail and there is no mention of it being run.
![image](https://github.com/dagster-io/dagster/assets/33455644/a8c27760-b2d2-429e-9c70-b9fcfe055c72)

### Deployment type

Local

### Deployment details

deployed and run via `dagster dev`

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
