### ISSUE TITLE
Config wrapping function crash from dagit

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1570]
Using the config_mapping pipeline in toys, with config:

```
solids:
  outer_wrap:
    config:
      outer_first: "3"
      outer_second: "3"
      outer_third: 3.0
```

gives:

```Exception occurred during execution of user config mapping function outer_wrap_fn defined by solid outer_wrap from definition outer_wrap at path root:solids:outer_wrap: Traceback (most recent call last): File "/Users/max/dev/dagster/python_modules/dagster/dagster/core/types/evaluator/evaluation.py", line 252, in _evaluate_composite_solid_config frozendict(context.config_value.get('config')), TypeError: outer_wrap_fn() takes 1 positional argument but 2 were given```
