### ISSUE TITLE
Dagster tagged AWS Secrets on UserCode instance: "raise TypeError(f'the JSON object must be str, bytes or bytearray"

### ISSUE THREAD

**Issue by yepher** [dagster-io/dagster#15770]
### Dagster version

dagster, version 1.4.4

### What's the issue?

AWS Secrets tagged with `dagster` are automatically showing up in my run instance because of EcsRunLauncher and that has been great. I've now been working towards "[Structuring your Dagster project](https://docs.dagster.io/guides/dagster/recommended-project-structure)" and as part of that, I've moved some code into `__init__.py`
```secret = json.loads(os.getenv('dagsterSecret'))`

defs = Definitions(
    assets=all_assets,
    resources={
        "bigquery": BigQueryResource(gcp_credentials=base64.b64encode(secret['bq_credentials'].encode("utf-8"))),
        "redshift": RedshiftClientResource(
            host=secret['redshift_host'],
            port=5439,
            user=secret['redshift_user'],
            password=secret['redshift_password'],
            database=secret['redshift_database'],
        )
    },

) 
```

When I put that in `__init__.py` I get an error on the user-code server. And the server fails to startup:

```
secret = json.loads(os.getenv('dagsterSecret'))
raise TypeError(f'the JSON object must be str, bytes or bytearray,
```

That makes sense because EcsRunLauncher only sets it on the run container, not the daemon, web server, or user-code containers.

My question is, how do folks tend to handle this? I can certainly handle an env variable not being set, but I would like to fail start-up if that env variable is not set. This [example](https://github.com/dagster-io/dagster/blob/master/examples/project_fully_featured/project_fully_featured/__init__.py) code seems like it would suffer the same problem if anything depended on a "secret" tagged dagster

From [Slack Thread](https://dagster.slack.com/archives/C014UDS8LAV/p1691605910863019)

### What did you expect to happen?

I expect user code not to try and use the environment variables. 

### How to reproduce?

Change [project_fully_featured](https://github.com/dagster-io/dagster/blob/master/examples/project_fully_featured/project_fully_featured/__init__.py) example code to use an AWS secret that has been tagged as `dagster` while using `EcsRunLauncher`. You will see the usercode server complains.

### Deployment type

Other

### Deployment details

This is running in AWS ECS from a Docker container.

### Additional information

_No response_

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by yepher** [comment]
[Here](https://dagster.slack.com/archives/C04CW71AGBW/p1691691904687679) is another related issue:

In Dagster running on ECS I have an env var dagsterSecret={ lot of stuff, "bigquery_creds"="JSON STUFF"}. I am trying to set up DBT in dagster that connects to BigQuery and use this auth the nested env var for authentication. Does anyone have any notes, or point me to a resource on how this typically works? I will have almost the same question but for Redshift too

dbt accepts this configuration:
Bigquery: https://docs.getdbt.com/docs/core/connect-data-platform/bigquery-setup#authentication-methods

I am doing what the dbt docs say and loading from config/profiles.yml  and using env variables from ECS that are tagged dagster But the problem is it blows up on the usercode server because the variables are not set there, they are only set on the run instances. Trying to understand how that is supposed to work when using Dagster in ECS with DBT.

This is my config/profiles.yml which works if dagsterSecrets is set:
config:
```
  send_anonymous_usage_stats: False

bigquery:
  target: dev

  outputs:
    dev:
      type: bigquery
      method: service-account-json
      project: product-analytics-prod
      dataset: dagster_testing_euw1
      threads: 1
      connect_timeout: 999999

      keyfile_json:
        type: "{{ fromjson(fromjson(env_var('dagsterSecret'))['bq_credentials'])['service_account'] }}"
        project_id: "{{ fromjson(fromjson(env_var('dagsterSecret'))['bq_credentials'])['project_id'] }}"
        private_key_id: "{{ fromjson(fromjson(env_var('dagsterSecret'))['bq_credentials'])['private_key_id'] }}"
        private_key: "{{ fromjson(fromjson(env_var('dagsterSecret'))['bq_credentials'])['private_key'] }}"
        client_email: "{{ fromjson(fromjson(env_var('dagsterSecret'))['bq_credentials'])['client_email'] }}"
        client_id: "{{ fromjson(fromjson(env_var('dagsterSecret'))['bq_credentials'])['client_id'] }}"
        auth_uri: "{{ fromjson(fromjson(env_var('dagsterSecret'))['bq_credentials'])['auth_uri'] }}"
        token_uri: "{{ fromjson(fromjson(env_var('dagsterSecret'))['bq_credentials'])['token_uri'] }}"
        auth_provider_x509_cert_url: "{{ fromjson(fromjson(env_var('dagsterSecret'))['bq_credentials'])['auth_provider_x509_cert_url'] }}"
        client_x509_cert_url: "{{ fromjson(fromjson(env_var('dagsterSecret'))['bq_credentials'])['client_x509_cert_url'] }}"
```

This is the error:
```
                :
                :
                :
August 10, 2023 at 19:14 (UTC-5:00)	dagster_dbt.errors.DagsterDbtCliFatalRuntimeError: Fatal error in the dbt CLI (return code 2): Running with dbt=1.5.4 Encountered an error:	59641355e51047b098011e43d2e91444	usercode
August 10, 2023 at 19:14 (UTC-5:00)	Parsing Error	59641355e51047b098011e43d2e91444	usercode
August 10, 2023 at 19:14 (UTC-5:00)	Env var required but not provided: 'dagsterSecret'	59641355e51047b098011e43d2e91444	usercode
August 10, 2023 at 19:14 (UTC-5:00)	manifest, cli_output = _load_manifest_for_project(	59641355e51047b098011e43d2e91444	usercode
August 10, 2023 at 19:14 (UTC-5:00)	^^^^^^^^^^^^^^^^^^^^^^^^^^^	59641355e51047b098011e43d2e91444	usercode
August 10, 2023 at 19:14 (UTC-5:00)	File "/usr/local/lib/python3.11/site-packages/dagster_dbt/asset_defs.py", line 84, in _load_manifest_for_project	59641355e51047b098011e43d2e91444	usercode
August 10, 2023 at 19:14 (UTC-5:00)	cli_output = execute_cli(
                :
                :
                :
```
That is because Dagster EcsRunLauncher only loads AWS secrets tagged as dagster on the run server and not on the usercode server. I am not sure why it is even getting loaded on the user-code server in the first place. I have essentially followed this [project_fully_feature](https://github.com/dagster-io/dagster/tree/master/examples/project_fully_featured/dbt_project) but using BigQuery instead of DuckDB. And it works if I hard code the env var on the usercode server. But that should not be needed.

If I change to using `load_assset_from_dbt_manifest` it works but then it is not dependent on runtime environment anymore.
