### ISSUE TITLE
init-user-deployment is missing securityContext in daemon

### ISSUE THREAD

**Issue by maowerner** [dagster-io/dagster#16092]
### Dagster version

1.4.9

### What's the issue?

In the `deployment-daemon.yaml` a `initContainer` is created for every element of `userDeployment.deployments` 

This is not inheriting the (container-)security context `Values.dagsterDaemon.securityContext` like the `check-db-ready` initContainer or the actual daemon.

With Pod Security restrictions in place there is no way to get past the admission hook

```
client.go:510: [debug] Patch Deployment "quyl-dagster-daemon" in namespace my-namespace
W0825 10:34:21.105561  147828 warnings.go:70] would violate PodSecurity "restricted:v1.24":  ...
```

### What did you expect to happen?

Setting `Values.dagsterDaemon.securityContext` should set security context for all containers

### How to reproduce?

A basic yaml file like
```
---
# values.yaml
.containerSecurityContext: &containerSecurityContext
  runAsUser: 1001

dagsterDaemon:
  securityContext: *containerSecurityContext
```

and looking at the deployment with 
```
helm install -f values.yaml -n _my-namespace_
and kubectl get deployment -o yaml _my-namespace_-dagster-daemon
```

```
...
- command:
        - sh
        - -c
        - until nslookup k8s-example-user-code-1; do echo waiting for user service;
          sleep 2; done
        image: docker.io/busybox:1.28
        imagePullPolicy: IfNotPresent
        name: init-user-deployment-k8s-example-user-code-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
```
(without the securityContext section)

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
