### ISSUE TITLE
Dynamically generate secrets for postgres on the helm installation to use your own backend

### ISSUE THREAD

**Issue by AlejandroUPC** [dagster-io/dagster#16686]
### What's the use case?

In the current `values.yaml` file the only way to define some of the parameters to connect to postgres is to use [this fields](https://github.com/dagster-io/dagster/blob/master/helm/dagster/values.yaml#L773):

```yaml
  postgresqlHost: ""
  postgresqlUsername: test
  postgresqlPassword: test
  postgresqlDatabase: test
```

Ideally, it would be nice to have a way to specify those values by mapping it to secrets where postgres can then connect.

### Ideas of implementation

This probably requires re-doing some parts of the helm file, I am not an expert and have a lot of time but I can try and support anyone who is willing to start.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
