### ISSUE TITLE
URL Malformed on Backfill with ingress "my.server/mycodeserver"

### ISSUE THREAD

**Issue by airton-neto** [dagster-io/dagster#16690]
### Dagster version

1.4.15

### What's the issue?

URL composition problem when doing bakfills.

Ingress has the structure "my.server/mycodeserver" (my.server was wrapped in the pics).
After adding backfill and clicking "View" tooltip, codeserver is taken off of the URL and the page crashes.
![_1](https://github.com/dagster-io/dagster/assets/64480652/7da496a6-bffd-433c-af28-451281d0d46c)
![_2](https://github.com/dagster-io/dagster/assets/64480652/dbf00736-6dad-4a18-b7a1-38b40f49107f)

My ingress.yml file is like

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.org/ssl-services: dagsters
  name: dagsters
  namespace: dagsters
spec:
  ingressClassName: nginx
  rules:
    - host: my.dagster.server
      http:
        paths:
          - backend:
              service:
                name: eolica-2w-webserver
                port:
                  name: http
            path: /eolica-2w
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - my.dagster.server
      secretName: dagsters-tls-cert
```

### What did you expect to happen?

See backfill page (I still can, just by fixing the url after pressing "view").

### How to reproduce?

Deploy a code server using this kind of ingress
Access via browser (Chrome in my case)
Create a backfill
Press "View".

### Deployment type

Dagster Helm chart

### Deployment details

Used the latest helm chart version.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
