### ISSUE TITLE
Dagster UI 

### ISSUE THREAD

**Issue by YuviGold** [dagster-io/dagster#16697]
### Dagster version

1.3.13

### What's the issue?

When the Dagster deployment is configured with an **S3ComputeLogManager**, and compute logs are uploaded successfully, but the Dagster UI pod isn't provided with credentials - it shows `No log file available`.

### What did you expect to happen?

Show an error of unauthorized, distinguish between 404 and 403.

Additionally, the [official documentation](https://docs.dagster.io/_apidocs/libraries/dagster-aws#s3) should describe prerequisites in order to use the **S3ComputeLogManager**
- Install `dagster-aws` library.
- Configure credentials to the worker as well as to the dagster UI
- Define what is the minimum policy required (e.g. `s3:GetObject`)

### How to reproduce?

1. Configure S3ComputeLogManager
```yaml
computeLogManager:
  type: S3ComputeLogManager
  config:
    s3ComputeLogManager:
      bucket: "${s3_bucket}"
```

2. Provide AWS access key to workers but not to Dagster UI
```yaml
runLauncher:
  type: K8sRunLauncher
  config:
    k8sRunLauncher:
      envSecrets:
        - name: "${aws_access_key}"
        - name: "${aws_secret_access_key}"
```

3. Run a job, verify it has been finished and logs have been uploaded to the S3 bucket successfully
4. Go to the stderr/stdout frames in the Dagster UI and see **No log file available**

It could be easily resolved when defining
```yaml
dagsterWebserver:
  envSecrets:
    - name: "${aws_access_key}"
    - name: "${aws_secret_access_key}"
```

### Deployment type

Dagster Helm chart

### Deployment details

```yaml
dagster-user-deployments:
  enabled: true
  deployments:
    - name: "${name}"
      image:
        repository: "${dagster_repository}"
        tag: "${dagster_tag}"
        pullPolicy: Always
      port: 3030
      envSecrets:
        - name: "${aws_access_key}"
        - name: "${aws_secret_access_key}"
      dagsterApiGrpcArgs:
        - "--module-name"
        - "my_dagster"

runLauncher:
  type: K8sRunLauncher
  config:
    k8sRunLauncher:
      envSecrets:
        - name: "${aws_access_key}"
        - name: "${aws_secret_access_key}"

postgresql:
  enabled: false
  postgresqlHost: "${postgres_host}"
  postgresqlUsername: "${postgres_username}"
  postgresqlPassword: "${postgres_password}"
  postgresqlDatabase: "${postgres_database}"

computeLogManager:
  type: S3ComputeLogManager
  config:
    s3ComputeLogManager:
      bucket: "${s3_bucket}"
```

### Additional information

Full conversation on https://dagster.slack.com/archives/C014N0PK37E/p1695217382229209

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
