### ISSUE TITLE
Dagster 1.5.5+ & Pydantic compatibility issues

### ISSUE THREAD

**Issue by benpankow** [dagster-io/dagster#17612]
Hello all - recently, we released Dagster 1.5.5, which included long-awaited support for [Pydantic 2](https://docs.pydantic.dev/latest/blog/pydantic-v2-final/). Dagster continues to support Pydantic 1.x, as we realize other packages that users depend on may not have updated their pins.

This discussion will collect reported issues with Pydantic 1.x and 2.x from Dagster 1.5.5+, and include troubleshooting steps.

### Dagster does not properly handle using `pydantic<2.0.0` and `pydantic-core`

The [`pydantic-core` package](https://pypi.org/project/pydantic-core/#description) is new with Pydantic 2 and is installed automatically when downloading `pydantic>=2.0.0`. However, when downgrading Pydantic to 1.x and not removing `pydantic-core`, Dagster 1.5.5 will raise often-confusing errors based on this mismatch. [A fix](https://github.com/dagster-io/dagster/pull/17589) is shipping with Dagster 1.5.6. In the meantime, ensure you either are not installing `pydantic-core` or are using `pydantic>=2.0.0`.

### Dagster libraries will error if version mismatched with the core `dagster` package

Because of the compatibility layer introduced in dagster `1.5.5`, older versions of libraries may not work properly. Ensure that your dagster libraries are matching, either `==1.5.5` or `==0.21.5`, depending on package versioning scheme.

**Comment by zaneselvans** [comment]
While the requirement for `pydantic<2` has been relaxed int he main python package, the pin which prohibits its use is still present in the [conda-forge packaging recipe meta.yml](https://github.com/conda-forge/dagster-feedstock/blob/main/recipe/meta.yaml#L279):

```yaml
    requirements:
      host:
        - python >=3.8
        - pip
      run:
        - {{ pin_subpackage("dagster-pipes", max_pin="x.x.x") }}
        - alembic >=1.2.1,!=1.6.3,!=1.7.0,!=1.11.0
        - click >=5.0
        - coloredlogs >=6.1,<=14.0
        - croniter >=0.3.34
        - docstring_parser
        - grpcio >=1.44.0
        - grpcio-health-checking >=1.44.0
        - jinja2
        - packaging >=20.9
        - pendulum
        - protobuf >=3.20.0
        - psutil >=1.0
        - pydantic >1.10.0,!=1.10.7,<2.0.0
        - python >=3.8
        - python-dateutil
        - python-dotenv
        - pytz
        - pywin32-on-windows
        - pyyaml >=5.1
        - requests
        - setuptools
        - sqlalchemy >=1.0
        - tabulate
        - tomli
        - toposort >=1.0
        - tqdm
        - typing_extensions >=4.4.0
        - universal_pathlib
        - watchdog >=0.8.3
```
