### ISSUE TITLE
Tags not overriding defaults set in dagster.yaml

### ISSUE THREAD

**Issue by jamiedemaria** [dagster-io/dagster#17818]
### Discussed in https://github.com/dagster-io/dagster/discussions/17813

<div type='discussions-op-text'>

<sup>Originally posted by **dagsir[bot]** November  8, 2023</sup>
Hey team, I'm attempting to use the `tags` keyword of the `define_asset_job` function to customise the ECS launched runs CPU and Memory of a specific job, however it is still taking the default values applied in the `dagster.yaml`. Has anyone encountered this before and know how to solve it? This is my asset job definition:
```python
generic_asset_job = define_asset_job(
    "generic_asset_job",
    selection=AssetSelection.groups("generic_group"),
    tags={
        "ecs/cpu": "16384",
        "ecs/memory": "32768",
    },
)
```
and this is my `dagster.yaml`:
```yaml
scheduler:
  module: dagster.core.scheduler
  class: DagsterDaemonScheduler

run_coordinator:
  module: dagster.core.run_coordinator
  class: QueuedRunCoordinator

run_launcher:
  module: dagster_aws.ecs
  class: EcsRunLauncher
  config:
    include_sidecars: true
    secrets_tag: "dagster"
    run_resources:
      cpu: "8192"
      memory: "16384" # In MiB
      ephemeral_storage: 30 # In GiB (defaults to 20)
```

---

*The question was originally asked in [Dagster Slack](https://dagster.slack.com/archives/C014UDS8LAV/p1699447286604429?thread_ts=1699447286.604429&cid=C014UDS8LAV).*</div>
