### ISSUE TITLE
Add date annotations to dagster-user-deployment deployment yaml

### ISSUE THREAD

**Issue by woolparka** [dagster-io/dagster#17874]
### What's the use case?

Dagster user deployments using the helm chart is a bit tricky when using a fixed image tag name.

When using a fixed image tag for the open source helm deployment for dragster, on the helm chart `dagster-user-deployment`, using values such as:
```
deployments:
- name: my-user-deployment
  image:
    repository: registry.gitlab.com/my-org/my-repo/my-image
    tag: latest
    pullPolicy: Always
```
and updating the `latest` image in the registry, followed by a helm upgrade, helm cannot pick up the most up to date `latest` image automatically and have to go through manual rollouts. This is because k8s uses image tag as first class, and only resolves the image SHA at pod creation.

Issue is described more in detail on helm side [here](https://github.com/helm/helm/issues/5696).

The work around is to provide a date label as suggested above, so that the always pull policy behaves as expected.

### Ideas of implementation

Add to current `deployment.yaml` [here](https://github.com/dagster-io/dagster/blob/22436b46a1d37ddf3f3a4bf304bac8d70b639859/helm/dagster/charts/dagster-user-deployments/templates/deployment-user.yaml#L28)

```
 date: "{{ now | unixEpoch }}"
```

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
