### ISSUE TITLE
Schedule doesn`t start from command line

### ISSUE THREAD

**Issue by newturok** [dagster-io/dagster#1812]
I use
`dagster schedule start --start-all`
inside docker container for script in docs [https://dagster.readthedocs.io/en/0.6.0.post0/sections/learn/tutorial/scheduler.html](https://dagster.readthedocs.io/en/0.6.0.post0/sections/learn/tutorial/scheduler.html)

**Dockerfile:**
```
FROM python:3.7.4-slim-stretch

RUN apt-get update
RUN apt-get -y install cron 

RUN pip install dagster
RUN pip install dagit
RUN pip install dagster-cron

WORKDIR /dagster

EXPOSE 3000

ENTRYPOINT [ "dagit", "-h", "0.0.0.0", "-p", "3000" ]
```
**docker-compose.yml**
```
version: '3'
services:
  dagster:
    build: .
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    ports:
      - 3000:3000
    volumes:
      - ./dagster:/dagster
```
And get
![image](https://user-images.githubusercontent.com/5757827/66256964-3a449b80-e79c-11e9-8e3e-e20d1574e303.png)
