### ISSUE TITLE
Unable to backfill a subset of partitions via the UI when using dict-like keys

### ISSUE THREAD

**Issue by dsgibbons** [dagster-io/dagster#18145]
### Dagster version

1.5.9

### What's the issue?

I like to sometimes use JSON-style dictionary strings as partition keys. If I try to select a subset of these keys for backfilling via the web UI, I get a GraphQL error. This is not a problem if I let the web UI materialize all (or even just missing/failed) partition keys. 

### What did you expect to happen?

The web UI should correctly initiate a backfill for a subset of dictionary-like partition keys.

### How to reproduce?

Create a virtual environment with Python version 3.10.6 and filesystem with files: 

```
.
├── dagtest.py
└── pyproject.toml
```

## `pyproject.toml`
```toml

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dagtest"
version = "0.0.1"
requires-python = ">=3.10"

dependencies = [
    "dagster",
    "dagster-webserver",
]

[tool.dagster]
module_name = "dagtest"
```

## `dagtest.py`
```python
import json

import dagster as dg

my_partition = dg.DynamicPartitionsDefinition(name="my-partition")


@dg.sensor()
def my_sensor(context: dg.SensorEvaluationContext) -> dg.SensorResult:
    return dg.SensorResult(
        dynamic_partitions_requests=[
            my_partition.build_add_request(
                [
                    json.dumps({"key1": "value1", "key2": "value2"}),
                    json.dumps({"key1": "value3", "key2": "value4"}),
                    json.dumps({"key1": "value5", "key2": "value6"}),
                ],
            ),
        ],
    )


@dg.asset(partitions_def=my_partition)
def my_asset(context: dg.OpExecutionContext) -> None:
    context.log.info(f"Creating my_asset {context.partition_key}")


defs = dg.Definitions(
    assets=[my_asset],
    sensors=[my_sensor],
)
```

Install dependencies via `pip install .` and then run `dagster dev` to start.

Navigate to the UI and enable the sensor. The partitions are correctly added by the sensor. Select an individual partition (e.g., `{"key1": "value1", key2": "value2"}`). Click `Materialize`, and then `Launch backfill`. The web UI displays `Unexpected GraphQL error`. If no partitions are selected, then `Launch backfill` works as expected.

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
