### ISSUE TITLE
Unable to auto-materialize more than one simultaneous partition

### ISSUE THREAD

**Issue by dsgibbons** [dagster-io/dagster#18144]
### Dagster version

1.5.9

### What's the issue?

If more than one partition is added simultaneously (i.e., by a sensor), the auto-materialize policy `AutoMaterializePolicy.eager()` only materializes a single partition. This does not seem to be a problem if partitions are added one-at-a-time between auto-materialization runs.

### What did you expect to happen?

`AutoMaterializePolicy.eager()` should correctly materialize all partitions.

### How to reproduce?

Create a virtual environment with Python version 3.10.6 and filesystem with files: 

```
.
├── dagtest.py
└── pyproject.toml
```

## `pyproject.toml`
```toml

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dagtest"
version = "0.0.1"
requires-python = ">=3.10"

dependencies = [
    "dagster",
    "dagster-webserver",
]

[tool.dagster]
module_name = "dagtest"
```

## `dagtest.py`
```python
import dagster as dg

my_partition = dg.DynamicPartitionsDefinition(name="my-partition")


@dg.sensor()
def my_sensor(context: dg.SensorEvaluationContext) -> dg.SensorResult:
    return dg.SensorResult(
        dynamic_partitions_requests=[
            my_partition.build_add_request(["a", "b", "c"]),
        ],
    )


@dg.asset(
    partitions_def=my_partition,
    auto_materialize_policy=dg.AutoMaterializePolicy.eager(),
)
def my_asset(context: dg.OpExecutionContext) -> None:
    context.log.info(f"Creating my_asset {context.partition_key}")


defs = dg.Definitions(
    assets=[my_asset],
    sensors=[my_sensor],
)
```

Install dependencies via `pip install .` and then run `dagster dev` to start.

Navigate to the UI and enable the sensor and auto-materialization policy. The partitions are correctly sensed, but all-but-one of them are discarded during auto-materialization. These partitions are never considered again in future iterations of auto-materialization.

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
