### ISSUE TITLE
We should be able to use env variables in all dagster.yaml properties

### ISSUE THREAD

**Issue by EtienneT** [dagster-io/dagster#18729]
### Dagster version

1.15.11

### What's the issue?

I wanted to parametrize my run_retries to be enabled in production, but disabled in dev.  I tried using environment variables like I did for configuring postgres usename and password (which are strings).  But it doesn't seem to work for other types of variables like boolean or int.  Here is the relevant part of my dagster.yaml:

```
run_retries:
  enabled:
    env: DAGSTER_RUN_RETRIES_ENABLED
  max_retries:
    env: DAGSTER_RUN_RETRIES_MAX_RETRIES
```

Then I can declare it like this in my .env file:

```
DAGSTER_RUN_RETRIES_ENABLED=True
DAGSTER_RUN_RETRIES_MAX_RETRIES=3
```

I get the following error:

```
dagster._core.errors.DagsterInvalidConfigError: Errors whilst loading dagster instance config at dagster.yaml.
    Error 1: Invalid scalar at path root:run_retries:enabled. Value "{'env': 'DAGSTER_RUN_RETRIES_ENABLED'}" of type "<class 'dict'>" is not valid for expected type "Bool".
    Error 2: Invalid scalar at path root:run_retries:max_retries. Value "{'env': 'DAGSTER_RUN_RETRIES_MAX_RETRIES'}" of type "<class 'dict'>" is not valid for expected type "Int".
```

### What did you expect to happen?

The pattern of using an environment variable in dagster.yaml should be the same for all properties.  Simply passing `env: ENV_VARIABLE_NAME` should work for all properties.

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by Ronaldo-AP** [comment]
Hello, exactly the same thing happens to me but when configuring `tag_concurrency_limits` as shown in https://docs.dagster.io/deployment/dagster-instance#queuedruncoordinator

**Comment by tomsej** [comment]
This really annoyed me. Anyway, for those who need a quick solution you can use `envsubst` in your Docker `entrypoint`, like:

```
cat dagster_template.yaml | envsubst > dagster.yaml
```

**Comment by drewagentsync** [comment]
Same situation with these config settings. Seems to be any value that expects a boolean. 

`  branch_deployments: { "env": "ENABLE_BRANCH_DEPLOYMENTS" } `

and

`   code_server_metrics:
      enabled: { "env": "CODE_SERVER_METRICS_ENABLED" }
    agent_metrics:
      enabled: { "env": "AGENT_METRICS_ENABLED" }`

**Comment by DruidNx** [comment]
Bumping this issue. We are not able to define mountpoints from variables in dagster.yaml, so each developer has to checkout the repo and then define an absolute path for their mount point. 

```
run_launcher:
  module: dagster_docker
  class: DockerRunLauncher
  config:
    env_vars:
      - DATA_DIR
      - DAGSTER_ENVIRONMENT
    network: dagster_network
    container_kwargs:
      volumes: # Make docker client accessible to any launched containers as well
        - /var/run/docker.sock:/var/run/docker.sock
        - /tmp/io_manager_storage:/tmp/io_manager_storage
        - /home/dev/data:/data
```

Ideally we would like to define the mountpoint as follows: `- ${DATA_DIR}:/data`

**Comment by eracle** [comment]
Any update?

**Comment by garethbrickman** [comment]
@eracle This is not being actively worked on

**Comment by eracle** [comment]
why?

**Comment by cukezr** [comment]
> Bumping this issue. We are not able to define mountpoints from variables in dagster.yaml, so each developer has to checkout the repo and then define an absolute path for their mount point.
> 
> ```
> run_launcher:
>   module: dagster_docker
>   class: DockerRunLauncher
>   config:
>     env_vars:
>       - DATA_DIR
>       - DAGSTER_ENVIRONMENT
>     network: dagster_network
>     container_kwargs:
>       volumes: # Make docker client accessible to any launched containers as well
>         - /var/run/docker.sock:/var/run/docker.sock
>         - /tmp/io_manager_storage:/tmp/io_manager_storage
>         - /home/dev/data:/data
> ```
> 
> Ideally we would like to define the mountpoint as follows: `- ${DATA_DIR}:/data`

I'm also looking for this.
Did you manage to define the mountpoint at the end?

**Comment by jumpmanjay** [comment]
Trying to configure postgres database port via environment variables and am running into this issue. A fix would be nice.

**Comment by seanr-ba** [comment]
I believe this is also a problem when trying to set the VPC configuration for the ECS run launcher, which is crucial as this absolutely needs to change for each environment.

The below `dagster.yaml` works for the task definition, container name and cluster name, but not for subnets and security groups, presumably because these are passed as a list/tuple behind the scenes, whereas (as mentioned above) the env var functionality only seems to work for string.

```
run_launcher:
  module: dagster_aws.ecs
  class: EcsRunLauncher
  config:
    use_current_ecs_task_config: false
    task_definition:
      env: TASK_DEFINITION_NAME
    container_name:
      env: CONTAINER_NAME
    run_task_kwargs:
      cluster:
        env: CLUSTER_NAME
      launchType: "FARGATE"
      networkConfiguration:
        awsvpcConfiguration:
          subnets:
            env: DAGSTER_ECS_SUBNET_IDS
          securityGroups:
            env: DAGSTER_ECS_SECURITY_GROUP_IDS
          assignPublicIp: "DISABLED"
```

```
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter networkConfiguration.awsvpcConfiguration.securityGroups, value: {'env': 'DAGSTER_ECS_SECURITY_GROUP_IDS'}, type: <class 'dict'>, valid types: <class 'list'>, <class 'tuple'>
Invalid type for parameter networkConfiguration.awsvpcConfiguration.subnets, value: {'env': 'DAGSTER_ECS_SUBNET_IDS'}, type: <class 'dict'>, valid types: <class 'list'>, <class 'tuple'>
```
