### ISSUE TITLE
dagster/retry_strategy tag "FROM_FAILURE" is ignored

### ISSUE THREAD

**Issue by saaramitay** [dagster-io/dagster#18965]
### Dagster version

1.4.6

### What's the issue?

Configuring the dagster/retry_strategy tag "FROM_FAILURE"  in the @job or in the Launchpad resulting in the run "ignoring" the tag.
Dagster does identifies a pod failure and starts a new pod (since runRetries is implemented) but instead of running from failure, it starts all steps again.

### What did you expect to happen?

Dagster needs to retry steps from failure in the new runner it creates.

### Deployment type

Dagster Helm chart

### Deployment details

Dagster is deployed in GKE via helm chart.

### Additional information

Using gcs_pickle_io_manager:
```
    "io_manager": gcs_pickle_io_manager.configured(
        {
            "gcs_bucket": TEST_TEMPORARY_PIPELINE_STORAGE_BUCKET,
            "gcs_prefix": DAGSTER_SSP_MANAGED_STORAGE_FOLDER,
        }
    )`
```
Steps outputed to the IO_Manager.

Run retries is enabled in the dagster.yaml:
```
run_retries:
  enabled: true
  max_retries: 3
```

and in the helm chart:
```
  runMonitoring:
    enabled: true
    # Timeout for runs to start (avoids runs hanging in STARTED)
    startTimeoutSeconds: 600
    # Max number of times to attempt to resume a run with a new run worker
    maxResumeRunAttempts:
    # How often to check on in progress runs
    pollIntervalSeconds: 120
    cancel_timeout_seconds: 180

    runRetries:
      enabled: true
      maxRetries: 3
```

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
