### ISSUE TITLE
Add support for relative path for volumes `container_kwargs` for `DockerRunLauncher`

### ISSUE THREAD

**Issue by Prajwalrajbasnet** [dagster-io/dagster#19318]
### What's the use case?

I'm using `docker-compose` to run Dagster with a separate self-managed code location service and utilizing `DockerRunLauncher` to be able to isolate each run in a separate container. I want to be able to load new definitions upon code changes without rebuilding the service since I'm using this same setup for local development as well. 

I've followed this guide https://github.com/dagster-io/dagster/discussions/14709 to use the new `dagster code-server start` command to run the code location server instead of the previous `dagster grpc api` and I'm mounting a volume to the source code in my host machine to the code location service to use the same. However to attach the same volume to the launched container spawned by `DockerRunLauncher` I need to use the absolute path to the source code folder which will be different depending on the host machine. So, I cannot set the absolute path for my host machine which will be different for another engineers working from their machine in the `dagster.yaml` file. I want to be able to do something like this in `dagster.yaml` file:

```yaml
run_launcher:
  module: dagster_docker
  class: DockerRunLauncher
    container_kwargs:
      volumes: 
        - ./my-source-code-directory:app/my-source-code-directory"
```

I don't seem to be able to use environment variables which can be dynamically set per host machine as well:

```yaml
run_launcher:
  module: dagster_docker
  class: DockerRunLauncher
    container_kwargs:
      volumes: 
        - ${SOURCE_CODE_PATH}:app/my-source-code-directory"
```

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by mdolr** [comment]
hey had the same issue here is a workaround i was able to work out for my dev flow, i'm running a similar setup of docker-compose in a monorepo

```
/
  docker-compose.yaml
  docker-compose.dev.yaml
  
  start.dev.sh
  
  pipeline/
    dagster.yaml
    workspace.yaml
    ... rest of the dagster project
    
  front/
    ... frontend & other components of my monorepository
```

I made a small script `start.dev.sh` to start the dev environment that populates an environment variable and passes it to the docker-compose

```bash
#!/bin/bash

# set env variable dev & get current path from where the script is launched
export ENV='dev'
export CURRENT_PATH=$(pwd)

# if --build then use --build
if [ "$1" == "--build" ]; then
    echo "Current path: $CURRENT_PATH"
    docker compose -f docker-compose.yaml -f docker-compose.dev.yaml up -d --build
else
    echo "Current path: $CURRENT_PATH"
    docker compose -f docker-compose.yaml -f docker-compose.dev.yaml up -d
fi
```

then my `docker-compose.yaml` looks like this
```yaml
version: '3'

services:
  # ...other services

  # ------- DAGSTER -----------
  # pipeline code
  pipeline:
    build:
      context: ./pipeline
      dockerfile: ./Dockerfile-pipeline
    image: pipeline
    restart: always
    environment:
      DAGSTER_POSTGRES_USER: 'postgres'
      DAGSTER_POSTGRES_PASSWORD: 'postgres'
      DAGSTER_POSTGRES_DB: 'postgres'
      DAGSTER_CURRENT_IMAGE: 'pipeline'
      DAGSTER_POSTGRES_HOST: 'dagster-postgres'
      DAGSTER_POSTGRES_PORT: 3007
      ENV: 'prod'
    volumes:
      - ./pipeline:/opt/dagster/app
    networks:
      - dagster-network
    command: dagster code-server start -h 0.0.0.0 -p 4000 -m src
  
  dagster-postgres:
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGPORT: 3007
    ports:
      - 127.0.0.1:3007:3007
    networks:
      - dagster-network

  dagster-webserver:
    build:
      context: ./pipeline
      dockerfile: ./Dockerfile-dagster
    entrypoint:
      - dagster-webserver
      - -h
      - '0.0.0.0'
      - -p
      - '80'
      - -w
      - workspace.yaml
    environment:
      DAGSTER_POSTGRES_USER: postgres
      DAGSTER_POSTGRES_PASSWORD: postgres
      DAGSTER_POSTGRES_DB: postgres
      DAGSTER_POSTGRES_HOST: 'dagster-postgres'
      DAGSTER_POSTGRES_PORT: 3007
      DAGSTER_GRPC_SERVER_HOST: 'pipeline'
      DAGSTER_GRPC_SERVER_PORT: 4000
      ENV: 'prod'
    ports:
      - 127.0.0.1:3005:80
    volumes: # Make docker client accessible so we can terminate containers from the webserver
      - /var/run/docker.sock:/var/run/docker.sock
      - io_manager_storage:/tmp/io_manager_storage
    networks:
      - dagster-network
    depends_on:
      - dagster-postgres
      - pipeline

  # This service runs the dagster-daemon process, which is responsible for taking runs
  # off of the queue and launching them, as well as creating runs from schedules or sensors.
  dagster-daemon:
    build:
      context: ./pipeline
      dockerfile: ./Dockerfile-dagster
    entrypoint:
      - dagster-daemon
      - run
    restart: on-failure
    environment:
      DAGSTER_POSTGRES_USER: postgres
      DAGSTER_POSTGRES_PASSWORD: postgres
      DAGSTER_POSTGRES_DB: postgres
      DAGSTER_POSTGRES_HOST: 'dagster-postgres'
      DAGSTER_POSTGRES_PORT: 3007
      DAGSTER_GRPC_SERVER_HOST: 'pipeline'
      DAGSTER_GRPC_SERVER_PORT: 4000
      ENV: 'prod'
    volumes: # Make docker client accessible so we can launch containers using host docker
      - /var/run/docker.sock:/var/run/docker.sock
      - io_manager_storage:/tmp/io_manager_storage
      - ./pipeline/dagster.yaml:/opt/dagster/dagster_home/dagster.yaml
      - ./pipeline/workspace.yaml:/opt/dagster/dagster_home/workspace.yaml
    networks:
      - dagster-network
    depends_on:
      - dagster-webserver
      - dagster-postgres
      - pipeline

networks:
  dagster-network:
    driver: bridge
    name: dagster-network

volumes:
  io_manager_storage:
    driver: local
    name: io_manager_storage
```

and then i have a `docker-compose.dev.yaml` file that overrides some environment variables and also mounts a volume ith read only access to my `/pipeline` folder from the `$CURRENT_PATH` environment variable representing the absolute path obtained in the `start.dev.sh` script

```yaml
version: '3'

services:
  pipeline:
    volumes:
    # mount normally because no headache from the dagster.yaml 
      - ./pipeline:/opt/dagster/app
    ports:
      - 127.0.0.1:4000:4000
    environment:
      ENV: 'dev'

  dagster-daemon:
    environment:
      ENV: 'dev'
      CURRENT_PATH: ${CURRENT_PATH}
    volumes:
      - ./pipeline/dagster.yaml:/opt/dagster/dagster_home/dagster.yaml
      - ./pipeline/workspace.yaml:/opt/dagster/dagster_home/workspace.yaml
      # mount the volume as proxy to the code folder in read-only mode
      - pipeline:/opt/dagster/app:ro 

  dagster-webserver:
    environment:
      ENV: 'dev'

volumes:
  pipeline:
    driver: local
    name: pipeline
    driver_opts:
      type: none
      o: bind
      device: ${CURRENT_PATH}/pipeline
```

and finally from my `dagster.yaml` i call that docker "proxy" volume that i just created
```yaml
scheduler:
  module: dagster.core.scheduler
  class: DagsterDaemonScheduler

run_coordinator:
  module: dagster.core.run_coordinator
  class: QueuedRunCoordinator

run_launcher:
  module: dagster_docker
  class: DockerRunLauncher
  config:
    env_vars:
      - DAGSTER_POSTGRES_USER
      - DAGSTER_POSTGRES_PASSWORD
      - DAGSTER_POSTGRES_DB
      - DAGSTER_POSTGRES_HOST
      - DAGSTER_POSTGRES_PORT
      - ENV
    container_kwargs:
      network_mode: host
      volumes:
        # Make docker client accessible to any launched containers as well
        - /var/run/docker.sock:/var/run/docker.sock
        - /tmp/io_manager_storage:/tmp/io_manager_storage
        - pipeline:/opt/dagster/app

run_storage:
  module: dagster_postgres.run_storage
  class: PostgresRunStorage
  config:
    postgres_db:
      hostname:
        env: DAGSTER_POSTGRES_HOST
      username:
        env: DAGSTER_POSTGRES_USER
      password:
        env: DAGSTER_POSTGRES_PASSWORD
      db_name:
        env: DAGSTER_POSTGRES_DB
      port: 3007

schedule_storage:
  module: dagster_postgres.schedule_storage
  class: PostgresScheduleStorage
  config:
    postgres_db:
      hostname:
        env: DAGSTER_POSTGRES_HOST
      username:
        env: DAGSTER_POSTGRES_USER
      password:
        env: DAGSTER_POSTGRES_PASSWORD
      db_name:
        env: DAGSTER_POSTGRES_DB
      port: 3007

event_log_storage:
  module: dagster_postgres.event_log
  class: PostgresEventLogStorage
  config:
    postgres_db:
      hostname:
        env: DAGSTER_POSTGRES_HOST
      username:
        env: DAGSTER_POSTGRES_USER
      password:
        env: DAGSTER_POSTGRES_PASSWORD
      db_name:
        env: DAGSTER_POSTGRES_DB
      port: 3007
```

hope that helps 🙏
