### ISSUE TITLE
K8s config per code-location

### ISSUE THREAD

**Issue by jPinhao-Rover** [dagster-io/dagster#19599]
### Discussed in https://github.com/dagster-io/dagster/discussions/19279

<div type='discussions-op-text'>

<sup>Originally posted by **jPinhao-Rover** January 18, 2024</sup>
We are self-hosting dagster and have k8s specific configuration that we need to apply to any triggered job - notably `pod_spec_config.service_account_name` - without which the job can't run. We have a set of code locations, and within each code location all jobs should use the same k8s service account. Our instance is configured with `k8sRunLauncher` and the default executor.

So far we've been attaching the k8s service account as a [tag on the job definitions](https://docs.dagster.io/deployment/guides/kubernetes/customizing-your-deployment#per-job-kubernetes-configuration), ie.:

```
job = define_asset_job(
    name="job",
    selection=[assets],
    tags={
        "dagster-k8s/config": {
            "pod_spec_config": {"service_account_name": "code-location-service-account"}
        }
    })
```

This has worked fine until now as we were only triggering materialisations via jobs, and all executions carried the tags configured. However we now need to enable materialising assets directly (so we can have backfills respecting `backfill_policy`), and when doing so the job tags are disregarded as we're not triggering a job.

There currently doesn't seem to be away to specify the podSpec at the code-location level as the [deployment configuration for each of the code locations](https://docs.dagster.io/deployment/guides/kubernetes/deploying-with-helm#step-61-configure-the-deployment) doesn't allow this. It seems this is [doable instance-wide](https://docs.dagster.io/deployment/guides/kubernetes/customizing-your-deployment#instance-level-kubernetes-configuration), but we'd want distinct values configured per code location.</div>

**Comment by brent-at-aam** [comment]
@jPinhao-Rover I am currently going through the same discovery. I know this is a pretty old issue and it may not be relevant for you any longer, but I was able to achieve a default config at a code location by using helm template to generate the k8s manifests and patching the Deployment.  

https://github.com/dagster-io/dagster/blob/master/helm/dagster/charts/dagster-user-deployments/templates/deployment-user.yaml#L67-L76

```yaml
            {{- if $deployment.dagsterApiGrpcArgs }}
            # uses the auto_envvar_prefix of the dagster cli to set the --container-context arg
            # on 'dagster api grpc'
            - name: DAGSTER_CLI_API_GRPC_CONTAINER_CONTEXT
              value: {{ include "dagsterUserDeployments.k8sContainerContext" (list $ $deployment) | fromYaml | toJson | quote }}
            {{- else }}
            - name: DAGSTER_CONTAINER_CONTEXT
              value: {{ include "dagsterUserDeployments.k8sContainerContext" (list $ $deployment) | fromYaml | toJson | quote }}
            {{- end }}
            {{- end }}
```

`DAGSTER_CONTAINER_CONTEXT` or `DAGSTER_CLI_API_GRPC_CONTAINER_CONTEXT`, one of these env vars (depending on your user deployment configuration) is what needs to be changed..

If the user deployment helm chart could be updated to include injecting these values directly, it would certainly make things easier.

In the meantine, here's a very minimal example using kustomize:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: dagster-user-deployments
    repo: https://dagster-io.github.io/helm
    includeCRDs: false
    valuesInline:
      deployments:
        - name: example
          includeConfigInLaunchedRuns:
            enabled: true
          image:
            repository: some/example-image
            tag: 1.0.0
            pullPolicy: IfNotPresent
          port: 3030
    releaseName: example
    version: 1.8.4
    namespace: dagster

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: example-dagster-user-deployments-example
      spec:
       template:
        spec:
          containers:
            - name: dagster-user-deployments
              env:
               - name: DAGSTER_CONTAINER_CONTEXT
                 value: '{"k8s":{"run_k8s_config":{"pod_spec_config":{"nodeSelector":{"some-label":"some-value"}}}}}'
```
