### ISSUE TITLE
Cannot reference same Dagster Asset Key in two DBT Sources

### ISSUE THREAD

**Issue by misa-nogly-aleksic** [dagster-io/dagster#19701]
### Dagster version

1.6.4

### What's the issue?

`dagster-dbt` version `0.22.4`

In my project, I have a Dagster asset, e.g. `my_asset`, that is materialized as a set of database tables: `my_table_1`, `my_table_2`, related by a foreign key.
These tables are then used downstream as DBT sources.

My `sources.yml` file then looks like this:
```
...
  tables:
  -name: my_table_1 
   identifier: my_table_1
   meta:
      dagster:
        asset_key:
        - my_asset
    
  -name: my_table_2
   identifier: my_table_2
   meta:
      dagster:
        asset_key:
        - my_asset
...
``` 

Starting with `dagster-dbt` version `0.22.4`, I get the following error:

> dagster._core.errors.DagsterInvalidDefinitionError: The following dbt resources are configured with identical Dagster asset keys. Please ensure that each dbt resource generates a unique Dagster asset key. See the reference for configuring Dagster asset keys for your dbt project: https://docs.dagster.io/integrations/dbt/reference#customizing-asset-keys.

### What did you expect to happen?

With `dagster-dbt` version `0.22.1` I did not have any errors and I could observe the correct lineage in the asset view.

This PR introduced the above error message: https://github.com/dagster-io/dagster/pull/19603 
Perhaps it is also the cause of this issue.
It was meant to fix this issue: https://github.com/dagster-io/dagster/issues/15160. However said issue relates to a situation where a **seed** and a **source** reference the same asset key, not two sources.

I think it's a fair usecase to have **one** asset be materialized as multiple normalized tables and then to join these tables (as sources) in dbt models. But I'm happy to learn if there is a better practice out there. 🙏 

### Deployment type

Dagster Cloud

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
