### ISSUE TITLE
Simplify user-facing deployment configuration

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#1973]
Right now we ask users to write something like:

```
    event_log_storage:
        module: dagster_postgres.event_log
        class: PostgresEventLogStorage
        config:
            postgres_url: "postgresql://{username}:{password}@{host}:5432/{database}"
```
in their `dagster.yaml` - and we require this for `local_artifact_storage`, `run_storage`, `event_log_storage`, and `compute_logs`. Then separately we have pipeline-specific configs like:

```
    execution:
      multiprocess:
        max_concurrent: 0
    storage:
      filesystem:
```

As a new user I can imagine that this set of storage configs would be pretty confusing when setting up a deployment. 

A proposal:

```
# Template for dagster.yaml 
storage:
  system:
    backend: postgres
    config:
  logs:
    backend: filesystem
    config:
  intermediates:
    backend: gcs
    config:

execution:
  multiprocess:
    max_concurrent: 0
```

Then, any pipeline can provide storage settings to override the base settings defined in `dagster.yaml` for execution or intermediates storage.

Not tied to any of the specifics, but it would be nice to simplify here and provide the default+override semantics
