### ISSUE TITLE
Can't swap storage backend on airline demo

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#1975]
Repro:

use `local_fast` preset on airline demo ingest pipeline. Add:

```
storage:
  s3:
    config:
      s3_bucket: dagster-scratch-80542c2
```

Then get:

![image](https://user-images.githubusercontent.com/609349/70572286-5bd35200-1b54-11ea-9ee9-e145f9866eb8.png)
