### ISSUE TITLE
Debug issues with buildkite networking for dagster-celery tests

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1978]
see: #1791

**Comment by mgasner** [comment]
crucial thing here is going to be to add a key to the buildkite cloudformation

```
Parameters:
  KeyName:
    Description: Optional - SSH keypair used to access the buildkite instances, setting this will enable SSH ingress
    Type: String
    Default: ""
```
