### ISSUE TITLE
Ability to declaratively set global concurrency key limits

### ISSUE THREAD

**Issue by gibsondan** [dagster-io/dagster#19793]
### What's the use case?

Right now, setting global concurrency key limits requires either using the dagster CLI or the Dagster UI to set individual keys. The feature request here is to be able to store the keys and limits in a file and declaratively set it via an API command, like you can do with Dagster Cloud deployment settings: https://docs.dagster.io/dagster-cloud/managing-deployments/managing-deployments#configuring-deployment-settings

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by easontm** [comment]
To be honest I was very surprised that this isn't possible in `dagster.yaml`. I expected to be able to do something like
```yaml
concurrency:
  pools:
    default_limit: 10
    declared:
      my_pool: 20
      my_other_pool: 30
```
Almost everything else I've dealt with in Dagster supports declarative configuration, so the fact that pools require performing an action every time you build a new environment (or just run `dagster dev`) is a bit disappointing.

**Comment by VerdantForge** [comment]
Any updates on this feature?
I'm currently configuring these imperatively through our ansible using something like this

```yaml
- name: Configure individual extraction process concurrency limits
  ansible.builtin.shell:
    cmd: docker compose exec -T daemon dagster instance concurrency set {{ item.key }} {{ item.value }}
    chdir: /opt/{{ service_name }}
  loop: "{{ extraction_pool_concurrency_limits }}"
  register: process_concurrency_results
  failed_when: process_concurrency_results.rc != 0
```

with variables like this
```yaml
extraction_pool_concurrency_limits:
  - { key: "pool1", value: 1 }
```

Though this works it's so much dirtier than just templating the `dagster.yaml` file directly
