### ISSUE TITLE
dbt groups do not update in the UI

### ISSUE THREAD

**Issue by malow106** [dagster-io/dagster#19859]
### Dagster version

1.6.3

### What's the issue?

I want to change dbt assets group. 
I updated my `dbt_project.yml` file to create a subgroup in analytics called 'PowerBI' 

from : 
``` yaml 
    DATAMART:
      +schema: datamart
      +materialized: table
      +meta:
        dagster:
          group: "DBT_PUBLISHING"

      analytics:
        +meta:
          dagster:
            group: "BI"
```
to: 
``` yaml 
    DATAMART:
      +schema: datamart
      +materialized: table
      +meta:
        dagster:
          group: "DBT_PUBLISHING"

      analytics:
        +meta:
          dagster:
            group: "BI"
        PowerBI:
          +meta:
            dagster:
              group: "PowerBI"
```

The new group appear in the left side panel but not in the asset graph : 
<img width="1434" alt="image" src="https://github.com/dagster-io/dagster/assets/26186200/5db673b9-240b-488f-ab7d-d1f68003a99e">

To see the PowerBi group in the graph, I have to select on of it's asset in the left sidebar : 
<img width="1369" alt="image" src="https://github.com/dagster-io/dagster/assets/26186200/e7b76ae0-60e3-4f3b-8b2f-7d6347668537">

Edit : also tried to clear cache

### What did you expect to happen?

Show PowerBi group in the graph all the time

### How to reproduce?

/

### Deployment type

Docker Compose

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
