### ISSUE TITLE
Log rolling for compute logs based on size:

### ISSUE THREAD

**Issue by salilsaifuddin** [dagster-io/dagster#19906]
### What's the use case?

We have configured the log rolling retention to purge logs after a certain number of days using the following configuration in the dagster.yaml file. Is there any way to trigger a purge when the log size reaches a specific threshold?.
Is there a way to configure the purging of compute logs based on a predefined period or size?

dagster.yaml file
```
retention:
  schedule:
    purge_after_days: 90
  sensor:
    purge_after_days:
      skipped: 7
      failure: 30
      success: -1
```

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
