### ISSUE TITLE
Place gbfs_repository under test

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2029]
Right now it doesn't load with the error "dagster.core.errors.DagsterInvalidDefinitionError: Detected conflicting solid definitions with the same name "_validate_json_solid""

After changing the repository.yaml to be:

```
repository:
  module: dagster_examples.bay_bikes.gbfs.repository
  # file: repository.py
  fn: gbfs_repository
```

This makes it impossible to refactor apis that this pipeline uses.
