### ISSUE TITLE
multiprocess docs are incorrect

### ISSUE THREAD

**Issue by ddd-bbb** [dagster-io/dagster#2038]
https://dagster.readthedocs.io/en/0.6.6/sections/deploying/deploying.html#execution says config shoudl be
```
execution:
  multiprocess:
    max_concurrent: 4
storage:
  filesystem:
```
but that causes an error. it should actually be

```
execution:
  multiprocess:
    config:
      max_concurrent: 4
storage:
  filesystem:
```
