### ISSUE TITLE
Configuring kubernetes settings on a job through tags not working

### ISSUE THREAD

**Issue by sverbruggen** [dagster-io/dagster#20429]
### Dagster version

1.6.9

### What's the issue?

I'm using tags to configure my job which is supposed to run on k8s. Specifically, I provide some keys under dagster-k8s/config including requests, nodeselector and tolerations. If I use these exact tags on my @assets, the step pods reflect this configuration, however, the exact same tags are ignored if I provide them on the job itself, and so the job run pod is not running on the correct node and does not have the correct cpu/mem reqs.

### What did you expect to happen?

I expected the job _run_ pod to reflect the configuration I provided in the tags, just like the _step_ pods

### How to reproduce?

I am using the following tags:
`{'dagster-k8s/config': {'pod_spec_config': {'tolerations': [{'key': 'agentpool', 'operator': 'Equal', 'value': 'node04', 'effect': 'NoSchedule'}, {'key': 'agentpool', 'operator': 'Equal', 'value': 'node01', 'effect': 'NoSchedule'}, {'key': 'agentpool', 'operator': 'Equal', 'value': 'node05', 'effect': 'NoSchedule'}, {'key': 'agentpool', 'operator': 'Equal', 'value': 'node02', 'effect': 'NoSchedule'}, {'key': 'agentpool', 'operator': 'Equal', 'value': 'node03', 'effect': 'NoSchedule'}], 'affinity': {'node_affinity': {'required_during_scheduling_ignored_during_execution': {'node_selector_terms': [{'match_expressions': [{'key': 'agentpool', 'operator': 'In', 'values': ['node04', 'node01', 'node05', 'node02', 'node03']}]}]}}}}, 'container_config': {'envFrom': [{'secretRef': {'name': 'sp-credentials'}}, {'secretRef': {'name': 'lakefs-credentials'}}], 'resources': {'requests': {'cpu': 4, 'memory': '32G'}, 'limits': {'cpu': 4, 'memory': '32G'}}, 'env': [{'name': 'ON_K8S', 'value': True}, {'name': '_TAGS', 'value': True}]}}}
`
This is how I define a job:
`define_asset_job(
        name="myjob",
        executor_def=k8s_job_executor,
        tags=tags,
        selection=["some_dummy_asset"],
    )`

### Deployment type

Dagster Helm chart

### Deployment details

I used the dagster helm chart to deploy dagster to kubernetes. We wish to run dagster and its job runs on specific nodes, e.g. node01 through node05. Our infra requires us to do this with nodeselector and tolerations configuration on the pod/container

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by gibsondan** [comment]
The configuration there looks correct to me. A couple of follow-up questions:

- is it possible to post a debug file for a run with these tags? You can generate a debug file from this drop-down on the runs page
<img width="426" alt="image" src="https://github.com/dagster-io/dagster/assets/8451211/c010cbf4-6825-4c07-a022-3961f209eed7">

- Can you post the output of "kubectl describe pod <pod name> -o yaml" where the pod name is one of your job pods for this job?

I don't think that PR is related - the tags you describe there should be working.

**Comment by gibsondan** [comment]
I tried creating a run with the tags that you specified and was able to see the configuration being applied in the launched run (excerpt from the `kubectl get pod` command I posted above):

```
  tolerations:
  - effect: NoSchedule
    key: agentpool
    operator: Equal
    value: node04
  - effect: NoSchedule
    key: agentpool
    operator: Equal
    value: node01
  - effect: NoSchedule
    key: agentpool
    operator: Equal
    value: node05
  - effect: NoSchedule
    key: agentpool
    operator: Equal
    value: node02
  - effect: NoSchedule
    key: agentpool
    operator: Equal
    value: node03
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
```

So the first thing that I would check is to verify that those tags are actually getting applied to the run. You can check that from the "View tags" button here: 
<img width="362" alt="image" src="https://github.com/dagster-io/dagster/assets/8451211/aae8a065-91fd-473b-9df8-c05a2d6f47ce">

You should see something like this in the dialog that opens if the tag was applied as expected: 
<img width="713" alt="image" src="https://github.com/dagster-io/dagster/assets/8451211/d38b8e90-a681-47ad-87a4-f569baebdaec">
