### ISSUE TITLE
replication.yaml doesn't get parsed properly when using @sling_assets

### ISSUE THREAD

**Issue by temminks** [dagster-io/dagster#20483]
### Dagster version

1.6.9

### What's the issue?

I created a simple `replication.yaml` following the Description in https://docs.slingdata.io/sling-cli/run/configuration/replication and the docs in https://docs.dagster.io/_apidocs/libraries/dagster-embedded-elt.

```yaml
source: davit
target: transformator_raw

defaults:
  mode: incremental
  update_key: last_updated
  object: "{my_target_schema}.{stream_table}"

streams:
  my_schema.my_table:
    meta:
      dagster:
        description: Ingestion of my_table.
        group: etl_import

env:
  SLING_LOADED_AT_COLUMN: True
  my_target_schema: "${TARGET_SCHEMA}"
  environment: "${DAGSTER_ENVIRONMENT}"
```

I exported the variables `TARGET_SCHEMA` and `DAGSTER_ENVIRONMENT`.

Dagster does not seem to recognise the `object`-key in the `defaults` and when adding `default` to the stream (`my_schema.my_table`), it will run some sanitise-function (although it's probably not `sanitize_stream_name` as I do not get an exception) and replace Sling's syntax for environment variables with underscores.

This is how Dagit displays the asset:

<img width="865" alt="result of above replication.yaml in Dagster" src="https://github.com/dagster-io/dagster/assets/4665646/d2772274-0618-4dd9-b17c-253a51d44708">

As the description and asset group aren't parse either, I suppose there is an issue with how Dagster parses the `replication.yaml`.

### What did you expect to happen?

Sling should parse the `replication.yaml` file completely according to Sling's documentation, should not sanitise sections if that leads to variables being replaced, should parse the `meta` key as documented in Dagster's docs as well as the code itself (`asset_key` is parsed, `group` and `description` are not), and support the Usage of environment variables.

### How to reproduce?

Add above `replication.yaml` to your Dagster project and provide the path to the file in `@sling_assets(replication_config=replication_config)` as `replication_config` and in your `sling.replicate()` function.

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
