### ISSUE TITLE
Add "from git repository" as a valid code location

### ISSUE THREAD

**Issue by mkleinbort-ic** [dagster-io/dagster#21105]
### What's the use case?

As far as I know, `dagster` only supports python modules and files as "code locations"

I think there are a lot of workflows that would be enabled by supporting git repositories as valid code locations.

In particular, a team could just merge code into main and the "reload code location" action in Dagster (I envision this as a `git pull`) would deploy these changes.

### Ideas of implementation

In the spirit of https://docs.dagster.io/concepts/code-locations

```yaml
locations:
  - location_name: my-code-location-from-file
    code_source:
      python_file: my_file.py
      
  - location_name: my-code-location-from-module
    code_source:
      module_name: my_module_name

  - location_name: my-code-location-from-repo
    code_source:
      git_remote: https://github.com/dagster-io/project-dagster-university.git
```

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
