### ISSUE TITLE
materialize dagstermill notebooks in GCS

### ISSUE THREAD

**Issue by zzztimbo** [dagster-io/dagster#2110]
I've set up storing intermediates in google storage. 

I'd like to be able to have dagstermill jupyter notebooks materialize in google storage as well. My expectation is that setting:

```
storage:
  gcs:
    config:
       gcs_bucket: my-bucket
       gcs_prefix: dagster-storage
```

would enable me to do this more or less automatically.
