### ISSUE TITLE
Really slow Embedded ELT (Sling) incremental update

### ISSUE THREAD

**Issue by morindo** [dagster-io/dagster#21486]
### Dagster version

1.7.2

### What's the issue?

I'm using Dagster Embedded ELT (Sling) to import raw data (MSSQL) into our data warehouse database (MSSQL). The procress of importing data is working but it take a long long time to complete (hours). But, when I run the same update with Sling command line `sling run -r sling_replication.yaml` it take only 15 seconds. Is there something I'm missing in Dagster Embedded ELT configuration?

Dagster Sling resource configuration
```python
from dagster import (
    Definitions,
    EnvVar,
    load_assets_from_package_module,
)

from dagster_embedded_elt.sling.resources import (
    SlingConnectionResource,
    SlingResource,
)

from . import assets

from .utils.constants import dbt_resource

sling_resource = SlingResource(
    connections=[
        # Using a connection string from an environment variable
        SlingConnectionResource(
            name="magma",
            type="sqlserver",
            host=EnvVar("MAGMA_MSSQL_HOST"),
            port=EnvVar("MAGMA_MSSQL_PORT"),
            database=EnvVar("MAGMA_MSSQL_DATABASE"),
            schema="dbo",
            user=EnvVar("MAGMA_MSSQL_USER"),
            password=EnvVar("MAGMA_MSSQL_PASSWORD"),
            encrypt=True,
            trust_server_certificate=True,
        ),
        # Using a hard-coded connection string
        SlingConnectionResource(
            name="magma_dw",
            type="sqlserver",
            host=EnvVar("MAGMA_DW_MSSQL_HOST"),
            port=EnvVar("MAGMA_DW_MSSQL_PORT"),
            database=EnvVar("MAGMA_DW_MSSQL_DATABASE"),
            schema="dbo",
            user=EnvVar("MAGMA_DW_MSSQL_USER"),
            password=EnvVar("MAGMA_DW_MSSQL_PASSWORD"),
            encrypt=True,
            trust_server_certificate=True,
        ),
    ]
)

resources = {
    "sling": sling_resource,
    "dbt": dbt_resource,
}

defs = Definitions(
    assets=load_assets_from_package_module(assets),
    resources=resources,
)
```

```powershell
C:\dagster\my_dagster_project>sling run -r sling_replication.yaml
```

```yaml
source: magma
target: magma_dw

defaults:
  mode: full-refresh
  object: dbo.{stream_table}_raw
  primary_key: [id]
  source_options:
    empty_as_null: false

streams:
  dbo.biz_cpt_inflow:
    mode: incremental
    primary_key: [id]
    update_key: createdonutc
    select: [id, depositslipid, totalamount, status, createdonutc]
    object: dbo.biz_cpt_inflow_raw
    meta:
      dagster:
        asset_key: magma_replica.biz_cpt_inflow_raw

env:
  # adds the _sling_loaded_at timestamp column
  SLING_LOADED_AT_COLUMN: true
```

### How to reproduce?

Create a basic Sling yaml with incremental update. Run from command line and Embedded ELT code and compare performance.

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
