### ISSUE TITLE
[dagster-k8s] Support external PG in Helm chart

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#2193]
Right now the Helm chart only supports deploying PG itself; we should support connecting to an external instance

**Comment by alangenfeld** [comment]
You can accomplish this today with helm values like:
```
postgresql:
  enabled: false   # dont deploy one for me
  postgresHost: foo.bar.com # point at this one
  service:
    port: 5432
  postgresqlDatabase: dagster
  postgresqlUsername: postgres
  postgresqlPassword: oreos123
```
