### ISSUE TITLE
DBT selector yaml support in build_dbt_asset_selection

### ISSUE THREAD

**Issue by dorothychen** [dagster-io/dagster#22252]
### What's the use case?

DBT has a powerful feature to select models [via yaml configuration](https://docs.getdbt.com/reference/node-selection/yaml-selectors), where the functionality afforded by yaml is a superset of what is possible with regular string CLI params. It's especially useful to chain together `selector` definitions, doing something like 

```
- name: exclude_from_main
   definition:
      method: tag
      value: exclude_from_main

- name: finance_models
   definition:
      method: tag
      value: finance
      exclude:
          - union: 
             - method: selector
                value: exclude_from_main
```

It would be great to bring this to dagster's DBT utilities like `build_dbt_asset_selection`. 

The only workaround today I can think of is using the CLI directly to run models, instead of treating jobs as materializing assets. However, this isn't great either because we lose out on Dagster functionality like rerun from failure.

### Additional information

For now, we're writing our own parsing functions, limited to the yaml fields most used.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
