### ISSUE TITLE
interaction of system storage config with instance can be very confusing

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#2259]
system_storage.py l. 59 et seq

if you have config like

```
storage:
  filesystem:
    config:
      base_dir: 'whatever'
```

then you end up with the potentially unexpected `root_for_run_id=lambda _: override_dir`
