### ISSUE TITLE
[composite solid] should be able to specify inputs at the composite level

### ISSUE THREAD

**Issue by alangenfeld** [dagster-io/dagster#2260]
and have the config mapped to the inner solids accordingly.

for the composite 
```
@composite_solid
def outer(mapped):
  inner_1(input_a=mapped)
  inner_2(input_b=mapped)
```

assuming `mapped` is a type with valid `input_hydration_config`, one should be able to do 

```
solids:
  outer:
    inputs:
      mapped: VALUE
```

which currently is not available. 

Note: need to deal with this type of condition:
```
solids:
  outer:
    inputs:
      mapped: VALUE
    solids:
      inner_1:
        inputs:
          input_a: OTHER_VALUE
```
by 
* not allowing inner `input` specification on composite config 
* allowing more specific config to take precedence
* error on any conflict
