### ISSUE TITLE
k8sRunLauncher.runK8sConfig.containerConfig overridden by dagster-user-deployments.deployments[0].resources

### ISSUE THREAD

**Issue by NiallRees** [dagster-io/dagster#22766]
### Dagster version

1.7.11

### What's the issue?

I was previously on Dagster 1.6.6. Since upgrading, it would appear that my `k8sRunLauncher.runK8sConfig.containerConfig` is being overridden by `dagster-user-deployments.deployments[0].resources`.

We set memory to 3Gi for the k8sRunLauncher. On 1.6.6, this correctly applies to K8s jobs created by Dagster.
```
  ####################################################################################################
  # Run Launcher: Configuration for run launcher
  ####################################################################################################
  runLauncher:
    # Type can be one of [K8sRunLauncher, CeleryK8sRunLauncher, CustomRunLauncher]
    type: K8sRunLauncher

    config:
      k8sRunLauncher:
        runK8sConfig:
          podTemplateSpecMetadata:
            annotations:
              cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
          containerConfig:
            resources:
              requests:
                cpu: 1
                memory: 3Gi
```

In 1.7.11, this no longer works, and we instead see job resources to be those set for the `dagster-user-deployments`: 
```
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
        nodeSelector: {}
        affinity: {}
        tolerations: []
        podSecurityContext: {}
        securityContext: {}
        resources:
          requests:
            cpu: 750m
            memory: 1Gi
```

### How to reproduce?

Launch dagster with the helm chart. Attempt to set the resources for the `k8sRunLauncher.runK8sConfig.containerConfig`.

### Deployment type

Dagster Helm chart

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
