### ISSUE TITLE
Dagster DBT doesn't load list of tags from dbt into dagster

### ISSUE THREAD

**Issue by SeppBerkner** [dagster-io/dagster#22770]
### Dagster version

dagster, version 1.7.0

### What's the issue?

Using the tags in dbt as list within the `config` setting in dbt only loads the last item to dagster.

dbt yaml file:

```yaml
version: 2

models:
  - name: my_model
    config:
        tags: ['category=category 1','category=category 2']
        meta:
          dagster:
            group: "my_group"
```

In Dagit only `category: category 2` appears in the asset catalog and additionally it is only possible to filter by this tag in the lineage graph.

### What did you expect to happen?

All items of the list in the tags setting in dbt are read into dagster.

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
