### ISSUE TITLE
Automaterialization with cpu/memory requirements per asset

### ISSUE THREAD

**Issue by HynekBlaha** [dagster-io/dagster#22865]
### What's the use case?

Auto-materialization is really cool! Unfortunately, there is a small, but very important fact preventing us from using it.
Jobs spawned for auto-materialization don't respect CPU/MEM resources defined in asset.op_tags.
We have a lot of assets with different memory requirements (up to 50GB) so global setting doesn't work for us.
```
additionalInstanceConfig:
  auto_materialize:
    run_tags:
      dagster-k8s/config: {"container_config": {"resources": {"requests": {"cpu": "1000m", "memory": "512Mi"}}}}
```    

The important part in [this example](https://github.com/dagster-io/dagster/discussions/14544) is:
```Note that setting the dagster-k8s/config tag on an asset will only work if you're using the k8s_job_executor that materializes each asset in its own Kubernetes pod. Setting dagster-k8s/config on a job will only work if you're using the K8sRunLauncher that runs each job in its own pod.```

We use [k8sRunLauncher](https://github.com/dagster-io/dagster/blob/master/helm/dagster/values.yaml#L468) as default launcher and k8s_job_executor can be defined only for job, not asset. :(

### Additional information

Based on: https://dagster.slack.com/archives/C01U5LFUZJS/p1720182445065919

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
