### ISSUE TITLE
GRPC Servers Empty Code Location without Warning

### ISSUE THREAD

**Issue by reinthal** [dagster-io/dagster#23606]
### Dagster version

1.8.0

### What's the issue?

Following dagster command was invoked 

```dagster api grpc -h 0.0.0.0 -p 4000```

without a valid code location in the default path.

### What did you expect to happen?

I expected the logs to warn that an empty code location was loaded

### How to reproduce?

Use the following `pyproject.toml`

```toml
[tool.poetry]
name = "testdagster"
version = "0.1.0"
description = ""
authors = ["Alexander Reinthal <email@reinthal.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.4"
dagster = "^1.8.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

then

```
poetry run dagster api grpc -h 0.0.0.0 -p 4000
2024-08-13 13:59:17 +0200 - dagster.code_server - INFO - Starting Dagster code server on port 4000 in process 59949
2024-08-13 13:59:17 +0200 - dagster.code_server - INFO - Started Dagster code server on port 4000 in process 59949
```

yields no warning

### Deployment type

Dagster Helm chart

### Additional information

This bug was discovered when troubleshooting an incorrectly configured deployment that lacked the required code location modele for a k8s deployment.

Correct Dockerfile` CMD invocation should have  the `-m dagster_project` flag. However, the silent fail required troubleshooting and testing.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
