### ISSUE TITLE
Dbt assets downstream of Sling assets are skipping due to non-existent skipped dependency 

### ISSUE THREAD

**Issue by jpentland89** [dagster-io/dagster#23859]
### Dagster version

dagster, version 1.8.3

### What's the issue?

I have a sling replication defined for two assets upstream of dbt assets constructed using `@dbt_assets`. The sling and dbt assets are grouped into a job. When running the job, the sling replication successfully materializes the assets, but the downstream dbt assets are skipped due to a skipped dependency that doesn't seem to exist in the graph. This started after updating to dagster 1.8.1 and has persisted to 1.8.3.

I have the following replication configuration

```python
replication_config = {
    "source": "JRWPOSTGRES",
    "target": "DATAWAREHOUSE",
    "defaults": {"mode": "truncate"},
    "streams": {
        "quality.final_audit_inspections": {
            "object": "raw.jrw_postgres__final_audit_inspections",
        },
        "quality.final_audit_inspection_approvals": {
            "object": "raw.jrw_postgres__final_audit_inspection_approvals",
        },
    },
}
```
A simple translator to set the asset group and auto materialize policies

```python
class JRWPostgresSlingTranslator(DagsterSlingTranslator):
    @classmethod
    def get_auto_materialize_policy(cls, stream_definition: Mapping[str, Any]) -> AutoMaterializePolicy | None:
        return AutoMaterializePolicy.eager()

    @classmethod
    def get_group_name(cls, stream_definition: Mapping[str, Any]) -> str | None:
        return "jrw_postgres_raw"
```

and sling assets defined using `@sling_assets`

```python
@sling_assets(replication_config=replication_config, dagster_sling_translator=JRWPostgresSlingTranslator())
def jrw_postgres_assets(context, jrw_postgres_sling: SlingResource):
    yield from jrw_postgres_sling.replicate(
        context=context,
        replication_config=replication_config,
        dagster_sling_translator=JRWPostgresSlingTranslator(),
    )
    for row in jrw_postgres_sling.stream_raw_logs():
        context.log.info(row)
``` 
 I've configured my dbt sources as follows
```yml
sources:
  - name: jrw_postgres
    schema: raw
    tables:
      - name: final_audit_inspections
        identifier: jrw_postgres__final_audit_inspections
        meta:
          dagster:
            asset_key: [target, raw, jrw_postgres__final_audit_inspections]
      - name: final_audit_inspection_approvals
        identifier: jrw_postgres__final_audit_inspection_approvals
        meta:
          dagster:
            asset_key: [target, raw, jrw_postgres__final_audit_inspection_approvals]
```

When running the job, this is the output I get

![image](https://github.com/user-attachments/assets/f70a453c-ab2d-48fa-8d75-b9009b78ce75)

Dagster is skipping the dbt run because `jrw_postgres_assets.target__raw__jrw_postgres__final_audit_inspection_approvals` was skipped, but this asset doesn't exist as far as I'm aware. It seems to be some type of issue with translating the Sling assets into dependencies that dagster can map onto the dbt assets, but I don't know enough about either integration to know what's actually going on here. 

### What did you expect to happen?

Expected dbt assets to materialize after the upstream replication succeeded. 

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
