### ISSUE TITLE
Disable `Launch` button when run launcher is configured against itself

### ISSUE THREAD

**Issue by prha** [dagster-io/dagster#2387]
dagster.yaml:
```
run_launcher:
  module: dagster_graphql.launcher
  class: RemoteDagitRunLauncher
  config:
    address: http://localhost:3333
```

Run dagit:
`dagit -p 3333`

Clicking `Launch` will cause the request to hang because:
https://stackoverflow.com/questions/33353192/flask-hangs-when-sending-a-post-request-to-itself
