### ISSUE TITLE
Dagster dbt doesn't work correctly when using `tag` in `select`

### ISSUE THREAD

**Issue by shorie000** [dagster-io/dagster#24218]
### Dagster version

dagster, version 1!0+dev (https://github.com/dagster-io/dagster/tree/5fd25f01d6e325b29688c8d7919377b955779d44)

### What's the issue?

When setting `tag:test` to the `select` argument,  empty asset is created.
```python
    @dbt_assets(
        manifest=test_dbt_unit_tests_manifest,
        select="tag:test",
    )
    def my_dbt_assets(context: AssetExecutionContext, dbt: DbtCliResource):
        yield from dbt.cli(["build"], context=context).stream()
```

### What did you expect to happen?

Assets create correctly.

### How to reproduce?

Run this code in `python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_decorator.py::test_dbt_with_unit_tests.py`

Fails to the second test.

In dbt_project.yml of [test_dagster_dbt_unit_tests](https://github.com/dagster-io/dagster/blob/4d28ef2246f0d99b567aead6e5cb0651b593dc08/python_modules/libraries/dagster-dbt/dagster_dbt_tests/dbt_projects/test_dagster_dbt_unit_tests/dbt_project.yml#L31-L32),
`tags:test` is attached to all models and all seeds so it is problem that `my_dbt_assets.keys` is empty. 

```python
@pytest.mark.skipif(
    version.parse(dbt_version) < version.parse("1.8.0"),
    reason="dbt unit test support is only available in `dbt-core>=1.8.0`",
)
@pytest.mark.parametrize(
    ["select", "asset_keys"],
    [
        (
            "fqn:*",
            {
                AssetKey(["customers"]),
                AssetKey(["orders"]),
                AssetKey(["raw_orders"]),
                AssetKey(["raw_payments"]),
                AssetKey(["raw_customers"]),
                AssetKey(["stg_customers"]),
                AssetKey(["stg_payments"]),
                AssetKey(["stg_orders"]),
            },
        ),
        (
            "tag:test",
            {
                AssetKey(["customers"]),
                AssetKey(["orders"]),
                AssetKey(["raw_orders"]),
                AssetKey(["raw_payments"]),
                AssetKey(["raw_customers"]),
                AssetKey(["stg_customers"]),
                AssetKey(["stg_payments"]),
                AssetKey(["stg_orders"]),
            },
        ),
    ],
)
def test_dbt_with_unit_tests(
    test_dbt_unit_tests_manifest: Dict[str, Any], select: str, asset_keys: set[AssetKey]
) -> None:
    @dbt_assets(
        manifest=test_dbt_unit_tests_manifest,
        select=select,
    )
    def my_dbt_assets(context: AssetExecutionContext, dbt: DbtCliResource):
        yield from dbt.cli(["build"], context=context).stream()

    result = materialize(
        [my_dbt_assets],
        resources={"dbt": DbtCliResource(project_dir=os.fspath(test_dbt_unit_tests_path))},
    )
    assert my_dbt_assets.keys == asset_keys
    assert result.success
```

<img width="1305" alt="image" src="https://github.com/user-attachments/assets/b1ef5f0e-f040-44c0-96f3-04a3067575c5">

```
models:
  jaffle_shop:
    +tags: test
    materialized: table
    staging:
      materialized: view

seeds:
  jaffle_shop:
    +tags: test
```

### Deployment type

Local

### Deployment details

Run `make dev_install`.
Using pytest

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by shorie000** [comment]
When I set `tags` in this way, it works well.

```sql
{{ config(
    tags="test",
) }}
with source as (

    {#-
    Normally we would select from the table here, but we are using seeds to load
    our data in this project
    #}
    select * from {{ ref('raw_customers') }}

),

renamed as (

    select
        id as customer_id,
        first_name,
        last_name

    from source

)

select * from renamed
```

**Comment by shorie000** [comment]
When I set `tags` in this way, it doesn't work well.

```
models:
  - name: stg_customers
    tags: ["stg_customers_tag"]
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
```

https://github.com/dagster-io/dagster/blob/edc454f7690e8f5ca3fdbd0061a2b5133c3edff2/python_modules/libraries/dagster-dbt/dagster_dbt_tests/dbt_projects/jaffle_shop/models/staging/schema.yml#L1-L2

**Comment by shorie000** [comment]
This is not a bug. There is an error in how I configure the tags.”

I should have set config like this.
```
models:
  - name: stg_customers
    config:
        tags: ["test"]
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
```
