### ISSUE TITLE
Allow role to create and delete deployments and service

### ISSUE THREAD

**Issue by michaelromagne** [dagster-io/dagster#24256]
### What's the use case?

I need to compute insights on a given dataframe using a Machine Learning model in my Dagster job. Dagster is deployed using Helm.

I want to launch a deployment with N replicas and a service **from the job** using kubernetes client, for the time of the job. However, the role used by Dagster does not have the permission to create/delete Deployments and Services : https://github.com/dagster-io/dagster/blob/master/helm/dagster/templates/role.yaml#L12-L27 

### Ideas of implementation

If that makes sense and does not pose a big security issue, just add services and deployments in the role.yaml template as an option or by default

`role.yaml` :

```
{{- if .Values.rbacEnabled }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "dagster.fullname" . }}-role
  labels:
    app: {{ template "dagster.name" . }}
    chart: {{ template "dagster.chart" .  }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"

# Allow the Dagster service account to read and write Kubernetes jobs, deployments, pods, events, services, and deployments.
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs/status"]
    verbs: ["get", "watch", "list"]
  # Core API group for pods and events
  - apiGroups: [""]
    resources: ["pods", "events", "services"]
    verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]
  - apiGroups: [""]
    resources: ["pods/log", "pods/status"]
    verbs: ["get", "watch", "list"]
  # Apps API group for deployments
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]
{{- end }}

```

### Additional information

I tried to use sidecar containers next to my op main container but it does not work : https://github.com/dagster-io/dagster/issues/23497

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
