### ISSUE TITLE
endpoint_url for S3ComputeLogManager

### ISSUE THREAD

**Issue by mrdrprofuroboros** [dagster-io/dagster#2438]
I'm trying to run dagster with self-hosted s3-like storage - minio
and I've managed to configure the intermediate storage for it (though there is a lack of documentation on providing credentials for s3 api login  - it would be great if you add a note on that - https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html
just passing them through env works)

But still I couldn't find a way to overwrite endpoint_url in S3ComputeLogManager in dagster.yaml. Am I missing something?

**Comment by prha** [comment]
The `endpoint_url` is now configurable for the compute log manager config starting in release `0.7.12`: 
```
compute_logs:
  module: dagster_aws.s3.compute_log_manager
  class: S3ComputeLogManager
  config:
    bucket: "my-bucket"
    prefix: "my-custom-prefix"
    endpoint_url: "http://localhost:9000"
```
