### ISSUE TITLE
compatibility with `uv init`

### ISSUE THREAD

**Issue by dbrtly** [dagster-io/dagster#24878]
### What's the use case?

Dagster should play nicely with uv to maximise reach with new developers.
- The "Getting Started" tutorial should leverage the `dagster project scaffold` command.
- The current pyproject.toml file is a subset of the minimum content that uv requires.

These instructions should succeed:

```bash
# create a dagster project using the scaffold tool
uvx dagster project scaffold --name dagster-quickstart
cd dagster-quickstart
uv add dagster dagster-webserver pandas

# create example data
mkdir -p data
cat << EOF > data/sample_data.csv
id,name,age,city
1,Alice,28,New York
2,Bob,35,San Francisco
3,Charlie,42,Chicago
4,Diana,31,Los Angeles

EOF

# create a dagster asset
cat << EOF > quickstart/assets.py
import dagster as dg
import pandas as pd


@dg.asset
def processed_data():
    ## Read data from the CSV
    df = pd.read_csv("data/sample_data.csv")

    ## Add an age_group column based on the value of age
    df["age_group"] = pd.cut(
        df["age"], bins=[0, 30, 40, 100], labels=["Young", "Middle", "Senior"]
    )

    ## Save processed data
    df.to_csv("data/processed_data.csv", index=False)
    return "Data loaded successfully"


## For Dagster to manage the execution and dependencies of assets,
## pass the assets of the pipeline to the Dagster Definitions object
defs = dg.Definitions(assets=[processed_data])

EOF
```

open a new terminal:
```
# start dagster web server to visually observe the asset
uv run dagster dev --python-file dagster_quickstart/assets.py 

```

Open web browser at http://127.0.0.1:3000
Observe a detail about asset and project state before example asset has been materialized.

Return to original terminal:

```bash
# materialize the dagster asset
uv run dagster asset materialize \
  --python-file dg_quickstart/assets.py \
  --select processed_data

```
Switch back to browser and observe asset/project state after asset has been materialized.

### Ideas of implementation

The uvx command runs Python libraries as tools similar to pipx. This simplifies the user experience. You don't have to understand how to install Python, upgrade pip or activate the virtual environment.

The command: `uvx dagster project scaffold --name dagster-quickstart` runs the command `dagster project scaffold --name dagster-quickstart` in a Python virtual environment containing the dagster package. 

This command generates a default pyproject.toml that is incomplete for uv.

setup.py looks like this:
```python
from setuptools import find_packages, setup

setup(
    name="dg_quickstart",
    packages=find_packages(exclude=["dg_quickstart_tests"]),
    install_requires=[
        "dagster",
        "dagster-cloud"
    ],
    extras_require={"dev": ["dagster-webserver", "pytest"]},
)

``` 
And the pyproject.toml file should be extended from this:

```toml
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.dagster]
module_name = "dagster_quickstart.definitions"
code_location_name = "dagster_quickstart"
```

pyproject.toml should also include the content at setup.install_requires and setup.extras_require like this:

```toml
[project]
name = "dagster_quickstart"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8,<3.12"
dependencies = [
    "dagster",
    "dagster-cloud",
    "pandas",
]
[tool.uv]
dev-dependencies = [
    "dagster-webserver", 
    "pytest",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.dagster]
module_name = "dagster_quickstart.definitions"
code_location_name = "dagster_quickstart"

```

### Additional information

I can't figure out where the template for the pyproject.toml lives in the codebase.
If you point me in the right direction, I will add it as many of the examples as you let me.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
