### ISSUE TITLE
Update deployment docs on dagster.yaml to show how to handle secrets

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#2489]
Right now this https://docs.dagster.io/docs/deploying/instance shows creds hard-coded—we should demo how to use env vars for PG secrets like:

```
run_storage:
  module: dagster_postgres.run_storage
  class: PostgresRunStorage
  config:
    postgres_db:
      username:
        env: DAGSTER_PG_USERNAME
      password:
        env: DAGSTER_PG_PASSWORD
      hostname:
        env: DAGSTER_PG_HOST
      db_name: 
        env: DAGSTER_PG_DB
      port: 5432
```
