### ISSUE TITLE
Better config for jobs with sidecar containers and DynamicOut

### ISSUE THREAD

**Issue by michaelromagne** [dagster-io/dagster#25308]
### What's the use case?

I have a job with a dynamic graph, using DynamicOut.

The ops are configured with Pydantic configs, allowing us to parametrize the ops in the launchpad.

In each Op, we have a sidecar container running alongside the main step container.

This sidecar container will run a ML model sever, to compute insights on some data. We are interested in changing the image used in the sidecar container in the launchpad at each job, using the pydantic config.

Here is an example of the config with only 2 ops in parallel (with the dynamic graph). As you can see, the configuration is currently not convenient as we have to replicate the per_step_k8s_config element for each op in our graph:

```
execution:
  config:
    per_step_k8s_config:
      compute_ml_enhancements[chunk_0]:
        pod_spec_config:
          init_containers:
          - image: 513715405986.dkr.ecr.us-west-2.amazonaws.com/ml-detector/ml-secret-engine/app:0.29.2
            name: model-server
            ports:
            - container_port: 3000
              host_port: 3000
              protocol: TCP
            resources:
              requests:
                cpu: '3'
                memory: 3Gi
            restartPolicy: Always
      compute_ml_enhancements[chunk_1]:
        pod_spec_config:
          init_containers:
          - image: 513715405986.dkr.ecr.us-west-2.amazonaws.com/ml-detector/ml-secret-engine/app:0.29.2
            name: model-server
            ports:
            - container_port: 3000
              host_port: 3000
              protocol: TCP
            resources:
              requests:
                cpu: '3'
                memory: 3Gi
            restartPolicy: Always
            
ops:
  fetch_and_chunk_data:
    config:
      account_ids:
      - <account_id>
      number_of_model_servers: 2
      number_of_rows: 100
resources:
  io_manager:
    config:
      s3_bucket: <s3>

```

### Ideas of implementation

I expect to only give the dynamic op config once, like below, and the same k8s config is used for each op : 

```
execution:
  config:
    per_step_k8s_config:
      compute_ml_enhancements:
        pod_spec_config:
          init_containers:
          - image: 513715405986.dkr.ecr.us-west-2.amazonaws.com/ml-detector/ml-secret-engine/app:0.29.2
            name: model-server
            ports:
            - container_port: 3000
              host_port: 3000
              protocol: TCP
            resources:
              requests:
                cpu: '3'
                memory: 3Gi
            restartPolicy: Always
            
ops:
  fetch_and_chunk_data:
    config:
      account_ids:
      - <account_id>
      number_of_model_servers: 2
      number_of_rows: 100
resources:
  io_manager:
    config:
      s3_bucket: <s3>

```

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by michaelromagne** [comment]
We switched to K8SRunLauncher, that allows us to have the same sidecar container for all pods. This is still not ideal but better than above problem.

**Comment by msavtchouk-pf** [comment]
This is a highly desirable feature from our side as well. In our use case we have a Dynamic graph and require to configure resources per-op at job launch time

**Comment by zacps** [comment]
I've also run into this, and I'm happy to implement a fix (along with https://github.com/dagster-io/dagster/issues/8331).

I'd suggest we do the following:

1. Leave `per_step_k8s_config` as it is and deprecate it
2. Add `per_step_execution_config` with the following schema:

```yaml
per_step_execution_config:
   all_executors:
       - op: my_op_name
         config:
             ... # all previously allowed op configuration
       - op: my_op_name
         graph: my_root_graph.my_sub_graph
         config:
             ... # all previously allowed op configuration
       - op: my_op_name
         graph: my_root_graph.my_sub_graph
         instance: 5 # target a specific invocation of an op
         config:
             ... # all previously allowed op configuration
   kubernetes:
       - op: ...
         ...
   docker:
       - op: ...
         ...
```

With the precedence order:

1. Executor-specific graph-specific instance-specific
2. Executor-specific graph-specific
3. Executor-specific instance-specific FORBIDDEN
4. Executor-specific
5. Executor-general graph-specific instance-specific
6. Executor-general instance-specific FORBIDDEN
7. Executor-general graph-specific
8. Executor-general

Generally I think dagster should move away from so much being stored in the op name strings but that's a wider refactor than I have appetite for. I'll probably wait until a maintainer ways in before I spend time implementing anything.
