### ISSUE TITLE
Allow to read StringSource values from files

### ISSUE THREAD

**Issue by Radiergummi** [dagster-io/dagster#25804]
### What's the use case?

I'd like to be able to read Dagster configuration values from files, in addition to environment variables.  
For example, to configure the database password for a Dagster instance from the environment variable `DAGSTER_POSTGRES_PASSWORD`, I'll use this:
```yaml
  config:
    postgres_db:
      password:
        env: DAGSTER_POSTGRES_PASSWORD
```

This requires the Postgres password—a possibly sensitive value—to be exposed in the process environment, where it is readable by other applications, might be included in log files, and other unintended consequences.

Instead, I'd like to propose support for secret files, as popular with Docker and Kubernetes, and used by a lot of other applications. This could look like so:
```yaml
  config:
    postgres_db:
      password:
        file: /run/secrets/postgres_password
```

That way, we could mount the secret as part of a compose specification, for example:
```yaml
services:
  daemon:
    image: my-dagster:latest
    secrets:
      - postgres_password

secrets:
  postgres_password:
    env: POSTGRES_PASSWORD
```

This would simplify integration in common secret management solutions a lot.

### Ideas of implementation

The `StringSource` class would have to be extended to support reading values from a file source. I haven't looked at the implementation, but would be willing to provide a PR—it can't be that hard™

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
