### ISSUE TITLE
`automation_condition` not supported in dbt metadata tags

### ISSUE THREAD

**Issue by jonathanneo** [dagster-io/dagster#25866]
### What's the issue?

I want to be able to specify `automation_condition` in dbt projects via the dbt model's SQL file, or the dbt YML config file. 

For example: 

```yml 
models:
  +meta:
    dagster:
      group: dbt_analytics
      automation_condition:
        type: eager
```

This was previously possible with `auto_materialize_policy` (before dagster v1.9): 

```yml
models:
  +meta:
    dagster:
      group: dbt_reporting
      auto_materialize_policy:
        type: "eager"
```

In addition, I want the automation_condition types specified in the [docs](https://docs.dagster.io/concepts/automation/declarative-automation#automation-conditions) to be reflected in the options, for example: 

```yml
models:
  +meta:
    dagster:
      group: dbt_analytics
      automation_condition:
        type: "on_cron"
        cron_schedule: "* * * * *"
```

### Dagster version

dagster, version 1.9.0

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
By submitting this issue, you agree to follow Dagster's [Code of Conduct](https://github.com/dagster-io/dagster/blob/master/.github/CODE_OF_CONDUCT.md).
