### ISSUE TITLE
Not possible to use postgres image config in the helm chart

### ISSUE THREAD

**Issue by psarka** [dagster-io/dagster#25898]
### What's the issue?

There is section in the dagster helm chart values to configure the postgresql:

```
postgresql:
  # set postgresql.enabled to be false to disable deploy of a PostgreSQL database and use an
  # existing external PostgreSQL database
  enabled: true

  # Used by init container to check that db is running. (Even if enabled:false)
  image:
    repository: "library/postgres"
    tag: "14.6"
    pullPolicy: IfNotPresent
```

This image is used both for webserver / daemon init images as well as for the database via bitnami helm. It is not possible to change that value to some other registry.

And this impossibility arises from the fact that in dagster helm repository and tag are composed to url as `{repository}:{tag}`. While in bitnami they are composed to url as `docker.io/{repository}:{tag}`.

It should be able to disable that `docker.io` prefix by setting image.registry to null and global.imageRegistry to null, but it does not seem to work.

### What did you expect to happen?

Setting repository + tag should work in postgresql sections like it works in other sections

### Dagster version

dagster 1.7.2

### Deployment type

Dagster Helm chart

### Additional information

There is a ticket with the same issue (I think), closed by the reporter without any solution: https://github.com/dagster-io/dagster/issues/12910

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
By submitting this issue, you agree to follow Dagster's [Code of Conduct](https://github.com/dagster-io/dagster/blob/master/.github/CODE_OF_CONDUCT.md).
