### ISSUE TITLE
helm chart: postgresql toleration/affinity

### ISSUE THREAD

**Issue by fbacker** [dagster-io/dagster#26074]
### What's the use case?

Using helm chart the postgresql is missing the ability to set toleration and affinity

### Ideas of implementation

in values use same syntax as dagsterDaemon

```yaml
dagsterDaemon: # should set postgresql here instead
  affinity: {}
  tolerations: []
```

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
