### ISSUE TITLE
EcsRunLauncher regression - "Could not determine image for run"

### ISSUE THREAD

**Issue by treilly1** [dagster-io/dagster#26138]
### What's the issue?

* detailed outline in dagster slack https://dagster.slack.com/archives/C01U954MEER/p1732566748483749
* Attempting an upgrade to dagster `1.9.2` raises error [here](https://github.com/dagster-io/dagster/blob/94bcd2a42a9f37f65613e21ee8b5704ef94d6204/python_modules/libraries/dagster-aws/dagster_aws/ecs/launcher.py#L490-L491) despite my `dagster.yaml` configuring the run launcher as outlined in [current documentation](https://docs.dagster.io/deployment/guides/aws#launching-runs-in-ecs) 

### What did you expect to happen?

* No breaking `ECSRunLauncher` changes when upgrading. Since underlying image is specified on my ECS task def (and controlled via CICD process), I'd expect dagster to use image defined on task def. 

### How to reproduce?

* For ECS launchers configured like documentation outlines, attempt kicking off a run.
```
run_launcher:
  module: "dagster_aws.ecs"
  class: "EcsRunLauncher"
  config:
    task_definition: "arn:aws:ecs:us-east-1:1234567890:task-definition/my-task-definition:1"
    container_name: "my_container_name"
```

### Dagster version

`1.9.2`

### Deployment type

Other Docker-based deployment

### Deployment details

* All dagster resources are deployed to an ECS cluster

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
By submitting this issue, you agree to follow Dagster's [Code of Conduct](https://github.com/dagster-io/dagster/blob/master/.github/CODE_OF_CONDUCT.md).
