### ISSUE TITLE
Dagtser Database Hostname is not read from environment variable

### ISSUE THREAD

**Issue by Klassen-Olga** [dagster-io/dagster#26322]
### What's the issue?

I am trying to set up an environment variable for the host name of the database und then use it inside dagster.yaml. It doesn't recognise the variable name only for the host, the username, password and database name work just fine.

`WARNING:root:Retrying failed database connection: (psycopg2.OperationalError) could not translate host name "DAGSTER_DB_HOST" to address: Name or service not known`

### What did you expect to happen?

All the environments set in docker-compose.yml are resolved in the application.

### How to reproduce?

docker-compose.yml
```
version: "3.7"

services:
  docker_postgresql:
    image: postgres:11
    container_name: docker_postgresql
    environment:
      POSTGRES_USER: "postgres_user"
      POSTGRES_PASSWORD: "postgres_password"
      POSTGRES_DB: "postgres_db"
    networks:
      - dagster_network


  dagster_pipeline:
    build:
      context: .
      dockerfile: dagster_pipeline/Dockerfile
    container_name: dagster_pipeline
    image: dagster_pipeline_image
    restart: always
    environment:
      DAGSTER_POSTGRES_USER: "postgres_user"
      DAGSTER_POSTGRES_PASSWORD: "postgres_password"
      DAGSTER_POSTGRES_DB: "postgres_db"
      DAGSTER_CURRENT_IMAGE: "dagster_pipeline_image"
      DAGSTER_DBT_PARSE_PROJECT_ON_LOAD: 1
      DAGSTER_DB_HOST: "docker_postgresql"
      AWS_REGION: "eu-central-1"
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
    networks:
      - dagster_network

  webserver:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    entrypoint:
      - dagster-webserver
      - -h
      - "0.0.0.0"
      - -p
      - "3000"
      - -w
      - workspace.yaml
    container_name: webserver
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      DAGSTER_POSTGRES_USER: "postgres_user"
      DAGSTER_POSTGRES_PASSWORD: "postgres_password"
      DAGSTER_POSTGRES_DB: "postgres_db"
      DAGSTER_DBT_PARSE_PROJECT_ON_LOAD: 1
      DAGSTER_DB_HOST: "docker_postgresql"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
    networks:
      - dagster_network
    depends_on:
      - docker_postgresql
      - dagster_pipeline


  deamon:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    entrypoint:
      - dagster-daemon
      - run
    container_name: deamon
    restart: on-failure
    environment:
      DAGSTER_POSTGRES_USER: "postgres_user"
      DAGSTER_POSTGRES_PASSWORD: "postgres_password"
      DAGSTER_POSTGRES_DB: "postgres_db"
      DAGSTER_DBT_PARSE_PROJECT_ON_LOAD: 1
      DAGSTER_DB_HOST: "docker_postgresql"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
    networks:
      - dagster_network
    depends_on:
      - docker_postgresql
      - dagster_pipeline

networks:
  dagster_network:
    driver: bridge
    name: dagster_network
```
dagtser.yaml
```
scheduler:
  module: dagster.core.scheduler
  class: DagsterDaemonScheduler

run_coordinator:
  module: dagster.core.run_coordinator
  class: QueuedRunCoordinator

run_launcher:
  module: dagster_docker
  class: DockerRunLauncher
  config:
    env_vars:
      - DAGSTER_POSTGRES_USER
      - DAGSTER_POSTGRES_PASSWORD
      - DAGSTER_POSTGRES_DB
      - AWS_SESSION_TOKEN
      - AWS_SECRET_ACCESS_KEY
      - AWS_ACCESS_KEY_ID
      - AWS_REGION
      - DAGSTER_DB_HOST
      - DAGSTER_DBT_PARSE_PROJECT_ON_LOAD
    network: dagster_network
    container_kwargs:
      volumes: # Make docker client accessible to any launched containers as well
        - /var/run/docker.sock:/var/run/docker.sock
        - /tmp/io_manager_storage:/tmp/io_manager_storage

run_storage:
  module: dagster_postgres.run_storage
  class: PostgresRunStorage
  config:
    postgres_db:
      hostname: DAGSTER_DB_HOST
      username:
        env: DAGSTER_POSTGRES_USER
      password:
        env: DAGSTER_POSTGRES_PASSWORD
      db_name:
        env: DAGSTER_POSTGRES_DB
      port: 5432

schedule_storage:
  module: dagster_postgres.schedule_storage
  class: PostgresScheduleStorage
  config:
    postgres_db:
      hostname: DAGSTER_DB_HOST
      username:
        env: DAGSTER_POSTGRES_USER
      password:
        env: DAGSTER_POSTGRES_PASSWORD
      db_name:
        env: DAGSTER_POSTGRES_DB
      port: 5432

event_log_storage:
  module: dagster_postgres.event_log
  class: PostgresEventLogStorage
  config:
    postgres_db:
      hostname: DAGSTER_DB_HOST
      username:
        env: DAGSTER_POSTGRES_USER
      password:
        env: DAGSTER_POSTGRES_PASSWORD
      db_name:
        env: DAGSTER_POSTGRES_DB
      port: 5432

```

### Dagster version

1.9.2

### Deployment type

Docker Compose

### Deployment details

**Python version**: 3.12-slim
**Dagster version**: 1.9.2
**Docker Compose version**: v2.23.0-desktop.1

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
By submitting this issue, you agree to follow Dagster's [Code of Conduct](https://github.com/dagster-io/dagster/blob/master/.github/CODE_OF_CONDUCT.md).
