### ISSUE TITLE
Helm Chart - runMonitoring: maxRuntimeSeconds not configurable

### ISSUE THREAD

**Issue by dbrocha** [dagster-io/dagster#26641]
### What's the issue?

I'd like to add a max runtime seconds to my helm chart. Referencing the dagster.yaml config described here: https://docs.dagster.io/deployment/run-monitoring#general-run-timeouts, I added the following to my helm chart -
```
runMonitoring:
    enabled: true
    # Timeout for runs to start (avoids runs hanging in STARTING)
    startTimeoutSeconds: 300
    # Timeout for runs to cancel (avoids runs hanging in CANCELING)
    # cancelTimeoutSeconds: 300
    # How often to check on in progress runs
    pollIntervalSeconds: 120
    maxRuntimeSeconds: 10800
```
This setting does not show in the front end configuration display, however:
```
run_monitoring:
  enabled: true
  start_timeout_seconds: 300
  max_resume_run_attempts: 0
  poll_interval_seconds: 120
  free_slots_after_run_end_seconds: 0
```

### Dagster version

1.9.6

### Deployment type

Dagster Helm chart

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
By submitting this issue, you agree to follow Dagster's [Code of Conduct](https://github.com/dagster-io/dagster/blob/master/.github/CODE_OF_CONDUCT.md).
