### ISSUE TITLE
`poetry install dagster `  error

### ISSUE THREAD

**Issue by kevinfuture** [dagster-io/dagster#26842]
### What's the issue?

python ==3.11.11
poetry=2.0.0
poetry install dagster 
<img width="971" alt="image" src="https://github.com/user-attachments/assets/ebd0403c-e5d8-45fa-9896-792ab53ec1de" />

### Dagster version

>=1.9.3

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by garethbrickman** [comment]
> a possible solution would be to set the `python` property to ">=3.9,<3.13"

That fixed it for me. In my `pyproject.toml`:

```toml
[tool.poetry.dependencies]
python = ">=3.9,<3.13"
dagster = "1.9.3"
```
