### ISSUE TITLE
Dagster OSS `LocalComputeLogManager` support

### ISSUE THREAD

**Issue by mtofano** [dagster-io/dagster#27054]
### What's the use case?

Hi there,

I would like to use the `LocalComputeLogManager` in the Dagster OSS deployment. In the helm chart I do not see this as an available option to choose from based on the commented documentation:

```yaml
####################################################################################################
# Compute Log Manager: Configuration for the compute log manager.
#
# By default, NoOpComputeLogManager is set as a compute log manager. As a result, stdout and stderr
# logs will be unavailable in the Dagster UI. To change this behavior, choose a compute log
# manager with a storage backend to capture and persist stdout and stderr logs.
#
# See https://docs.dagster.io/deployment/dagster-instance#compute-log-storage for more information.
####################################################################################################
computeLogManager:
  # Type can be one of [
  #   NoOpComputeLogManager,
  #   AzureBlobComputeLogManager,
  #   GCSComputeLogManager,
  #   S3ComputeLogManager,
  #   CustomComputeLogManager,
  # ]
  type: NoOpComputeLogManager
  config: {}
  ##  Uncomment this configuration if the AzureBlobComputeLogManager is selected
  #   azureBlobComputeLogManager:
  #     storageAccount: ~
  #     container: ~
  #     secretCredential: ~
  #     defaultAzureCredential: ~
  #     accessKeyOrSasToken: ~
  #     localDir: ~
  #     prefix: ~
  #     uploadInterval: ~
  #     showUrlOnly: ~
  ##  Uncomment this configuration if the GCSComputeLogManager is selected
  #   gcsComputeLogManager:
  #     bucket: ~
  #     localDir: ~
  #     prefix: ~
  #     jsonCredentialsEnvvar: ~
  #     uploadInterval: ~
  ##  Uncomment this configuration if the S3ComputeLogManager is selected
  #   s3ComputeLogManager:
  #     bucket: ~
  #     localDir: ~
  #     prefix: ~
  #     useSsl: ~
  #     verify: ~
  #     verifyCertPath: ~
  #     endpointUrl: ~
  #     skipEmptyFiles: ~
  #     uploadInterval: ~
  #     uploadExtraArgs: {}
  ##  Uncomment this configuration if the CustomComputeLogManager is selected.
  ##  Using this setting requires a custom webserver image that defines the user specified
  ##  compute log manager in an installed python module.
  #   customComputeLogManager:
  #     module: ~
  #     class: ~
  #     config: {}
```

Am I right in thinking this is not currently supported? Or is the documentation just out of date?

### Additional information

I am using Dagster version `1.9.6` and deploying on Kubernetes.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
