### ISSUE TITLE
Kubernetes envSecrets can be defined as optional, but raise an error that prevents run launching

### ISSUE THREAD

**Issue by menzenski** [dagster-io/dagster#27379]
### What's the issue?

The items in the `envSecrets` array in the `dagster/dagster-user-deployments` Helm chart (schema links: [here](https://github.com/dagster-io/dagster/blob/ef87f61c250560509813a6bf07cc0724fa34d490/helm/dagster/charts/dagster-user-deployments/values.schema.json#L322) and [here](https://github.com/dagster-io/dagster/blob/ef87f61c250560509813a6bf07cc0724fa34d490/helm/dagster/charts/dagster-user-deployments/values.schema.json#L155)) are objects that allow both a `name` string and an `optional` boolean:

```json
    "io.k8s.api.core.v1.SecretEnvSource": {
      "description": "SecretEnvSource selects a Secret to populate the environment variables with.\n\nThe contents of the target Secret's Data field will represent the key-value pairs as environment variables.",
      "properties": {
        "name": {
          "description": "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names",
          "type": "string"
        },
        "optional": {
          "description": "Specify whether the Secret must be defined",
          "type": "boolean"
        }
      },
      "type": "object"
    },
```

I'm able to define an item in this array as "optional" in the values.yaml:

```yaml
    envSecrets:
      - name: my-required-secret
      - name: my-optional-secret  # only used in prod
        optional: true
```

When I do this, the code server (Kubernetes Deployment) starts up fine, and I can view Dagster resources in the UI in the way that I expect. But any Run launched in this code location fails to start, with a `RUN_FAILURE` error:

> Run timed out due to taking longer than 300 seconds to start.
> Debug information for pod dagster-run-<run-id>:
> 
> Pod status: Pending
> Container 'dagster' status: Waiting: CreateContainerConfigError: secret "my-optional-secret" not found
>
> No logs for container 'dagster'.
>
> Warning events for pod:
> Failed: Error: secret "my-optional-secret" not found (x8)
> For more information about the failure, try running `kubectl describe pod dagster-run-<run-id>`, `kubectl logs dagster-run-<run-id>`, or `kubectl describe job dagster-run-<run-id>` in your cluster.

### What did you expect to happen?

I'm able to specify in the values.yaml `envSecrets` field that a given Kubernetes secret is optional. When a secret is optional, a Run should be able to occur without error if that Secret is not present. (Of course if a given Run tries to _use_ an optional secret that's not defined, that should error. But A Run from that code location that doesn't use that particular secret should be able to execute).

If an optional secret won't work (or isn't allowed), I'd much rather that it raise an error early. Part of the issue here is that the error isn't raised until a run is attempted - if it had raised an issue during the startup of the Deployment it'd be easier to account for.

### How to reproduce?

Here is a minimal `values.yaml` file that can be used with the `dagster/dagster-user-deployments` Helm chart to reproduce this. 

```yaml
deployments:
  - name: "k8s-example-user-code-3"
    image:
      repository: "docker.io/dagster/user-code-example"
      tag: ~
      pullPolicy: Always
    dagsterApiGrpcArgs:
      - "-f"
      - "/example_project/example_repo/repo.py"
    port: 3030
    includeConfigInLaunchedRuns:
      enabled: true
    envSecrets:
      - name: my-optional-secret
        optional: true
```

I installed it with:

```shell
helm upgrade --install my-dagster-user-deployments dagster/dagster-user-deployments \
    --namespace dagster \
    --kube-context "${CONTEXT}" \
    --version 1.9.3 \
    -f .values.yaml
```

The `values.yaml` file for the main `dagster/dagster` deployment has this for the webserver:

```yaml
dagsterWebserver:
  replicaCount: 1
  image:
    # When a tag is not supplied for a Dagster provided image,
    # it will default as the Helm chart version.
    repository: "docker.io/dagster/dagster-celery-k8s"
    tag: ~
    pullPolicy: Always
  workspace:
    enabled: true
    servers:
      - host: "k8s-example-user-code-3"
        port: 3030
        name: "user-code-example"
```

Here are some screenshots:

The code location is loaded without error (the Deployment starts without error):

<img width="1172" alt="Image" src="https://github.com/user-attachments/assets/62404eca-251e-4572-b5f8-00dbe21e1bd8" />

However, job launched in this code location fails:

<img width="1473" alt="Image" src="https://github.com/user-attachments/assets/fd47457f-7260-48b0-bbc0-7349212244ad" />

<img width="1203" alt="Image" src="https://github.com/user-attachments/assets/bf413698-b614-455d-b8c8-11dc7efa094f" />

### Dagster version

dagster, version 1.9.3

### Deployment type

Dagster Helm chart

### Deployment details

We have Dagster OSS deployed on Kubernetes using the `dagster/dagster` Helm chart. We also have several deployments of user code via the `dagster/dagster-user-deployments` Helm chart. (We're using chart version 1.9.3 currently).

We use Kustomize to inflate the Helm chart values, and use ArgoCD to actually deploy the resources to Kubernetes.

### Additional information

It looks like the "optional" field gets lost [here](https://github.com/dagster-io/dagster/blob/ef87f61c250560509813a6bf07cc0724fa34d490/helm/dagster/charts/dagster-user-deployments/templates/helpers/_helpers.tpl#L110-L117)? This seems to take in an array of objects (which can have a `name` and also an `optional` boolean) and returns an array of strings. Only the `name` property gets passed through to the [K8sContainerContext](https://github.com/dagster-io/dagster/blob/ef87f61c250560509813a6bf07cc0724fa34d490/python_modules/libraries/dagster-k8s/dagster_k8s/container_context.py#L70) so it seems to have no way to know that a given secret is "optional".

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
