### ISSUE TITLE
AzureBlobComputeLogManager config not working

### ISSUE THREAD

**Issue by Elrau** [dagster-io/dagster#27438]
### What's the issue?

Hi,

I have a Dagster deployment on Kubernetes and encounter a weird issue with AzureBlobComputeLogManager config.

If I follow the documentation, I have the following configuration :
```
compute_logs:
  module: dagster_azure.blob.compute_log_manager
  class: AzureBlobComputeLogManager
  config:
    storage_account: "mystorageaccount"
    container:
      env: ENV
    access_key_or_sas_token: 
      env: AZURE_SA_KEY
    prefix: "dagster-compute-logs"
    local_dir: "/tmp/dagster/compute_logs"
    upload_interval: 30
```

With this, I can't even run a job and the error said :
" Error 1: Received unexpected config entry "access_key_or_sas_token" at the root. Expected: "{ container: (String | { env: String }) default_azure_credential?: { }? local_dir?: (String | { env: String })? prefix?: (String | { env: String }) secret_key?: (String | { env: String })? storage_account: (String | { env: String }) upload_interval?: Int? }"."

According to it, I changed my configuration to have the following :
```
compute_logs:
  module: dagster_azure.blob.compute_log_manager
  class: AzureBlobComputeLogManager
  config:
    storage_account: "mystorageaccount"
    container:
      env: ENV
    secret_key: 
      env: AZURE_SA_KEY
    prefix: "dagster-compute-logs"
    local_dir: "/tmp/dagster/compute_logs"
    upload_interval: 30
```

I can now run my jobs, I can see my log files in the Azure Storage Account. The problem is, when I want to see them from Dagster UI :
"Error 1: Received unexpected config entry "secret_key" at the root. Expected: "{ access_key_or_sas_token?: (String | { env: String })? container: (String | { env: String }) default_azure_credential?: { }? local_dir?: (String | { env: String })? prefix?: (String | { env: String }) secret_credential?: { client_id: (String | { env: String }) client_secret: (String | { env: String }) tenant_id: (String | { env: String }) }? show_url_only?: Bool storage_account: (String | { env: String }) upload_interval?: Int? }"."

The first one want the `secret_key` option but not the `access_key_or_sas_token` and it's the opposite for the other one. I tried to put both but it didn't change everything because daemon can't handle the `access_key_or_sas_token` and then I don't have any jobs.

Is this an expected behavior or I missed something ?

### Dagster version

1.9.10

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
