### ISSUE TITLE
[docs] Incorrect syntax for component templating

### ISSUE THREAD

**Issue by stevenayers** [dagster-io/dagster#28494]
### What's the issue or suggestion?

The following code snippet will cause an "unhashable dict" error:

https://github.com/dagster-io/dagster/blob/c56c65db1b42a2756d0654111af2126c9f514a70/docs/docs/guides/labs/components/building-pipelines-with-components/adding-components.md?plain=1#L71-L77

### Additional information

Docs can be found here: https://docs.dagster.io/guides/labs/components/building-pipelines-with-components/adding-components#component-templating

The correct syntax is:

```yaml
component_type: my_snowflake_component

attributes:
    account: "{{ env('SNOWFLAKE_ACCOUNT') }}"
    password: "{{ env('SNOWFLAKE_PASSWORD') }}"
```

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
