### ISSUE TITLE
Make scheduler time to be the same as time that scheduler run 

### ISSUE THREAD

**Issue by wingyplus** [dagster-io/dagster#2850]
## version info

dagster & dagit version: 0.9.2

## dagster instance details

```yaml
local_artifact_storage:
    module: dagster.core.storage.root
    class: LocalArtifactStorage
    config:
    base_dir: /opt/dagster/local/

run_storage:
    module: dagster_postgres.run_storage
    class: PostgresRunStorage
    config:
    postgres_db:
db_name:
    env: DAGSTER_PG_DB
hostname:
    env: DAGSTER_PG_HOST
password:
    env: DAGSTER_PG_PASSWORD
port: 5432
username:
    env: DAGSTER_PG_USERNAME

event_log_storage:
    module: dagster_postgres.event_log
    class: PostgresEventLogStorage
    config:
    postgres_db:
db_name:
    env: DAGSTER_PG_DB
hostname:
    env: DAGSTER_PG_HOST
password:
    env: DAGSTER_PG_PASSWORD
port: 5432
username:
    env: DAGSTER_PG_USERNAME

compute_logs:
    module: dagster.core.storage.local_compute_log_manager
    class: LocalComputeLogManager
    config:
    base_dir: /lfc_pipeline/storage

schedule_storage:
    module: dagster_postgres.schedule_storage
    class: PostgresScheduleStorage
    config:
    postgres_db:
db_name:
    env: DAGSTER_PG_DB
hostname:
    env: DAGSTER_PG_HOST
password:
    env: DAGSTER_PG_PASSWORD
port: 5432
username:
    env: DAGSTER_PG_USERNAME

scheduler:
    module: dagster_cron.cron_scheduler
    class: SystemCronScheduler
    config:
    {}

run_launcher:
    module: dagster
    class: DefaultRunLauncher
    config:
    {}

opt_in:
    NoneType

telemetry:
    enabled: false
```

Currently, time of scheduler show as UTC. But time that scheduler got executed are show as local time. For example:

Time in scheduler page: 
![Screen Shot 2563-08-24 at 10 36 43](https://user-images.githubusercontent.com/484530/91001485-03ff4d00-e5f6-11ea-987b-f2f851c75639.png)

Time in all runs page:
![Screen Shot 2563-08-24 at 10 36 59](https://user-images.githubusercontent.com/484530/91001488-06fa3d80-e5f6-11ea-95bb-ce1a57725622.png)

## What I expected

Time in the scheduler page should show as local time.

## What's actual

It's utc time which set in scheduler.
