### ISSUE TITLE
[dagster-components] `AssetSpecModel` does not resolve dep asset keys

### ISSUE THREAD

**Issue by stevenayers** [dagster-io/dagster#28530]
### What's the issue?

When using `AssetSpecModel` in a component, the resolution of dependencies with multi-part asset keys does not resolve them, and keeps them as a string.

Given the `component.yaml`:
```yaml
type: dagster_components.dagster.PipesSubprocessScriptCollectionComponent

attributes:
  scripts:
    - path: "my_script.py"
      assets:
        - key: "kitchen_sink"
          deps:
            - "prefixed/upstream"
```

Dagster will throw:
> ERROR:dagster.code_server:dagster._core.errors.DagsterInvalidDefinitionError: "my/upstream" is not a valid name in Dagster. Names must be in regex ^[A-Za-z0-9_]+$.

### Dagster version

dagster, version 1.10.5

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
