### ISSUE TITLE
[dagster-dg] `dg list defs` cannot resolve templated environment variables in `component.yaml`

### ISSUE THREAD

**Issue by stevenayers** [dagster-io/dagster#28537]
### What's the issue?

With the following `component.yaml`:
```yaml
type: dagster_components.dagster.PipesSubprocessScriptCollectionComponent

attributes:
  scripts:
    - path: "my_script.py"
      assets:
        - key: "{{ env('FOO') }}"
          deps:
            - "prefixed/upstream"
```
and `.env` file:
```.env
FOO=BAR
```

`dg list defs` will throw the following error:

> dagster._check.functions.CheckError: Failure condition: Unexpected type for AssetKey: <class 'NoneType'>

However, when running `dg dev`, the `component.yaml` is able to resolve the environment variable.

### What did you expect to happen?

I would expect `dg list defs` to have access to the `.env` variables, the same way `dg dev` does.

### Dagster version

dagster, version 1.10.5 | dg, version 0.2.2

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
