### ISSUE TITLE
Failing materialisation does not exhaust max retries

### ISSUE THREAD

**Issue by TabLand** [dagster-io/dagster#28965]
### What's the issue?

Hi Team,

We have periodically experienced an issue in both our production and UAT environments where a failing job / materialisation is not retried up to the value specified in `dagster/max_retry` tag, or even at all.

I've managed to replicate this issue consistently in a development environment, by using the attached configuration.

### What did you expect to happen?

Run retries need to be applied consistently and reliably

### How to reproduce?

dagster.yaml:
```yaml
run_retries:
  enabled: true
  max_retries: 200

storage:
  postgres:
    postgres_db:
      username: postgres
      password: changme
      hostname: DB_HOST
      db_name: dagster
      port: 5432

run_monitoring:
  enabled: true

telemetry:
  enabled: true
```

__init__.py:
```py
from dagster import Definitions, OpExecutionContext, asset

@asset
def failing_asset():
    assert 1 == 0

defs = Definitions(
    assets=[failing_asset],
)
```

### Dagster version

1.7.7

### Deployment type

Local

### Deployment details

Running on Windows 10
PostgreSQL 16.1

### Additional information

[err.txt](https://github.com/user-attachments/files/19588600/err.txt)
![Image](https://github.com/user-attachments/assets/0c3fff91-0803-472e-ab12-5e3adc7c6bb0)
![Image](https://github.com/user-attachments/assets/1780a5a4-79c1-4dd4-aca3-ac72bdd3e68b)
[out.txt](https://github.com/user-attachments/files/19588599/out.txt)

The failure to re-execute an unsuccessful run seems to be correlated to this warning: 

```
WARNING:root:Retrying failed database connection: (psycopg2.OperationalError) connection to server at "##DB_HOST##" (10.X.X.X), port 5432 failed: Connection timed out (0x0000274C/10060)
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/20/e3q8)
```

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
