### ISSUE TITLE
Created container for partition runs remember old schema and fails at schema evolution

### ISSUE THREAD

**Issue by Thealoe** [dagster-io/dagster#29143]
### What's the issue?

# Overview

When evolving schemas in DuckDB assets (adding/removing columns), we encounter `duckdb.duckdb.BinderException: Binder Error: table abc has 8 columns but 9 values were supplied errors` in Docker Compose deployments, despite using fresh database files in the code server (duck db database for xcom is ignored in its Dockerfile - **on the initial definitions.py load, the duckdb database is empty**)

# Environment

-  `DockerRunLauncher`
- Paritionned assets (so i cannot just drop table on my first asset start) on a duckdb xcom database
- IO Manager that is equivalent of : `DuckDBPandasIOManager `

# Observed Behavior

- Asset execution works fine in development with `dagster dev`, i can just manually delete the duckdb xcom database to avoid the issue
- In Docker deployment, when schema changes (add column for ex), **container runners remember old schemas on its definition.py load.** (this is the root of the issue, how can container runner have tables in the first place if code location is loaded with en empty database, where does it come from? Some internal dagster process with related to deamon, idk?)

# Details

Custom IO Manager i used that is equivalent of `DuckDBPandasIOManager ` :

```
class CustomDuckDBPandasTypeHandler(DuckDBPandasTypeHandler):
    def handle_output(
        self,
        context: OutputContext,
        table_slice: TableSlice,
        obj: pd.DataFrame,
        connection,
    ):
        # Basically does nothing ......
        return super().handle_output(
            context=context, table_slice=table_slice, obj=obj, connection=connection
        )

class PandasIO(DuckDBIOManager):
    @staticmethod
    def type_handlers() -> Sequence[DbTypeHandler]:
        return [CustomDuckDBPandasTypeHandler()]

    @classmethod
    def _is_dagster_maintained(cls) -> bool:
        return True

    @staticmethod
    def default_load_type() -> Optional[type]:
        return pd.DataFrame
```

How database is created in the definitions.py :

```
defs = Definitions(
        assets=all_registry_assets,
        asset_checks=all_assets_checks,
        jobs=[registry_updates_job, registry_fillup_job],
        schedules=[daily_1am_schedule],
        resources={
            # Generics
            "dbt": DbtCliResource(project_dir=orchestrator_dbt_project),
            "pandas_io": PandasIO(database=database, schema="orchestrator"),
            [...]
        },
 )
```

Docker-Compose i use for deployment and testing containerization on local machine :

To know, `./code_locations/orchestrator_code_location/io_storage:/app/code_locations/orchestrator_code_location/io_storage` is where i keep the duckdb xcom database for inter asset communication.

```
services:
  # This service runs the postgres DB used by dagster 
  # for : run storage, schedule storage and event log storage.
  pgstorage:
    build:
      context: .
      dockerfile: ./dockers/pgstorage.dockerfile
    image: [...]
    pull_policy: never
    container_name: pgstorage
    environment:
      [...]
    networks:
      - dagster_ecosystem_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bernster-admin -d bernster-admin-db"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

  # This service runs the orchestrator's source code
  orchestrator:
    build:
      context: .
      dockerfile: ./code_locations/orchestrator_code_location/orchestrator/Dockerfile
    container_name: orchestrator
    image: [...]
    pull_policy: never
    extra_hosts:
      [...]
    restart: always
    environment:
      ENV: ${ENV}
	  [...]
    networks:
      - dagster_ecosystem_network

  # This service runs dagster-webserver, which loads your user code from the user code container.
  # Since our instance uses the QueuedRunCoordinator, any runs submitted from the webserver will be put on
  # a queue and later dequeued and launched by dagster-daemon.
  bernster_gui:
    build:
      context: .
      dockerfile: ./dockers/bernster_gui.dockerfile
    image: [...]
    pull_policy: never
    entrypoint:
      - dagster-webserver
      - -h
      - "0.0.0.0"
      - -p
      - "5013"
      - --path-prefix
      - /bernster 
      - -w
      - workspace.yaml
    container_name: bernster_gui
    expose:
      - "5013"
    ports:
      - "5013:5013"
    environment:
	 [...]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./code_locations/orchestrator_code_location/io_storage:/app/code_locations/orchestrator_code_location/io_storage
    networks:
      - dagster_ecosystem_network
    depends_on:
      pgstorage:
        condition: service_healthy
      orchestrator:
        condition: service_started

  # This service runs the dagster-daemon process, which is responsible for taking runs
  # off of the queue and launching them, as well as creating runs from schedules or sensors.
  # Each time a run starts, a new container is created and the configuration for this container
  # is defined in the dagster.yaml file (look for section: run_launcher).
  bernster_daemon:
    build:
      context: .
      dockerfile: ./dockers/bernster_daemon.dockerfile
    image: [...]
    pull_policy: never
    entrypoint:
      - dagster-daemon
      - run
    container_name: bernster_daemon
    restart: on-failure
    environment:
      ENV: ${ENV}
	  [...]
    extra_hosts:
      [...]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./code_locations/orchestrator_code_location/io_storage:/app/code_locations/orchestrator_code_location/io_storage
    networks:
      - dagster_ecosystem_network
    depends_on:
      pgstorage:
        condition: service_healthy
      orchestrator:
        condition: service_started

networks:
  dagster_ecosystem_network:
    driver: bridge
    name: dagster_ecosystem_network

volumes:
  pgdata:
```

Important parts dagster.yaml configuration for the instance :

Notice, `/app/code_locations/orchestrator_code_location/io_storage:/app/code_locations/orchestrator_code_location/io_storage` is shared 

```
run_launcher:
  module: dagster_docker
  class: DockerRunLauncher
  config:
    env_vars:
      - [...]
    network: dagster_ecosystem_network
    container_kwargs:
      extra_hosts:
        [...]
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /app/code_locations/orchestrator_code_location/io_storage:/app/code_locations/orchestrator_code_location/io_storage

run_coordinator:
  module: dagster.core.run_coordinator
  class: QueuedRunCoordinator
  config:
    max_concurrent_runs: 1  # (temp) removes concurrency issue during full backfill jobs on my api
    tag_concurrency_limits: []
```

### Dagster version

dagster, version 1.10.9

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
