### ISSUE TITLE
dagster-dbt: Add `asset_key_prefix` to supported dbt meta config for dagster

### ISSUE THREAD

**Issue by mattgiles** [dagster-io/dagster#29249]
### What's the use case?

The documentation [highlights two broad approaches](https://docs.dagster.io/integrations/libraries/dbt/reference#customizing-asset-keys) to customizing asset keys for dbt assets.

The example given is:

```yaml
sources:
  - name: jaffle_shop
    tables:
      - name: orders
        meta:
          dagster:
            asset_key: ['snowflake', 'jaffle_shop', 'orders']
```

A lot of natural uses of this pattern end up with the asset_key meta config repeated for every model, with only the third element (the model name) repeated.

In dbt, it is idiomatic (and convenient) to make use of config inheritance/hierarchy to avoid this kind of repetition.

It would be great to support a pattern like:

```yaml
models:
  +materialized: table
  meta:
    dagster:
      asset_key_prefix: ['snowflake', 'jaffle_shop']
```

In my case, if this existed, I would avoid a fair amount of code/complexity maintaining a configurable `DagsterDbtTranslator` with the ability to avail itself of `AssetKey.with_prefix`.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
