### ISSUE TITLE
Set old GitHub issues to stale and close them

### ISSUE THREAD

**Issue by stevenayers** [dagster-io/dagster#29390]
### What's the use case?

There's currently 2.4k issues open on the Dagster project, some of which are 6 years old.

Sometimes when I'm scanning through to see any other relevant issues, there's a lot of noise that comes up that likely isn't relevant anymore, considering how fast this project moves.

### Ideas of implementation

Use the [stale GitHub action](https://github.com/actions/stale).

Below would mark an inactive issue stale after 60 days, then delete 30 days after:
```yaml
name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'

permissions:
  issues: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed in 30 days.'
          days-before-issue-stale: 60
          days-before-issue-close: 30
          # don't mark PRs as stale and don't close them
          days-before-pr-stale: -1
          days-before-pr-close: -1
```

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
