### ISSUE TITLE
[dagster-dbt] Expose `DagsterDbtTranslatorSettings` via `DbtProjectComponent`

### ISSUE THREAD

**Issue by stevenayers** [dagster-io/dagster#29745]
### What's the use case?

Currently these settings aren't exposed via `DbtProjectComponent` and due to the way the translator is resolved from YAML, it's not immediately obvious how you can inherit from `DbtProjectComponent` to add the customization yourself.

### Ideas of implementation

```yaml
type: dagster_dbt.DbtProjectComponent

attributes:
  exclude: '...'
  op:
    backfill_policy:
      type: '...'
    name: '...'
    tags: {}
  project: '...'
  select: '...'
  translation: 
    settings:
      enable_asset_checks: true
      enable_duplicate_source_asset_keys: false
      enable_code_references: false
      enable_dbt_selection_by_name: false
      enable_source_tests_as_checks: false
```

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
