### ISSUE TITLE
Intermittent DagsterExecutionInterruptedError failures

### ISSUE THREAD

**Issue by jrmartin** [dagster-io/dagster#29752]
### What's the issue?

**Bug Report: Intermittent DagsterExecutionInterruptedError During Asset Execution on K8s
Summary:**
We're seeing sporadic DagsterExecutionInterruptedError exceptions when running assets on Kubernetes with Dagster Cloud using the K8sRunLauncher. These errors are not consistent and seem to interrupt asset execution mid-compute, even though nothing in the code explicitly raises them. Any ideas how to debug this? Each asset uses tags to launch a pod in its own EC2 instance, and we see this error happen at random times, when starting pod or in the middle of asset execution. Memory doesn't seem to be the issue during computation, but rather an external signal coming in to kill the pod. 

 **Environment**
Dagster Cloud

User Code Launcher: K8sUserCodeLauncher (with terminationGracePeriodSeconds: 120)

Run Launcher: K8sRunLauncher

Runtime: Python 3.12

Platform: AWS EKS with Karpenter-managed nodes

Query logic: asset step uses awswrangler.athena.read_sql_query

**Sample Failure**
dagster._core.errors.DagsterExecutionInterruptedError

  File "/usr/src/app/.pixi/envs/default/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_plan.py", line 245, in dagster_event_sequence_for_step
    yield from check.generator(step_events)
  File "/usr/src/app/.pixi/envs/default/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 506, in core_dagster_event_sequence_for_step
    for user_event in _step_output_error_checked_user_event_sequence(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/.pixi/envs/default/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 189, in _step_output_error_checked_user_event_sequence
    for user_event in user_event_sequence:
                      ^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/.pixi/envs/default/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 88, in _process_asset_results_to_events
    for user_event in user_event_sequence:
                      ^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/.pixi/envs/default/lib/python3.12/site-packages/dagster/_core/execution/plan/compute.py", line 187, in execute_core_compute
    for step_output in _yield_compute_results(step_context, inputs, compute_fn, compute_context):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/.pixi/envs/default/lib/python3.12/site-packages/dagster/_core/execution/plan/compute.py", line 156, in _yield_compute_results
    for event in iterate_with_context(
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/.pixi/envs/default/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 392, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/usr/src/app/src/lfc_analytical_pipeline/assets/analyze/detach_cell_asset.py", line 140, in detach_cell_asset
    aligned_cell_positions = reconstruct_tracked_cells_parquet(context, partition_key, cfg.expt.paths.cell_kinetics,
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/src/lfc_analytical_pipeline/assets/analyze/utils.py", line 29, in reconstruct_tracked_cells_parquet
    df = context.resources.iceberg_io_manager.load_input(input_context)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/.pixi/envs/default/lib/python3.12/site-packages/exthymic/resources/iceberg_io_manager.py", line 172, in load_input
    df = wr.athena.read_sql_query(sql=sql, database=database)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/.pixi/envs/default/lib/python3.12/site-packages/awswrangler/_config.py", line 712, in wrapper
    return function(**args)
           ^^^^^^^^^^^^^^^^
  File "/usr/src/app/.pixi/envs/default/lib/python3.12/site-packages/awswrangler/_utils.py", line 179, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/.pixi/envs/default/lib/python3.12/site-packages/awswrangler/athena/_read.py", line 1083, in read_sql_query
    return _resolve_query_without_cache(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/.pixi/envs/default/lib/python3.12/site-packages/awswrangler/athena/_read.py", line 508, in _resolve_query_without_cache
    return _resolve_query_without_cache_ctas(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/.pixi/envs/default/lib/python3.12/site-packages/awswrangler/athena/_read.py", line 325, in _resolve_query_without_cache_ctas
    ctas_query_info: dict[str, str | _QueryMetadata] = create_ctas_table(
                                                       ^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/.pixi/envs/default/lib/python3.12/site-packages/awswrangler/_config.py", line 712, in wrapper
    return function(**args)
           ^^^^^^^^^^^^^^^^
  File "/usr/src/app/.pixi/envs/default/lib/python3.12/site-packages/awswrangler/athena/_utils.py", line 847, in create_ctas_table
    response["ctas_query_metadata"] = _get_query_metadata(
                                      ^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/.pixi/envs/default/lib/python3.12/site-packages/awswrangler/athena/_utils.py", line 233, in _get_query_metadata
    _executions.wait_query(
  File "/usr/src/app/.pixi/envs/default/lib/python3.12/site-packages/awswrangler/_config.py", line 712, in wrapper
    return function(**args)
           ^^^^^^^^^^^^^^^^
  File "/usr/src/app/.pixi/envs/default/lib/python3.12/site-packages/awswrangler/athena/_executions.py", line 224, in wait_query
    time.sleep(athena_query_wait_polling_delay)
  File "/usr/src/app/.pixi/envs/default/lib/python3.12/site-packages/dagster/_utils/interrupts.py", line 83, in _new_signal_handler
    raise error_cls()

**dagster.yaml**
```
instance_class:
  module: dagster_cloud.instance
  class: DagsterCloudAgentInstance

dagster_cloud_api:
  agent_token: agent:account:44446232323232323233232
  branch_deployments: true
  deployment: prod

user_code_launcher:
  module: dagster_cloud.workspace.kubernetes
  class: K8sUserCodeLauncher
  config:
    namespace: dagster-plus
    service_account_name: user-cloud-dagster-cloud-agent
    instance_config_map: user-cloud-dagster-cloud-agent-instance
    dagster_home: /opt/dagster/dagster_home
    pull_policy: Always
    server_ttl:
      enabled: true
      ttl_seconds: 7200
    server_k8s_config:
      pod_spec_config:
        terminationGracePeriodSeconds: 120
        tolerations:
          - key: "karpenter.sh/provisioned"
            operator: "Exists"
      pod_template_spec_metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
          karpenter.sh/do-not-disrupt: "true"
          karpenter.sh/requirements: >
            [{"key": "node.kubernetes.io/instance-type", "operator": "In", "values": ["m5d.xlarge", "r5.2xlarge", "g4dn.4xlarge", "c5d.4xlarge", "g5.2xlarge", "g5.4xlarge", "g5.8xlarge", "c5d.9xlarge", "m5d.8xlarge"]},
             {"key": "node.kubernetes.io/disk", "operator": "Gt", "values": ["500Gi"]}]

python_logs:
  python_log_level: INFO
  managed_python_loggers:
    - dagster

telemetry:
  enabled: false

run_launcher:
  module: dagster_k8s
  class: K8sRunLauncher
  config:
    max_concurrent_runs: 10
    delete_failed_k8s_jobs: false
    run_k8s_config:
      tolerations:
        - key: "karpenter.sh/provisioned"
          operator: "Exists"
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
        karpenter.sh/do-not-disrupt: "true"
        karpenter.sh/requirements: >
          [{"key": "node.kubernetes.io/instance-type", "operator": "In", "values": ["m5d.xlarge", "r5.2xlarge", "g4dn.4xlarge", "c5d.4xlarge", "g5.2xlarge", "g5.4xlarge", "g5.8xlarge", "c5d.9xlarge", "m5d.8xlarge"]},
           {"key": "node.kubernetes.io/disk", "operator": "Gt", "values": ["500Gi"]}]
      pod_spec_config:
        terminationGracePeriodSeconds: 120
```

### Dagster version

v.1.10.1

### Deployment type

Dagster Cloud

### Deployment details

**Environment**
Dagster Cloud
User Code Launcher: K8sUserCodeLauncher

Run Launcher: K8sRunLauncher

Kubernetes Cluster: AWS EKS + Karpenter

Python Version: 3.12

Dagster Version: v1.10.1

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
