### ISSUE TITLE
Retry from failure asset does not include the failure asset which asset check failed

### ISSUE THREAD

**Issue by wenbinye** [dagster-io/dagster#30105]
### What's the issue?

When using the "From Asset Failure" execution feature in Dagster, assets with failed data tests are not being included in the execution scope.

### What did you expect to happen?

When using "From Asset Failure" execution, all assets with failed checks (including data tests) should be included in the execution scope.

### How to reproduce?

1. Set up a dbt project with two models:
   - `my_first_dbt_model`
   - `my_second_dbt_model`
2. Add a data tests to check for unique IDs in `my_first_dbt_model`
```sql
{{ config(materialized='table') }}

with source_data as (

    select 1 as id
    union all
    select 1 as id
)

select *
from source_data
where id is not null
```
```yaml
models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
```

3. Run the models and observe that the data test fails in `my_first_dbt_model`
4. Use "From Asset Failure" execution feature
5. Observe that only `my_second_dbt_model` is included in the execution, while `my_first_dbt_model` (which has the failed data test) is not included

### Dagster version

1.10.15

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
