### ISSUE TITLE
Problem with environment variable resolution in configs when using Dagit with remote gRPC server

### ISSUE THREAD

**Issue by kinghuang** [dagster-io/dagster#3013]
### Summary

I reconfigured my Dagit instance to load from gRPC servers instead of local modules. In my Dagit instance, the Dagster configuration specifies environment variables for many config values. Here is an example.

```yaml
run_storage:
  module: dagster_postgres.run_storage
  class: PostgresRunStorage
  config:
    postgres_db:
      hostname:
        env: DAGSTER_POSTGRES_HOST
      port:
        env: DAGSTER_POSTGRES_PORT
      username:
        env: DAGSTER_POSTGRES_USER
      password:
        env: DAGSTER_POSTGRES_PASSWORD
      db_name:
        env: DAGSTER_POSTGRES_DB
```

My Dagit instance (a Docker container) has environment variables set for `DAGSTER_POSTGRES_HOST`, `DAGSTER_POSTGRES_PORT`, `DAGSTER_POSTGRES_USER`, etc.

When I use Dagit to run a remote pipeline, it appears to send the Dagit instance's Dagster config to the remote Dagster gRPC server (another Docker container) and then resolve the environment variables there. The gRPC server container does not have these environment variables set.

I think environment variables in the config should be resolved by the Dagit instance, and the result sent to the Dagster gRPC server. The configuration is being done from Dagit's perspective, not the remote server. I don't think it makes sense to have to configure the environment variables on every possible remote server instead of on Dagit.

### Steps to reproduce

1. For Dagit, create a Dagster configuration that uses environment variables for some of the config values (see example above).
2. Configure a gRPC server for Dagit to get repositories from. Do not configure the gRPC server with the environment variables used in the config.
3. Run a pipeline on the remote server through Dagit.

### What is the current *bug* behaviour?

Dagit appears to send the Dagster configuration verbatim, including the references to environment variables. When the remote gRPC server loads the config, it attempts to resolve the environment variables from its perspective, where they might not be configured or have different values than Dagit. The following error is raised for missing environment variables.

> dagster.core.errors.DagsterLaunchFailedError: Error during RPC setup for executing run: dagster.core.errors.DagsterInvalidConfigError: Errors whilst loading configuration for <dagster.config.field_utils.Selector object at 0x7f4396fff1c0>. Error 1: Post processing at path root:postgres_db:username of original value {'env': 'DAGSTER_POSTGRES_USER'} failed: (PostProcessingError) - dagster.config.errors.PostProcessingError: You have attempted to fetch the environment variable "DAGSTER_POSTGRES_USER" which is not set. In order for this execution to succeed it must be set in this environment. 

### What is the expected *correct* behaviour?

Dagit should resolve environment variables in the configuration using from its perspective before sending the config to the remote gRPC server.

### Relevant logs and/or screenshots

This is the error shown in Dagit. It's extra confusing here, because Dagit does have the environment variables set. It's the remote Dagster gRPC server that doesn't have them.

![95142013-eca49b00-072f-11eb-9599-336a4029b47b](https://user-images.githubusercontent.com/27340/95156675-53d44680-0754-11eb-8f73-296f2ed278fc.png)

### Versions

```
root@994f48641753:/project# dagster --version
dagster, version 0.9.13
root@994f48641753:/project# dagit --version
dagit, version 0.9.13
```

**Comment by gibsondan** [comment]
I think this is doable, but is one of the possible reasons for putting the postgres password in an environment variable so that it doesn't have to be passed around over your network in cleartext?

**Comment by alangenfeld** [comment]
> Dagit should resolve environment variables in the configuration using from its perspective before sending the config to the remote gRPC server.

The current design of the system is to avoid this so that we are not leaking sensitive information in plain text anywhere.

Going to close this issue since making the proposed change would have to be part of a large re-architecture.

**Comment by jeremyadamsfisher** [comment]
What is the recommended approach to passing secrets to a remote pipeline?

**Comment by alangenfeld** [comment]
> What is the recommended approach to passing secrets to a remote pipeline?

The common pattern is that when the "remote" computational resource is spun up, it can load secrets as environment variables using connected systems that manage secrets. 
https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/specifying-sensitive-data-tutorial.html

**Comment by tahesse** [comment]
@alangenfeld Sorry for bumping this closed thread, but simply from [the link you posted](https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#define-container-environment-variables-with-data-from-multiple-secrets) I fail to provide multiple secrets to my k8s jobs.

I created a k8s secret like so `kubectl create secret generic dagster-aws-s3 --from-env-file .env --namespace=dagster` and end up with this error:
```
dagster:
- dagster-user-deployments.deployments.0.env: Invalid type. Expected: object, given: array
```
My `dagster-user-deployments.deplyoments.0.env` look like this:
```
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: dagster-aws-s3
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: dagster-aws-s3
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: dagster-aws-s3
              key: AWS_DEFAULT_REGION
```
What I am supposed to put there? The dagster docs are sadly of no help to me here.
