### ISSUE TITLE
dagster-evidence duckdb required error when using postgres

### ISSUE THREAD

**Issue by jreaci** [dagster-io/dagster#30345]
### What's the issue?

When trying to use the dagster-evidence component, the below component.yaml:
```
type: dagster_evidence.EvidenceProject

attributes:
  project_path: ../reports
  asset:
    key: jaffle_dashboard
  deploy_command: 'echo "Dashboard built at $EVIDENCE_BUILD_PATH"'
```
finds the "reports" folder, but when I run `dg launch --assets jaffle_dashboard` or materialize in the UI I get the folowing error:
```
usage: dagster.EXE [-h] --duckdb DUCKDB
dagster.EXE: error: the following arguments are required: --duckdb
Failed to launch assets.
```

My sources are postgres only, not duckdb.

### Dagster version

1.10.17

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
