### ISSUE TITLE
dagster user-code-example dockerfile is missing pandas

### ISSUE THREAD

**Issue by adasilva** [dagster-io/dagster#30427]
### What's the issue?

When I run the user-code-example docker container, I get an error, `ModuleNotFoundError: No module named 'pandas'`. It seems that the image is missing pandas in order to be able to run the iris_analysis.

I am running dagster on a kind cluster on a mac laptop. Here is my values.yaml: 

```
dagsterDaemon: 
  runMonitoring: 
    enabled: true 
  image: 
    repository: "dagster-webserver" 
    tag: latest pullPolicy: Never # Important for kind cluster

postgresql: 
  enabled: true

dagster-user-deployments: 
  enabled: true 
  deployments: 
    - name: "k8s-example-user-code-1" 
      image: # When a tag is not supplied, it will default as the Helm chart version. 
        repository: "docker.io/dagster/user-code-example" 
        tag: ~ 
        pullPolicy: Always  
      dagsterApiGrpcArgs: 
        - "--module-name" 
        - "iris_analysis.definitions" 
      port: 3030 
      readinessProbe: 
        enabled: false

dagsterWebserver: 
  image: 
    repository: "dagster-webserver" 
    tag: latest 
    pullPolicy: Never # Important for kind cluster
```

### What did you expect to happen?

The example code container is able to run, and materialize the asset(s) using the webserver.

### How to reproduce?

Run the dagster helm chart on a kind (or similar) cluster with the user code example.

### Dagster version

1.10.18

### Deployment type

Dagster Helm chart

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
