### ISSUE TITLE
[components] Tag values are type-coerced but should remain strings

### ISSUE THREAD

**Issue by nixent** [dagster-io/dagster#30954]
### What's the issue?

When defining assets with components, tag values are implicitly type-converted but should remain strings.

**Steps to reproduce**
Create a component and specify a tag with _integer_ value:
```YAML
type: dagster_open_platform.lib.ScheduleComponent
attributes:
  name: hightouch_syncs_schedule
  target: group:hightouch_syncs and not (key:hightouch_sync_hubspot_company or key:hightouch_sync_hubspot_organization)
  tags:
    team: devrel
    my_tag: 123
  cron: 0 3 * * *

```

**Result**:
Error: Tag values must be strings, got type <class 'int'>

**Expected result**: tag type must remain string and no error.

**Observation**
The issue originates from attribute [resolution](https://github.com/dagster-io/dagster/blob/eddbf6e1b947307ae778046e29759b21ca5473f1/python_modules/dagster/dagster/components/utils.py#L118)

After the generic attribute resolution value for `code_version` is explicitly converted to a string, same needs to happen to `tags` 
```python
if "code_version" in resolved_attributes:
    resolved_attributes = {
        **resolved_attributes,
        "code_version": str(resolved_attributes["code_version"]),
    }

if "tags" in resolved_attributes:
    resolved_attributes["tags"] = {
        str(k): str(v) for k, v in resolved_attributes["tags"].items()
    } 
```

### How to reproduce?

Create a component and specify a tag with integer value:
```YAML
type: dagster_open_platform.lib.ScheduleComponent
attributes:
  name: hightouch_syncs_schedule
  target: group:hightouch_syncs and not (key:hightouch_sync_hubspot_company or key:hightouch_sync_hubspot_organization)
  tags:
    team: devrel
    my_tag: 123
  cron: 0 3 * * *

```

Result:
    Error: Tag values must be strings, got type <class 'int'>
Expected result: 
    tag type must remain string and no error.

### Dagster version

1.11

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
