### ISSUE TITLE
Special handling for dask.dataframe.to_sql dtype argument

### ISSUE THREAD

**Issue by kinghuang** [dagster-io/dagster#3104]
### Problem to solve

The Dask DataFrame type's `to_sql` materializer maps to the underlying [dask.dataframe.to_sql](https://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.to_sql) function, which accepts a `dtype` argument to customize the datatype for columns. The expected values are SQLAlchemy types. These are impossible to specify in the type's config YAML.

It would be nice if the DataFrame type provided special handling for `dtype` to convert string type references (e.g., `"JSON"`) into the equivalent SQLAlchemy type object (`sqlalchemy.types.JSON`).

### Intended users

* Pipeline Developer

### User experience goal

For DataFrames with `to_sql` materializers, it should be possible to configure the `dtype` option for standard use cases.

Pipeline developers will still have to custom code engine-specific dtypes.

### Proposal

The Dask DataFrame type's materializer should do special handling for the `.to_sql.dtype` option so that it is possible to configure it in YAML configs. The `dtype` option can either take a single type, which will be applied to all columns, or a dict of column: type entries. For the types, if it is a string value, the materializer will attempt to get an attribute of the same name from `sqlalchemy.types`, only.

**Example materializer config:**

```yaml
solids:
  dask_solid:
    outputs:
      - output_df:
          to:
            sql:
              uri: postgresql://host:5432/postgres
              name: output_table
              dtype:
                tokens: JSON
                spaces: JSON
```

The `dtype` config is a dict. The `JSON` string would get converted into `sqlalchemy.types.JSON`.

### Further details

* [dask.dataframe.to_sql](https://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.to_sql)
* [SQLAlchemy Column and Data Types](https://docs.sqlalchemy.org/en/13/core/type_basics.html)
