### ISSUE TITLE
Enable multiple outputs per materialization config on Dagster DataFrame type

### ISSUE THREAD

**Issue by kinghuang** [dagster-io/dagster#3114]
### Problem to solve

The Dask DataFrame type materializer was written to allow materialization to multiple types in a single materialization config. But, the materialization config `to` field is declared as a Selector, that only allows one type to be specified.

Allowing multiple types to be specified in the same materialization config allows the materializer to construct a more optimal Dask computation graph. The `to` field should be changed from a Selector to a Shape, and then the materializer loop optimized to compute with all the materializers together on the same graph.

### Intended users

* Pipeline Developer

### User experience goal

If a Dask DataFrame output is to be materialized to multiple formats, it should be possible to configure this in a single materialization config, which can then be optimized by the materializer to generate a single graph computation.

### Proposal

Given a dataframe output named `facets_df`, materializing this to both a JSON file and a database currently requires a materialization config like this.

```yaml
solids:
  dask_solid:
    outputs:
      - facets_df:
          to:
            json:
              path: s3://bucket/key
      - facets_df:
          to:
            sql:
              name: table
              uri: postgresql://server:5432/postgres
```

It should be possible to combine the `sql` and `json` options into a single materialization config like this.

```yaml
solids:
  dask_solid:
    outputs:
      - facets_df:
          to:
            json:
              path: s3://bucket/key
            sql:
              name: table
              uri: postgresql://server:5432/postgres
```

### Further details

This optimization does not change the behaviour when multiple materializers are defined using separate materializer configs.
