### ISSUE TITLE
Add button in Dagit that populates as much config as possible in the playground

### ISSUE THREAD

**Issue by helloworld** [dagster-io/dagster#3118]
When developing new pipelines, I spend a lot of time typing out the path to various config values. Autocomplete in the playground helps, but it is still quite slow. For example, if I have a solid and resource that needed to be configured, I type out:

```
solids:
   solid_name:
        config:
             key_name: value1
resources:
   resource_name:
        config:
             key_name: value2
```

However, if `key_name` was required for both the solid and resource, we know enough to at least scaffold out the following:

```
solids:
   solid_name:
        config:
             key_name:
resources:
   resource_name:
        config:
             key_name:
````

We should have a button that does this.
