### ISSUE TITLE
Spruce up the instructions to use Helm for Dagster

### ISSUE THREAD

**Issue by rexledesma** [dagster-io/dagster#3202]
https://github.com/dagster-io/dagster/tree/master/helm could use a revamp for defining installation instructions, having a section for defined `values.yaml` fields and defaults, etc

**Comment by natekupp** [comment]
@rexledesma hmm, should we just have this readme point to the k8s docs here https://docs.dagster.io/deploying/k8s_part1 and then refresh those docs?

**Comment by xaniasd** [comment]
hi there. Wanted to chip in here as I'm following the tutorial mentioned above and not off to a great start. After installing the helm chart with the default values, the dagit pod is crashing (see error log):

```
Starting periodic command scheduler: cron.
Usage: dagster schedule up [OPTIONS]

Error: No arguments given and workspace.yaml not found.
Usage: dagit [OPTIONS]

Error: No arguments given and workspace.yaml not found.
```
Not sure whether it's the chart's default setting that needs fixing, or the docs.

**Comment by rexledesma** [comment]
hey @xaniasd - sorry you ran into this. We're updating the example images that we provide so you won't run into this error.

In the meanwhile, if you want to try out the example using our user code separation deployment, feel free to try out the following:

with `values-override.yaml`
``` 
celery:
  enabled: false

k8sRunLauncher:
  enabled: true

userDeployments:
  enabled: true
  deployments:
    - name: "k8s-example"
      image:
        repository: dagster/k8s-example
        tag: latest
        pullPolicy: Always
      dagsterApiGrpcArgs:
        - "-f"
        - "/example_project/example_repo/repo.py"
      port: 3030
```

Installation via Helm, using the overrides above:
```
helm install dagster-example dagster/dagster -f values-override.yaml
```

After dagit starts, use the following run configuration for the example pipeline:
```
execution:
  multiprocess:

intermediate_storage:
  filesystem:
    config:
      base_dir: "/"

solids:
  multiply_the_word:
    config:
      factor: 2
    inputs:
      word: test
```

If you run into any other problems, please feel free to raise an issue or [come straight to our slack](https://dagster-slackin.herokuapp.com/) - I'll be happy to help.
