### ISSUE TITLE
Example for local development environment (Docker-Compose)

### ISSUE THREAD

**Issue by amillette** [dagster-io/dagster#3464]
## Use Case

It would be nice to have an example for local development with Docker-Compose (Dagit / Postgres / etc) with the right environnements variable and configuration in the dagster.yaml. 

## Additional Info

- [Running Dagit as a service](https://docs.dagster.io/deploying/local)

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by gibsondan** [comment]
Totally agree with this - we have a docker-compose example planned for inclusion in our 0.10.0 release in just a couple of weeks.

**Comment by gibsondan** [comment]
This is live now at https://docs.dagster.io/examples/deploy_docker

Feedback welcome!

**Comment by amillette** [comment]
Thanks for this example,

One thing I could suggest is the ability to configure fields in the "config" section of the dagster.yaml file with environment variable. Some fields are not StringSource like the PostgresRunStorage class.

For example we cannot configure the S3ComputeLogManager with environement variable to set the endpoint_url or the bucket:

```
compute_logs:
  module: dagster_aws.s3.compute_log_manager
  class: S3ComputeLogManager
  config:
    endpoint_url: "http://object-storage:9000"
    bucket: "dagster-compute-logs"
    prefix: "dagster-"
```
