### ISSUE TITLE
Proposal: Refactor the K8sRunLauncher to work with multiple executors

### ISSUE THREAD

**Issue by helloworld** [dagster-io/dagster#3512]
## Proposal

Refactor the `K8sRunLauncher` to work with multiple executors and eliminate the `CeleryK8sRunLauncher`

## Current Situation

We currently have two run launchers that enable pipeline execution on K8s: the `K8sRunLauncher` and `CeleryK8sRunLauncher`. 

The `K8sRunLauncher` is typically used with the multiprocess executor, but it can also be used with the in-process executor, We can switch between the two executors by just modifying run config:

```
# instance.yaml

run_launcher:
    module: dagster_k8s
    class: K8sRunLauncher
    config: ...

# run config

executor:
    multiprocess:
```

We plan on having another executor (`K8sExecutor`) that executes each step in its own pod without relying on celery. To use the `K8sExecutor`, the pipeline author would just need to configure it in run config:

```
# instance.yaml

run_launcher:
    module: dagster_k8s
    class: K8sRunLauncher
    config: ...

# run config

executor:
    k8s_executor: ...
```

This is quite nice because pipeline authors can decide on a per-pipeline basis which executor they would like to use. 

The `CeleryK8sRunLauncher`, however, can only be used with the `CeleryK8sExecutor`. If you decide to configure your production instance to use the `CeleryK8sRunLauncher`, there are a few consequences:

1. Every pipeline needs to have a mode with the `CeleryK8sExecutor` and a preset that configures it
2. You cannot run pipelines that don't have a mode with the `CeleryK8sExecutor`. This executor is not suitable for all pipelines, since execution requires the heavyweight process of creating a celery task and k8s pod for every step.

It could be argued that (2) could be desired in certain cases, and a platform team may want to fix or restrict the executors that can be in production. However, this restriction shouldn't be forced as a result of choosing a run launcher, but should rather be an instance-level configuration option. For example, you could pass config to the run launcher in your production instance that whitelists certain executors. 

```
# instance.yaml

run_launcher:
    module: dagster_k8s
    class: K8sRunLauncher
    config:
         whitelisted_executors: ...
```

## Implementation

Instead of having a separate `CeleryK8sRunLauncher`, refactor the `K8sRunLauncher` so that you can use the `CeleryK8sExecutor` with it. That means with the single `K8sRunLauncher`, you can use:

- `InProcessExecutor`
- `MultiprocessExecutor` 
- The upcoming `K8sExecutor`
- `CeleryK8sExecutor`

You should also be able to freely switch between them on a per-pipeline basis. 

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.
