### ISSUE TITLE
helm deploy fails with: userDeployments.deployments.0: replicaCount is required

### ISSUE THREAD

**Issue by mrdavidlaing** [dagster-io/dagster#3546]
## Summary

Naively following the [Deploying to K8s docs](https://docs.dagster.io/deploying/k8s#default-deployment) lead me to try to use my own user code similar to the following (essentially I'm just replacing existing values)

```
userDeployments:
  enabled: true
  deployments:
    - name: "my-user-code-1"
      image:
        repository: "eu.gcr.io/my_proj/my_dagster_image"
        tag: latest
        pullPolicy: Always
      dagsterApiGrpcArgs:
        - "-f"
        - "/my_repo/repo.py"
      port: 3030
```

Using this results in the following error when running `helm install -f values.yaml`:

```
Error: UPGRADE FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
dagster:
- userDeployments.deployments.0: replicaCount is required
```

Adding `replicaCount: 1` to my values.yaml fixed the problem; but seems like unnecessary config friction

```
userDeployments:
  enabled: true
  deployments:
    - name: "my-user-code-1"
       replicaCount: 1
      image:
         ...snip...
```

## Suggested fixes:

1.  [PREFERRED] Change the helm chart schema so that `replicaCount: 1` is the default (and thus not required unless you want to change it), or
1.  Change the config snipped in the [docs](https://docs.dagster.io/deploying/k8s#default-deployment) to include  `replicaCount: 1`

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.
