### ISSUE TITLE
S3ComputeLogManager makes steps take for 60 seconds longer to complete than LocalComputeLogManager

### ISSUE THREAD

**Issue by amillette** [dagster-io/dagster#3565]
## Summary
Whenever I run a pipeline with the S3ComputeLogManager, the pipeline is taking 60 secondes longer than the LocalComputeLogManager. Maybe waiting for the connection to close ?

## Reproduction
Here's the example I am using:
```
from dagster import pipeline, repository, schedule, solid


@solid
def hello(_):
    return 1


@pipeline
def my_pipeline():
    hello()


@schedule(cron_schedule="* * * * *", pipeline_name="my_pipeline", execution_timezone="America/Toronto")
def my_schedule(_context):
    return {}


@repository
def my_repository():
    return [my_pipeline, my_schedule]
```

## Dagit UI/UX Issue Screenshots
![localhost_3000_instance_runs_c2d7ecac-6b3e-47dc-ab7c-d8ee6835b1d3](https://user-images.githubusercontent.com/12679869/105247561-fa492980-5b42-11eb-8723-01fb2c2b865b.png)

## Additional Info about Your Environment
dagster.yaml
```
# ==================================================================================================
# Run Storage
# ==================================================================================================
# Controls how the history of runs is persisted. Can be set to SqliteRunStorage (default) or
# PostgresRunStorage.
run_storage:
  module: dagster_postgres.run_storage
  class: PostgresRunStorage
  config:
    postgres_db:
      username:
        env: DAGSTER_POSTGRES_USERNAME
      password:
        env: DAGSTER_POSTGRES_PASSWORD
      hostname:
        env: DAGSTER_POSTGRES_HOSTNAME
      db_name:
        env: DAGSTER_POSTGRES_DATABASE
      port: 5432

# ==================================================================================================
# Event Log Storage
# ==================================================================================================
# Controls how the structured event logs produced by each run are persisted. Can be set to
# SqliteEventLogStorage (default) or PostgresEventLogStorage.
event_log_storage:
  module: dagster_postgres.event_log
  class: PostgresEventLogStorage
  config:
    postgres_db:
      username:
        env: DAGSTER_POSTGRES_USERNAME
      password:
        env: DAGSTER_POSTGRES_PASSWORD
      hostname:
        env: DAGSTER_POSTGRES_HOSTNAME
      db_name:
        env: DAGSTER_POSTGRES_DATABASE
      port: 5432

# ==================================================================================================
# Scheduler
# ==================================================================================================
# Provides an optional scheduler which controls execution of pipeline runs at regular intervals.
# We recommend using the default DagsterDaemonScheduler - SystemCronScheduler and K8sScheduler are
# also available but are deprecated.
scheduler:
  module: dagster.core.scheduler
  class: DagsterDaemonScheduler

# ==================================================================================================
# Schedule Storage
# ==================================================================================================
# Controls the backing storage used by the scheduler to manage the state of schedules and persist
# records of attempts.
schedule_storage:
  module: dagster_postgres.schedule_storage
  class: PostgresScheduleStorage
  config:
    postgres_db:
      username:
        env: DAGSTER_POSTGRES_USERNAME
      password:
        env: DAGSTER_POSTGRES_PASSWORD
      hostname:
        env: DAGSTER_POSTGRES_HOSTNAME
      db_name:
        env: DAGSTER_POSTGRES_DATABASE
      port: 5432

# ==================================================================================================
# Run Launcher
# ==================================================================================================
# Component that determines where runs are executed.
run_launcher:
  module: dagster_docker
  class: DockerRunLauncher
  config:
    env_vars:
      - DAGSTER_POSTGRES_USERNAME
      - DAGSTER_POSTGRES_PASSWORD
      - DAGSTER_POSTGRES_HOSTNAME
      - DAGSTER_POSTGRES_DATABASE
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    network: project_default

# ==================================================================================================
# Run Coordinator
# ==================================================================================================
# Determines the policy used to determine the prioritization rules and concurrency limits for runs.
# Can be set to DefaultRunCoordinator (default) or QueuedRunCoordinator when you want to maintain
# limits on the number of runs that can be executing at once.
run_coordinator:
  module: dagster.core.run_coordinator
  class: QueuedRunCoordinator

# ==================================================================================================
# Compute Log Storage
# ==================================================================================================
# Controls the capture and persistence of raw stdout & stderr text logs.
#
# Currently supported:
# - LocalComputeLogManager (default)
# - AzureBlobComputeLogManager
# - S3ComputeLogManager
compute_logs:
  module: dagster_aws.s3.compute_log_manager
  class: S3ComputeLogManager
  config:
    endpoint_url: "http://object-storage:9000"
    bucket: "dagster-compute-logs"
    prefix: "dagster-"

# ==================================================================================================
# Local Artifact Storage
# ==================================================================================================
# Controls where to store data on the local disk. Primarily used for storing schedule metadata.
#
# Currently only supports LocalArtifactStorage.
local_artifact_storage:
  module: dagster.core.storage.root
  class: LocalArtifactStorage
  config:
    base_dir: "/var/shared/dagster"

# ==================================================================================================
# Telemetry
# ==================================================================================================
# Allows opting out of Dagster collecting usage statistics. See
# https://docs.dagster.io/install#telemetry for more details.
telemetry:
  enabled: false
```

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.
