### ISSUE TITLE
Expose docs / config options to get around DockerHub 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit.

### ISSUE THREAD

**Issue by mrdavidlaing** [dagster-io/dagster#3584]
## Use Case
Whilst working through the K8s Helm deploy docs - https://docs.dagster.io/deploying/k8s - to deploy an instance of Dagster on a K8s cluster *inside* my corporate network; I ran into a bunch of issues related to DockerHub Rate Limiting.

Specifically, the errors encountered were of the form:

```
Failed to pull image "dagster/k8s-dagit": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/dagster/k8s-dagit:latest": failed to copy: httpReaderSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/dagster/k8s-dagit/manifests/sha256:d6a6badb2b...snip...
 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

For the following images:

- dagster/k8s-dagit
- dagster/k8s-celery-worker
- dagster/k8s-dagit-example
- dagster/k8s-example
- postgres:9.6.16
- rabbitmq:3.8.2-debian-9-r35
- bitnami/minideb:stretch
- busybox:1.28

### Solution idea 1:

If your company runs a "dockerhub-cache" (like mine does); it might be possible to edit all the image references in the helm values.yaml to "fully qualify" the image references.  eg:

- dagster/k8s-dagit -> corp-repo.mycompany.com/dockerhub-proxy-cache/dagster/k8s-dagit 
- dagster/k8s-celery-worker -> corp-repo.mycompany.com/dockerhub-proxy-cache/dagster/k8s-celery-worker
- dagster/k8s-dagit-example -> corp-repo.mycompany.com/dockerhub-proxy-cache/dagster/k8s-dagit-example
- dagster/k8s-example -> corp-repo.mycompany.com/dockerhub-proxy-cache/dagster/k8s-example

Changing the image path for the embedded postgres and rabbitmq charts seems to be possible using `(postgresql|rabbitmq).image.registry`; referencing `library/postgres` rather than just `postgres`.

`bitnami/minideb:stretch` is used by the rabbitmq chart; its image path can be changed via `rabbitmq.volumePermissions.image.registry`

I couldn't figure out a way to change the image paths for `busybox:1.28`

If it is possible to configure everything already; Solution 1 might be to just document clearly which `image` settings to change

### Solution idea 1.a:
Similar to solution 1; but avoid "default" image locations and use a single top level config setting:

`images.registry: registry-1.docker.io/v2/` 

which could be changed to `corp-repo.mycompany.com/dockerhub-proxy-cache/`.

### Solution idea 2:

Publish all needed images to some where other than Dockerhub with higher rate limits.

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by mrdavidlaing** [comment]
As an interim (partial) solution; its possible to specify a dockerhub-cache via the following changes to `values.yaml`

```yaml
dagit:
  image:
    repository: "corp-repo.mycompany.com/dockerhub-proxy-cache/dagster/k8s-dagit-example"

dagsterDaemon:
  image:
    repository: "corp-repo.mycompany.com/dockerhub-proxy-cache/dagster/k8s-dagit"

pipelineRun:
  image:
    repository: "corp-repo.mycompany.com/dockerhub-proxy-cache/dagster/k8s-example"

runLauncher:
  config:
    celeryK8sRunLauncher:
      image:
        repository: "corp-repo.mycompany.com/dockerhub-proxy-cache/dagster/k8s-celery-worker"

postgresql:
  image:
    repository: "corp-repo.mycompany.com/dockerhub-proxy-cache/library/postgres"
  volumePermissions:
    # for the bitnami/minideb:stretch image used by the postgres sub-chart in the init-chmod-data Init Container
    image:
      registry: "harbor-repo.vmware.com/dockerhub-proxy-cache"
    
rabbitmq:
  image:
    registry: "corp-repo.mycompany.com/dockerhub-proxy-cache"
  volumePermissions:
   # for the bitnami/minideb:stretch image used by the rabbitmq sub-chart in the volume-permissions Init Container
    image:
      registry: "corp-repo.mycompany.com/dockerhub-proxy-cache"

flower:
  image:
    repository: "corp-repo.mycompany.com/dockerhub-proxy-cache/mher/flower"

```

I don't think its currently possible to change the image path for the `busybox:1.28` container used by the Dagit Deployment to check the status of `userDeployments` via the `init-user-deployment-{name}` Init Container given the hard-coding in https://github.com/dagster-io/dagster/blob/master/helm/dagster/templates/deployment-dagit.yaml#L49

**Comment by catherinewu** [comment]
related: https://github.com/dagster-io/dagster/issues/3628

**Comment by catherinewu** [comment]
another alternative is amazon's public docker registry https://gallery.ecr.aws

for reference, this is aws's warning when docker introduced the rate limit: https://aws.amazon.com/blogs/containers/advice-for-customers-dealing-with-docker-hub-rate-limits-and-a-coming-soon-announcement/

**Comment by mrdavidlaing** [comment]
@catherinewu / @mgasner Can I help implement the solution you choose?

**Comment by catherinewu** [comment]
@mrdavidlaing thank you! i'll defer to @mgasner who is starting to work on this soon!

**Comment by mgasner** [comment]
@mrdavidlaing would love your eyes on https://dagster.phacility.com/D6671

**Comment by mgasner** [comment]
https://dagster.phacility.com/D6677

**Comment by catherinewu** [comment]
@mgasner is this good to close now?

**Comment by mrdavidlaing** [comment]
To use a docker registry proxy/cache with v0.13.8 of the chart you need to:

1.  Search and replace all instances of `docker.io` in `values.yaml` with your `corp-repo.mycompany.com/dockerhub-proxy-cache`
2.  Make sure the `postgresql:` section contains the following:
```
postgresql:
  image:
    registry: ~  # This must be ~ (ie, NULL)
    repository: "corp-repo.mycompany.com/dockerhub-proxy-cache/library/postgres"
  volumePermissions:
    # for the bitnami/minideb:stretch image used by the postgres sub-chart in the init-chmod-data Init Container
    image:
      registry: "corp-repo.mycompany.com/dockerhub-proxy-cache"
```
2. Make sure the `busybox:` section contains the following (note the additional `library/` in the path to `busybox`)
```
busybox:
  image:
    repository: "corp-repo.mycompany.com/dockerhub-proxy-cache/library/busybox"
```
