### ISSUE TITLE
GCSComputeLogManager not working on k8s (missing module dagster_gcp)

### ISSUE THREAD

**Issue by amarrella** [dagster-io/dagster#3661]
## Summary

If I set my helm `values.yaml` as following:
```yaml
computeLogManager:
  type: GCSComputeLogManager
  config: 
    gcsComputeLogManager:
      bucket: <REDACTED>
      prefix: dagster/logs/
```

dagit and the celery workers refuse to start, complaining that `dagster_gcp` is missing. 
As a workaround, I could build a new docker image, but I think it would be better to fix upstream.

## Reproduction

Deploy dagster to k8s with the provided helm chart and the setting above.

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.
