### ISSUE TITLE
Deprecate "existing" cluster type for Dask executors

### ISSUE THREAD

**Issue by kinghuang** [dagster-io/dagster#3854]
#3835 will unify the Dask configuration for executors and resources. The executor will gain the same client configuration options as resources currently have. As such, specifying a pre-existing Dask cluster for executors should be done by specifying the client address instead of the `existing` cluster config, which is not an actual Dask cluster type.

The `existing` option was added in Dagster 0.9.17.

**Deprecated Executor "existing" Cluster Config**:

```yaml
config:
  cluster:
    existing:
      address: "tcp://127.0.0.1:8786"
```

**Replace with Client Config**:

```yaml
config:
  client:
    address: "tcp://127.0.0.1:8786"
```
