### ISSUE TITLE
Users should be able to be specify a default for StringSource config values

### ISSUE THREAD

**Issue by helloworld** [dagster-io/dagster#4142]
## Summary

When using `StringSource`, it would be very nice if users could specify a default value to be used if the environment variable did not exist. This is useful to expose behavior where default can be overridden with an environment variable. 

For example:

```
run_storage:
  module: dagster_postgres.run_storage
  class: PostgresRunStorage
  config:
    should_autocreate_tables: false
    postgres_db:
      hostname: 
        env: POSTGRES_TEST_DB_HOST
        default: localhost
      username: postgres_user
      password: postgres_password
      db_name: postgres_db
      port: 5432
```

I would like the default `postgres_db.hostname` value to be `localhost`, but allow it to be overridden by specifying an environment variable.

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.
