### ISSUE TITLE
Allow config maps to be mounted as file volumes

### ISSUE THREAD

**Issue by Oliver-Sellwood** [dagster-io/dagster#4147]
## Use Case

This will allow users to generate yml preset definitions that can then be loaded using the `PresetDefinition.from_files` API. This will help to reduce config in the code.

## Additional Info

This feature discussed further [here](https://dagster.slack.com/archives/C014N0PK37E/p1620010553130200) 

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by sryza** [comment]
Hey @Oliver-Sellwood - thanks for the suggestion.  Do you have specific ideas on how you imagine this experience would look?

**Comment by Oliver-Sellwood** [comment]
Hi, not sure exactly but maybe something like...
```
configVolumeMounts:
    - configName: pipeline-config
      mountPath: /opt/config/pipeline1
    - configName: pipeline2-config
      mountPath: /opt/config/pipeline2
```
I think you would need these options on at least dagster user deployments and the dagster daemon.

Is this what you mean?
