### ISSUE TITLE
dagster do not wait for last run logs from databricks cluster

### ISSUE THREAD

**Issue by andgineer** [dagster-io/dagster#4148]
## Summary
I launch Spark solid using databricks_pyspark_step_launcher
In dagster logs it shows logs downloaded from databricks cluster after running pyspark task on it.
But the logs that dagster download are old one - from previous run.

As I understand dagster should wait for some time(?) to get newest logs from databricks cluster.

## Reproduction
```
databricks_jobs_mode = ModeDefinition(
    name="databricks",
    resource_defs={
        "spark_cluster": databricks_pyspark_step_launcher,
        "spark": pyspark_resource,
        "s3": s3_resource,
        "io_manager": atomic_spark_io_manager,
    },
    logger_defs={"console": colored_console_logger},
)

@solid(
    required_resource_keys={"spark", "io_manager", "spark_cluster"},
)
def health_check(context: SolidExecutionContext):
    spark_session: SparkSession = context.resources.spark.spark_session
    myRange = spark_session.range(1000).toDF("number")
    context.log.info(f"Number of partitions: {myRange.rdd.getNumPartitions()}")
```

```
loggers:
  console:
    config:
      log_level: DEBUG

resources:
  io_manager:
    config:
      base_dir: "s3a://****/dagster_work/"
      source_version: "version_1"

  spark_cluster:
    config:
      run_config:
        cluster:
          existing: 0325-073316-gears115
      local_pipeline_package_path: '.'
      databricks_host: 'https://*****.databricks.com'
      wait_for_logs: true
      databricks_token:
        env: 'DATABRICKS_TOKEN'
      secrets_to_env_variables:
        - key: databricks_token
          name: DATABRICKS_TOKEN
          scope:  ****
      storage:
        s3:
          secret_scope: ****
          access_key_key: aws_key
          secret_key_key: aws_secret

  spark:
    config:
      spark_conf:
        spark:
          sql:
            broadcastTimeout: 36000
          executor:
            memoryOverhead: "1G"
          driver:
            memory: "1G"
```

## Dagit UI/UX Issue Screenshots
This is 9:54 run that shows only logs from 9:46 previous run
![Screenshot 2021-05-07 at 10 07 52](https://user-images.githubusercontent.com/1568089/117411374-2afb7600-af1c-11eb-92b7-7b346a63f720.png)

## Additional Info about Your Environment
dagster 0.11.7
running in AWS ECS container

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.
