### ISSUE TITLE
impossible to use env vars in databricks configuration

### ISSUE THREAD

**Issue by andgineer** [dagster-io/dagster#4151]
## Summary
```
resources:
  spark_cluster:
    config:
      run_config:
        cluster:
          existing:
            env: 'DATABRICKS_CLUSTER_ID'
      local_pipeline_package_path: '.'
      databricks_host:
        env: 'DATABRICKS_HOST'
```

```
   Error 1: Invalid scalar at path root:resources:spark_cluster:config:run_config:cluster:existing. Value "{'env': 'DATABRICKS_CLUSTER_ID'}" of type "<class 'dict'>" is not valid for expected type "String".
```

## Reproduction
Use env vars in the databricks resources

## Dagit UI/UX Issue Screenshots
N/A

## Additional Info about Your Environment
dagster 0.11.7

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.
