### ISSUE TITLE
SynchronousExecutionManager does not stream logs to frontend

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#429]
Logs are delivered all at once, after pipeline execution is complete.

Steps to reproduce:
1. Run dagit using the SynchronousExecutionManager (`dagit --sync`) in dagster/python_modules/airline_demo
2. Execute the download pipeline (http://127.0.0.1:3000/airline_demo_download_pipeline/execute) using  the following config:

```
# This is config editor. Enjoy!

context:
  local:
    resources:
      db_info:
        config:
          postgres_username: test
          postgres_password: test
          postgres_hostname: localhost
          postgres_db_name: test
solids:
  archive_members:
    config:
    - On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2018_4.csv
    - On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2018_5.csv
    - On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2018_6.csv
    - Origin_and_Destination_Survey_DB1BCoupon_2018_2.csv
    - Origin_and_Destination_Survey_DB1BMarket_2018_2.csv
    - Origin_and_Destination_Survey_DB1BTicket_2018_2.csv
    - 954834304_T_MASTER_CORD.csv
  download_archives:
    config:
    - bucket: dagster-airline-demo-source-data
      key: test/On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2018_4.zip
      skip_if_present: true
      target_path: source_data/On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2018_4.zip
    - bucket: dagster-airline-demo-source-data
      key: test/On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2018_5.zip
      skip_if_present: true
      target_path: source_data/On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2018_5.zip
    - bucket: dagster-airline-demo-source-data
      key: test/On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2018_6.zip
      skip_if_present: true
      target_path: source_data/On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2018_6.zip
    - bucket: dagster-airline-demo-source-data
      key: test/Origin_and_Destination_Survey_DB1BCoupon_2018_2.zip
      skip_if_present: true
      target_path: source_data/Origin_and_Destination_Survey_DB1BCoupon_2018_2.zip
    - bucket: dagster-airline-demo-source-data
      key: test/Origin_and_Destination_Survey_DB1BMarket_2018_2.zip
      skip_if_present: true
      target_path: source_data/Origin_and_Destination_Survey_DB1BMarket_2018_2.zip
    - bucket: dagster-airline-demo-source-data
      key: test/Origin_and_Destination_Survey_DB1BTicket_2018_2.zip
      skip_if_present: true
      target_path: source_data/Origin_and_Destination_Survey_DB1BTicket_2018_2.zip
    - bucket: dagster-airline-demo-source-data
      key: test/954834304_T_MASTER_CORD.zip
      skip_if_present: true
      target_path: source_data/954834304_T_MASTER_CORD.zip
  download_q2_sfo_weather:
    config:
    - bucket: dagster-airline-demo-source-data
      key: test/sfo_q2_weather.txt
      skip_if_present: true
      target_path: source_data/sfo_q2_weather.txt
  unzip_archives:
    config:
      destination_dir: source_data
      skip_if_present: true
```
