### ISSUE TITLE
Redis Password in Helm chart

### ISSUE THREAD

**Issue by ibegleris** [dagster-io/dagster#4316]
## Summary
Dagster uses Bitami's Helm chart when deploying with Redis instead of RabbitMQ.
In recent versions, though Redis requires a password for authentication unless ` usePassword: false` is set within Redis

## Reproduction
Try and deploy Dagster chart with:
```
  redis:
    enabled: true
    internal: true
    nameOverride: dagster-redis
    host: "dagster-redis-master"
```
The celery workers will complain saying they can't connect to the Redis because of authentication issues.

I recommend the chart be set with `usePassword: false` by default along with a comment to state what needs to be done to work with a password.

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.
