### ISSUE TITLE
[HELM] imagePullSecrets not propagated to dagster-user-deployments

### ISSUE THREAD

**Issue by gjeusel** [dagster-io/dagster#4339]
## Summary

The helm chart indeed works for a standalone user-deployment:
> helm install etl-project-x dagster/dagster-user-deployments -f project-x-values.yaml --dry-run

Although it is not working when not deploying user code in a separate Helm release.
> helm install etl-master dagster/dagster -f values.yaml --dry-run

Meaning, I did filled the `imagePullSecrets` to deploy with dagster/dagster helm chart, but it was not propagated to the generated dagster-user-deployments. Altough it was propagated everywhere else.

## Reproduction
<details>
<summary>values.yaml</summary>

```yaml
imagePullSecrets:
  - name: gitlab-docker-registry

# ______ User Code Deployments ______
dagster-user-deployments:
  enabled: true
  deployments:
    - name: "project-x"
      image:
        repository: "registry.gitlab.com/renewex/project-x"
```
</details>

## Additional Info about Your Environment
```
λ helm version
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.16.5"}

λ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:19:55Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
```

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.
