### ISSUE TITLE
[HELM] add warning on using another namespace for jobs and scheduler regarding ServiceAccount rights

### ISSUE THREAD

**Issue by gjeusel** [dagster-io/dagster#4340]

**Comment by rexledesma** [comment]
@gjeusel The title of this is vague. Could you use one of the issue templates to better describe the problem that you're dealing with, and a potential way to resolve?

**Comment by gjeusel** [comment]
My bad,

## What content is missing

While deploying using the Helm chart, I was surprised by the missing rights on the ServiceAccount created by the chart to be able to run kubernetes jobs inside another namespace.

```yaml
runLauncher:
  type: K8sRunLauncher
  config:
    k8sRunLauncher:
      # The K8s namespace where new jobs will be launched.
      # By default, the release namespace is used.
      jobNamespace: etl-jobs

serviceAccount:
  create: true
```

Just adding a little commentary in the values might help !
```yaml
runLauncher:
  type: K8sRunLauncher
  config:
    k8sRunLauncher:
      # The K8s namespace where new jobs will be launched.
      # By default, the release namespace is used.
      # If using a different namespace, mind to provide a service account
      # with rights to launch jobs in the selected namespace.
      jobNamespace: etl-jobs

serviceAccount:
  create: false

global:
  serviceAccountName: "etl-master-cross-namespace"
```

## Type of the content
- Comment in the Helm chart values

---
#### Message from the maintainers:
Are you looking for the same documentation content? Give it a :thumbsup:. We factor engagement into prioritization.
