### ISSUE TITLE
dagster.core.errors.DagsterImportError: Encountered ImportError: `cannot import name 'DtypeArg' from 'pandas._typing'

### ISSUE THREAD

**Issue by galloramiro** [dagster-io/dagster#4368]
## Summary
We have a proyect working with a dagit image, dagster-daemon image and a lot of tasks.  
But on the last deploy we start to have and error that we cant replicate on local:

```bash
scrappers_web_tasks    |   File "/usr/local/lib/python3.8/site-packages/dagster/grpc/server.py", line 98, in load
scrappers_web_tasks    |     self._loadable_repository_symbols = load_loadable_repository_symbols(
scrappers_web_tasks    |   File "/usr/local/lib/python3.8/site-packages/dagster/grpc/server.py", line 122, in load_loadable_repository_symbols
postgresql_db          | waiting for server to shut down....2021-07-16 11:47:49.801 UTC [48] LOG:  aborting any active transactions
postgresql_db          | 2021-07-16 11:47:49.805 UTC [48] LOG:  background worker "logical replication launcher" (PID 55) exited with exit code 1
postgresql_db          | 2021-07-16 11:47:49.806 UTC [50] LOG:  shutting down
scrappers_web_tasks    |     loadable_targets = get_loadable_targets(
scrappers_web_tasks    |   File "/usr/local/lib/python3.8/site-packages/dagster/grpc/utils.py", line 25, in get_loadable_targets
scrappers_web_tasks    |     else loadable_targets_from_python_file(python_file, working_directory)
scrappers_web_tasks    |   File "/usr/local/lib/python3.8/site-packages/dagster/cli/workspace/autodiscovery.py", line 11, in loadable_targets_from_python_file
postgresql_db          | 2021-07-16 11:47:49.847 UTC [48] LOG:  database system is shut down
scrappers_web_tasks    |     loaded_module = load_python_file(python_file, working_directory)
scrappers_web_tasks    |   File "/usr/local/lib/python3.8/site-packages/dagster/core/code_pointer.py", line 109, in load_python_file
scrappers_web_tasks    |     raise DagsterImportError(
scrappers_web_tasks    | dagster.core.errors.DagsterImportError: Encountered ImportError: `cannot import name 'DtypeArg' from 'pandas._typing' (/usr/local/lib/python3.8/site-packages/pandas/_typing.py)` while importing module repositories from file /scrape_web_tasks/src/task_manager/repositories.py. Local modules were resolved using the working directory `/scrape_web_tasks`. If another working directory should be used, please explicitly specify the appropriate path using the `-d` or `--working-directory` for CLI based targets or the `working_directory` configuration option for `python_file`-based workspace.yaml targets.
```

## Reproduction

We dont know how to reproduce this.

## Dagit UI/UX Issue Screenshots

![Screenshot from 2021-07-16 10-00-34](https://user-images.githubusercontent.com/25160187/125951816-9fd9bdd0-7a66-4a15-92b6-7ab65afbb86e.png)

## Additional Info about Your Environment
**Dockerfile**
```DockerFile
FROM python:3.8-slim-buster
ENV PYTHONUNBUFFERED=1

RUN apt-get update


# Set general dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    libgflags-dev \
    libsnappy-dev \
    zlib1g-dev \
    libbz2-dev \
    liblz4-dev \
    librocksdb-dev \
    libzstd-dev \
    cron \
    wget \
    xvfb \
    unzip \
    unixodbc \
    gcc \
    g++ \
    gnupg \
    gnupg1 \
    gnupg2 \
    unixodbc-dev \
    freetds-dev \
    freetds-bin \
    tdsodbc \
    tzdata \
    python3-dev \
    && pip install --upgrade pip


# Set up chrome dependencies
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
RUN apt-get update -y
RUN apt-get install -y google-chrome-stable

# Add SQL Server ODBC Driver 17
RUN apt-get install curl \
    && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update
RUN ACCEPT_EULA=Y apt-get install -y --allow-unauthenticated msodbcsql17 \
    mssql-tools \
    libgssapi-krb5-2

RUN echo "[FreeTDS]\n\
Description = FreeTDS Driver\n\
Driver = /usr/lib/x86_64-linux-gnu/odbc/libtdsodbc.so\n\
Setup = /usr/lib/x86_64-linux-gnu/odbc/libtdsS.so" >> /etc/odbcinst.ini

RUN chmod +rwx /etc/ssl/openssl.cnf
RUN sed -i 's/TLSv1.2/TLSv1.0/g' /etc/ssl/openssl.cnf
RUN sed -i 's/SECLEVEL=2/SECLEVEL=1/g' /etc/ssl/openssl.cnf


# Install fbprophet
RUN pip install --upgrade setuptools
RUN pip install lxml
RUN pip install Cython==0.29.15
RUN pip install numpy==1.18.1
RUN pip install pystan==2.19.1.1
RUN pip install fbprophet==0.7.1
RUN pip install zeep==4.0.0


# SAP by Pyrfc
# configure SAP NW RFC SDK files path
ENV SAPNWRFC_HOME=/usr/local/sap/nwrfcsdk
COPY nwrfc_sdk/nwrfcsdk.conf /etc/ld.so.conf.d/nwrfcsdk.conf
# copy SAP NW RFC SDK files
COPY nwrfc_sdk/nwrfcsdk $SAPNWRFC_HOME
# Install Pyrfc
RUN pip --no-cache-dir install https://github.com/SAP/PyRFC/releases/download/v2.4.1/pyrfc-2.4.1-cp38-cp38-linux_x86_64.whl


# Create the workdir
WORKDIR scrape_web_tasks

CMD mkdir scrape_web_tasks/src
COPY requirements.txt src/
RUN pip install -r src/requirements.txt


# Clear dependencies
RUN apt-get remove -y --purge \
    gcc \
    g++ \
# clear apt-get cache & remove unnecessary files
    && apt-get -y autoremove \
    && apt-get clean && rm -rf /var/lib/apt/lists/*


ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV SRCDIR "/scrape_web_tasks/src/"
ENV DAGSTER_HOME "${SRCDIR}"
ENV PYTHONPATH "${SRCDIR}"
ENV LC_ALL=es_AR.utf8
ENV LANG=es_AR.utf8
ENV LANGUAGE=es_AR.utf8
ENV TZ=America/Argentina/Buenos_Aires

```
**docker-compose.yml**
```yml
version: "3.8"

services:
  chrome:
    image: selenium/standalone-chrome:latest
    container_name: chrome
    hostname: chrome
    networks:
      - web
    privileged: true
    shm_size: 2G
  
  # This service runs the postgres DB used by dagster for run storage, schedule storage,
  # and event log storage.
  postgresql_db:
    image: postgres:11
    container_name: postgresql_db
    environment:
      POSTGRES_USER: ${DAGSTER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DAGSTER_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DAGSTER_POSTGRES_DB}
    networks:
      - dagster-network

  # This service runs the gRPC server that loads and executes your pipelines, in both dagit
  # and dagster-daemon. By setting DAGSTER_CURRENT_IMAGE to its own image, we tell the
  # run launcher to use this same image when launching runs in a new container as well.
  # Multiple containers like this can be deployed separately - each just needs to run on
  # its own port, and have its own entry in the workspace.yaml file that's loaded by dagit.
  scrappers_web_tasks:
    image: scrappers_web_tasks_image
    container_name: scrappers_web_tasks
    environment: 
      DAGSTER_CURRENT_IMAGE: "scrappers_web_tasks_image"
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile.tasks
    volumes:
      - ./src:/scrape_web_tasks/src
    networks:
      - web
      - dagster-network
    depends_on:
      - chrome
    extra_hosts:
      - ${MYSQL_HOST_STRING}
      - ${WAN_SERVER_IP}
  
  # This service runs dagit, which loads the pipelines from the user code container.
  # Since our instance uses the QueuedRunCoordinator, any runs submitted from dagit will be put on
  # a queue and later dequeued and launched by dagster-daemon.
  dagit:
    build:
      context: .
      dockerfile: ./Dockerfile.dagster
    entrypoint:
      - dagit
      - -h
      - "0.0.0.0"
      - -p
      - "3000"
      - -w
      - workspace.yaml
    container_name: dagit
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      DAGSTER_POSTGRES_USER: ${DAGSTER_POSTGRES_USER}
      DAGSTER_POSTGRES_PASSWORD: ${DAGSTER_POSTGRES_PASSWORD}
      DAGSTER_POSTGRES_DB: ${DAGSTER_POSTGRES_DB}
    volumes: # Make docker client accessible so we can terminate containers from dagit
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dagster-network
    depends_on:
      - scrappers_web_tasks
  
  # This service runs the dagster-daemon process, which is responsible for taking runs
  # off of the queue and launching them, as well as creating runs from schedules or sensors.
  dagster-daemon:
    image: dagster-daemon
    build:
      context: .
      dockerfile: Dockerfile.dagster
    entrypoint:
      - dagster-daemon
      - run
    container_name: dagster_daemon
    environment:
      DAGSTER_POSTGRES_USER: ${DAGSTER_POSTGRES_USER}
      DAGSTER_POSTGRES_PASSWORD: ${DAGSTER_POSTGRES_PASSWORD}
      DAGSTER_POSTGRES_DB: ${DAGSTER_POSTGRES_DB}
      DAGSTER_CURRENT_IMAGE: "postgresql_db"
    restart: on-failure
    volumes: # Make docker client accessible so we can launch containers using host docker
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dagster-network
    depends_on:
      - scrappers_web_tasks

networks:
  web:
    external: true
    driver:  bridge
  dagster-network:
    driver: bridge
    name: dagster-network
```
**workspace.yml**
```yml
load_from:
  - grpc_server:
      host: scrappers_web_tasks
      port: 4000
      location_name: "scrappers_web_tasks"
```
**dagster.yml**
```yml
scheduler:
  module: dagster.core.scheduler
  class: DagsterDaemonScheduler

run_coordinator:
  module: dagster.core.run_coordinator
  class: QueuedRunCoordinator

run_storage:
  module: dagster_postgres.run_storage
  class: PostgresRunStorage
  config:
    postgres_db:
      hostname: postgresql_db
      username:
        env: DAGSTER_POSTGRES_USER
      password:
        env: DAGSTER_POSTGRES_PASSWORD
      db_name:
        env: DAGSTER_POSTGRES_DB
      port: 5432

schedule_storage:
  module: dagster_postgres.schedule_storage
  class: PostgresScheduleStorage
  config:
    postgres_db:
      hostname: postgresql_db
      username:
        env: DAGSTER_POSTGRES_USER
      password:
        env: DAGSTER_POSTGRES_PASSWORD
      db_name:
        env: DAGSTER_POSTGRES_DB
      port: 5432

event_log_storage:
  module: dagster_postgres.event_log
  class: PostgresEventLogStorage
  config:
    postgres_db:
      hostname: postgresql_db
      username:
        env: DAGSTER_POSTGRES_USER
      password:
        env: DAGSTER_POSTGRES_PASSWORD
      db_name:
        env: DAGSTER_POSTGRES_DB
      port: 5432

telemetry:
      enabled: false
```
---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.
