### ISSUE TITLE
[Documentation Feedback] Problem on /deployment/guides/docker page

### ISSUE THREAD

**Issue by stuartin** [dagster-io/dagster#4382]
In the **Mounting Volumes** code snippet, the `container_kwargs:` key is not aligned correctly, it should be moved under the `config:` key.

It should be:
```yaml
run_launcher:
  module: dagster_docker
  class: DockerRunLauncher
  config:
    env_vars:
      - DAGSTER_POSTGRES_USER
      - DAGSTER_POSTGRES_PASSWORD
      - DAGSTER_POSTGRES_DB
    container_kwargs:
      volumes:
        - repo.py:/opt/dagster/app/
```
I also found that I had to use an absolute path when defining the `volume` instead of a relative one.
Using an existing named volume, $PWD or relative paths produced an error.
