### ISSUE TITLE
No option to pass external Redis password

### ISSUE THREAD

**Issue by gabrielecalvo** [dagster-io/dagster#4404]
## Use Case
When using the [Advanced Deployment](https://docs.dagster.io/deployment/guides/kubernetes/deploying-with-helm-advanced) with a production-grade external Redis, there is currently no way of passing the password from a k8s secret.

## Ideas of Implementation
Additional configuration parameters could be passed similarly to the [official redis helm chart](https://artifacthub.io/packages/helm/bitnami/redis#redis-tm-common-configuration-parameters).

Perhaps something like:
```yaml
redis:
  enabled: true
  internal: false
  host: <full.url.of.external.hosted.redis>
  auth:
    existingSecret: <name-of-the-k8s-secret>
    existingSecretPasswordKey: <name-of-the-secret-key-eg:REDIS_PRIMARY_ACCESS_KEY>
```

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.
