### ISSUE TITLE
QueuedRunCoordinator  param tag_concurrency_limits not working in 0.12.10

### ISSUE THREAD

**Issue by cwe5590** [dagster-io/dagster#4834]
## Summary

QueuedRunCoordinator param, tag_concurrency_limits, are not working as documented in `0.12.10`. I am able to run as many of the below sleep_graph pipeline as I desire despite the limit.  Downgraded to `0.12.8` and the tag_concurrency_limits are working as described in the documentation with the same example. 

## Reproduction

```
run_coordinator:
  module: dagster.core.run_coordinator
  class: QueuedRunCoordinator
  config:
    max_concurrent_runs: 2
    tag_concurrency_limits:
      - key: "test"
        limit: 1
```

```
@solid
def sleep():
    time.sleep(300)

@pipeline(tags={'test': 'value'})
def sleep_graph():
    sleep()

@repository
def repository() -> List[Any]:
    return [
        sleep_graph,
    ]
```

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.
