### ISSUE TITLE
Helm chart does not allow QueuedRunCoordinator to use applyLimitPerUniqueValue

### ISSUE THREAD

**Issue by abkfenris** [dagster-io/dagster#4880]
## Summary

When using the helm chart to deploy Dagster, trying to use [`applyLimitPerUniqueValue` tag concurrency limit](https://docs.dagster.io/deployment/run-coordinator#applying-concurrency-limits-per-unique-value) with the QueuedRunCoordinator causes the schema validation to fail.

## Reproduction

`applyLimitPerUniqueValue` as a `tagConcurrencyLimits.value` fails, while specifying a single values passes.

Failing helm `values.yaml`:

```yaml
dagsterDaemon:
  runCoordinator:
    enabled: true
    type: QueuedRunCoordinator
    config:
      queuedRunCoordinator:
        tagConcurrencyLimits:
        - key: server-limit-2
          value:
            applyLimitPerUniqueValue: True
          limit: 2
```

Output:

```
Error: values don't meet the specifications of the schema(s) in the following chart(s): 
dagster: 
- dagsterDaemon.runCoordinator.config.queuedRunCoordinator: 
  - Must validate at least one schema (anyOf) 
  - dagsterDaemon.runCoordinator.config.queuedRunCoordinator.tagConcurrencyLimits.0.value: 
    - Must validate at least one schema (anyOf) 
    - dagsterDaemon.runCoordinator.config.queuedRunCoordinator.tagConcurrencyLimits.0.value: 
      - Invalid type. Expected: string, given: object
```

Passing helm `values.yaml`:

```yaml
dagsterDaemon:
  runCoordinator:
    enabled: true
    type: QueuedRunCoordinator
    config:
      queuedRunCoordinator:
        tagConcurrencyLimits:
        - key: server-limit-2
          value: ncei
          limit: 2
```

## Additional Info about Your Environment

- Kubernetes 1.21 on Digital Ocean
- Chart revision 0.12.11
- Deployed with Argo CD 2.1.2+7

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.
