### ISSUE TITLE
Op selection isn't working in Launchpad

### ISSUE THREAD

**Issue by yuhan** [dagster-io/dagster#5585]
## Summary
slack convo: https://dagster.slack.com/archives/C01U954MEER/p1636120679460900

repro:
```
@job
def foo():
    @op
    def op_1():
        return 1

    @op
    def op_2():
        return 1

    @op
    def op_with_2_ins(in_1, in_2):
        return in_1 + in_2

    op_with_2_ins(op_1(), op_2())
```
yaml:
```
ops:
  op_with_2_ins:
    inputs:
      in_2: 
        value: "aa"
```

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.
