### ISSUE TITLE
Asset Dashboard fails for Folder View with characters differ from Latin and Chinese (?) in AssetKey

### ISSUE THREAD

**Issue by dinya** [dagster-io/dagster#5795]
Asset Dashboard fails for Folder View with characters differ from Latin and Chinese (?) in AssetKey

Code:

```python

from dagster import op, job, Output, AssetMaterialization, AssetKey

@op
def op0():
    yield AssetMaterialization(asset_key=AssetKey(["Hi", "嗨。", "Zdraví", "हाय", "Здоров", "Привет", "item0"]))
    yield Output(None)


@job
def process_record_job():
    op0()
```

1. Run log [✔️]
![0 run log](https://user-images.githubusercontent.com/2182222/143574749-30f2976c-0443-4ea7-b13b-db436dd7dccb.jpg)

2. After click on Vew Asset from run log [✔️]
![1 click on View asset](https://user-images.githubusercontent.com/2182222/143574751-8437baaf-adbe-4ec1-b13d-837dd1af648c.jpg)

3. In Asset Dashboard with List View [✔️]
![2 asset dashboard list view](https://user-images.githubusercontent.com/2182222/143575072-17e2f1ac-349a-43b3-8201-2e8c77159be2.jpg)

4. In Asset Dashboard with Folder View [❌]. Maybe URL generator problem?
![3 asset dashboard folder view](https://user-images.githubusercontent.com/2182222/143575075-7d923d93-4301-418f-94a3-822e451700a7.jpg)

**Comment by hellendag** [comment]
Thanks for the code snippet, it's very helpful! Unfortunately, I'm not able to repro this in master -- perhaps this was fixed since 0.13.8.

Can you provide the exact URL path that you are using when you see the broken asset page (4)?

**Comment by dinya** [comment]
@hellendag 

> Can you provide the exact URL path that you are using when you see the broken asset page (4)?

I assume you run you instance with SQLite as a backend database. Default env with SQLite is ok for me too:.

![](https://user-images.githubusercontent.com/2182222/144024422-f784c02d-c2fc-4cf9-a886-78bb6facccbe.png)

But __*my bad*__. I didn't provide my ``dagster.yaml``. I use PostgreSQL:

```yaml
run_storage:
  module: dagster_postgres.run_storage
  class: PostgresRunStorage
  config:
    postgres_db:
      username:
        env: DAGSTER_PG_USERNAME
      password:
        env: DAGSTER_PG_PASSWORD
      hostname:
        env: DAGSTER_PG_HOST
      db_name:
        env: DAGSTER_PG_DB
      port: 5432

event_log_storage:
  module: dagster_postgres.event_log
  class: PostgresEventLogStorage
  config:
    postgres_db:
      username:
        env: DAGSTER_PG_USERNAME
      password:
        env: DAGSTER_PG_PASSWORD
      hostname:
        env: DAGSTER_PG_HOST
      db_name:
        env: DAGSTER_PG_DB
      port: 5432

schedule_storage:
  module: dagster_postgres.schedule_storage
  class: PostgresScheduleStorage
  config:
    postgres_db:
      username:
        env: DAGSTER_PG_USERNAME
      password:
        env: DAGSTER_PG_PASSWORD
      hostname:
        env: DAGSTER_PG_HOST
      db_name:
        env: DAGSTER_PG_DB
      port: 5432

telemetry:
  enabled: false
```

As result 

![](https://user-images.githubusercontent.com/2182222/144023842-723e6cf0-99b6-4811-8cec-8a55d62c9726.png)

So I guess the problem is primarily in ``dragster_postgres``?
