### ISSUE TITLE
The log handler level not effect

### ISSUE THREAD

**Issue by lambdaTW** [dagster-io/dagster#6075]
## Summary

When I set the customize log handler with the level it doesn't work.

## Reproduction

1. Setup the `dagster.yaml`
```yaml
python_logs:
  managed_python_loggers:
    - root
  python_log_level: INFO
  dagster_handler_config:
    handlers:
      newrelicHandler:
        class: logit.FileHandler
        level: INFO
        filename: "/opt/dagster/app/log/dagster_logs.log"
        mode: "a"
        formatter: newrelicFormatter
    formatters:
      newrelicFormatter:
        class: newrelic.agent.NewRelicContextFormatter
```
2. Log things with the lower level
```python
import logging
from dagster import op, job


@op
def test_log():
    my_logger = logging.getLogger("my_logger")
    my_logger.exception(Exception("Test")) # works correctly
    my_logger.debug("I am debug") # Should not log to file. But it did.

@job
def hello_dagster():
    test_log()
```

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.
