### ISSUE TITLE
PyYAML parser parses date-like strings as datetime objects

### ISSUE THREAD

**Issue by gibsondan** [dagster-io/dagster#6465]
Repro:
Run a job via the dagster CLI with config like this:

```
resources:
  envs:
    config:
      END_DATE: 2021-10-30
```

The same config works in the Launchpad UI, but not when loading from a yaml file.
