### ISSUE TITLE
dagit not showing Raw Compute Log that is present in dagster-run kube pod

### ISSUE THREAD

**Issue by mpomarole** [dagster-io/dagster#7045]
## Summary
I am running a job manually through dagit, when checking the raw compute logs of one of the ops, it says "No log file available".

But when I exec into the kubectl run for the run and look for the file `/tmp/clicampo-dagster-compute-logs/458666b7-94cb-484e-aeac-250701a575f1/compute_logs/farmers_orders_history.out`, which is listed at the bottom of the dagit window. I can cat the logs with `kubectl exec`.

## Reproduction

1. Run my job in dagit
2. Go to Raw compute logs
3. See `No log file available`
4. Run `kubectl exec -ti dagster-run-458666b7-94cb-484e-aeac-250701a575f1-vcmfr -- cat /tmp/clicampo-dagster-compute-logs/458666b7-94cb-484e-aeac-250701a575f1/compute_logs/farmers_orders_history.out`. Now I can see logs

## Dagit UI/UX Issue Screenshots

<img width="1147" alt="Screen Shot 2022-03-14 at 6 56 14 AM" src="https://user-images.githubusercontent.com/333924/158149012-ed747d03-dceb-4ea4-b07f-ef7d562a57bf.png">

<img width="1147" alt="Screen Shot 2022-03-14 at 6 59 40 AM" src="https://user-images.githubusercontent.com/333924/158149492-7eb565f8-e07c-4e8d-92d2-58190061a569.png">

## Additional Info about Your Environment
I am running dagit on k8s with argocd pulling in the information from helm charts. 
```
  computeLogManager:
    type: S3ComputeLogManager
    config:
      s3ComputeLogManager:
        bucket: "core-shared-clicampo-dagster-compute-logs"
        localDir: "/tmp/clicampo-dagster-compute-logs"
        prefix: "clicampo-dagster-"
```
note: additional problem that I am trying to debug, the s3 bucket is also not getting written to.

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.
