### ISSUE TITLE
[Documentation Feedback] Example run config for multiprocess executor results in error

### ISSUE THREAD

**Issue by markfickett** [dagster-io/dagster#7588]
The multiprocess executor docs (under #dagster.multiprocess_executor) say the config should be

```yaml
# error
execution:
  multiprocess:
    config:
      max_concurrent: 4
```

but actually that gets errors for me, it has to be:

```yaml
# corrected
execution:
  config:
    multiprocess:
        max_concurrent: 32
```

Also, where it says "in your config" it would be helpful to say "in your run config" (to differentiate from your dagster.yaml config).
