### ISSUE TITLE
Test if Helm chart works with multiple user-code-deployment releases

### ISSUE THREAD

**Issue by johannkm** [dagster-io/dagster#7843]
We only test using one release of the separate user-code-deployment chart. Unclear if things would work when running multiple. Test this out

**Comment by justinberedo** [comment]
I tried this out today because I was curious about deploying multiple user-code-deployments. On the `values.yaml`, I set `dagster-user-deployments.enableSubchart` to false. Also, I set `dagit.workspace` with the following values:
```
dagit:
  workspace:
      enabled: true
      servers:
        - host: "k8s-example-user-code-1"
          port: 3030
          name: "user-code-example-1"
        - host: "k8s-example-user-code-2"
          port: 3031
          name: "user-code-example-2"
```
I deployed two user code deployment charts with hostnames and ports shown above. I used the example user code deployment image `docker.io/dagster/user-code-example`.

Result:
![image](https://user-images.githubusercontent.com/57856620/182279709-9095d1a8-26d2-4ad8-a040-4a1be2413884.png)

So I think it works. I was able to run the `single_pod_job` for both user code deployments.
