### ISSUE TITLE
Azure ACI  kubernetes failure caused by dagster command in args

### ISSUE THREAD

**Issue by TimoFriedri** [dagster-io/dagster#8481]
## Summary
Dagster pods cannot start on Azure ACI nodes due to an accepted feature request: [Issue](https://github.com/dagster-io/dagster/issues/3081)

The kubernetes spec ATM only have args and no command. Azure ACI nodes require a command and deny to run pods without one!
I think the everything in the args is a unclean workaround!

Please revert the following commit: [link](https://dagster.phacility.com/D5452)

## Reproduction
Spawn runs on Azure ACI nodes with nodeSelector and tolerations decribed like here: [link](https://github.com/virtual-kubelet/azure-aci/blob/master/README.md#readme)

## Logs
``` yaml
Name:           ######
Namespace:      ######
Priority:       0
Node:           virtual-node-aci-linux/
Labels:         app.kubernetes.io/component=run_worker
                app.kubernetes.io/instance=dagster
                app.kubernetes.io/name=dagster
                app.kubernetes.io/part-of=dagster
                app.kubernetes.io/version=0.15.0
                controller-uid=######
                dagster/job=Cost_Revenue_Unit
                dagster/run-id=######
                job-name=######
Annotations:    <none>
Status:         Failed
Reason:         ProviderFailed
Message:        ACI does not support providing args without specifying the command. Please supply both command and args to the pod spec.
IP:             
IPs:            <none>
Controlled By:  Job/dagster-run-######
Containers:
  dagster:
    Image:      ########
    Port:       <none>
    Host Port:  <none>
    Args:
      dagster
      api
      execute_run
      {###########}
    Environment:
      DAGSTER_HOME:         /opt/dagster/dagster_home
      DAGSTER_PG_PASSWORD:  <set to the key 'postgresql-password' in secret 'dagster-postgresql-secret'>  Optional: false
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-9g5g4 (ro)
Conditions:
  Type           Status
  PodScheduled   True 
Volumes:
  kube-api-access-9g5g4:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              beta.kubernetes.io/os=linux
                             kubernetes.io/role=agent
                             type=virtual-kubelet
Tolerations:                 azure.com/aci:NoSchedule
                             node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
                             virtual-kubelet.io/provider op=Exists
Events:
  Type     Reason                Age   From                                   Message
  ----     ------                ----  ----                                   -------
  Normal   Scheduled             10s   default-scheduler                      Successfully assigned ######/dagster-run-###### to virtual-node-aci-linux
  Warning  ProviderCreateFailed  11s   virtual-node-aci-linux/pod-controller  ACI does not support providing args without specifying the command. Please supply both command and args to the pod spec.
```

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.
