### ISSUE TITLE
enable per-source-asset configuration on IO managers

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#9351]
IO managers currently support `input_config_schema` and `output_config_schema`.  `output_config_schema` allows providing configuration that dictates:
1. how a particular output (or asset) is stored
2. how it's loaded in all the downstream places it's used

Analogous "how it's loaded in all the downstream places it's used" config might also be useful for source assets.

This would be useful in a situation where you want to kick off a run that targets a particular file that you decide at runtime.

**Comment by acroz** [comment]
This sounds useful. For what it's worth, the "natural" place for me to have this config would be in the source asset, i.e. if I could do the following:

```python
entities = SourceAsset("entities", config_schema={"url": str})
```

If this config was then available to the IOManager, I could have e.g. a production run read from S3:

```yaml
assets:  # Or perhaps separated as source_assets
  entities:
    config:
      url: s3://mybucket/path/to/entities.csv
```

or a "test" run using a file on the local filesystem:

```yaml
assets:
  entities:
    config:
      url: path/to/entities.csv
```
